// Mappings for Western and Eastern Cham font encodings
const langConverter = new langConverterClass('chr', 'Cherokee');

var map_encoding_names = [
  'Syllabary'
];

langConverter.encoding_data = {
  'Noto Sans Cherokee': {index:0, outputEncoding:'Unicode', outputScript:'Latn'}
  };

private_use_map_combined = {
  'Ꭰ': ['A'],
  'Ꭱ': ['E'],
  'Ꭲ': ['I'],
  'Ꭳ': ['O'],
  'Ꭴ': ['U'],
  'Ꭵ': ['V'],
  'Ꭶ': ['Ga'],
  'Ꭷ': ['Ka'],
  'Ꭸ': ['Ge'],
  'Ꭹ': ['Gi'],
  'Ꭺ': ['Go'],
  'Ꭻ': ['Gu'],
  'Ꭼ': ['Gv'],
  'Ꭽ': ['Ha'],
  'Ꭾ': ['He'],
  'Ꭿ': ['Hi'],
  'Ꮀ': ['Ho'],
  'Ꮁ': ['Hu'],
  'Ꮂ': ['Hv'],
  'Ꮃ': ['La'],
  'Ꮄ': ['Le'],
  'Ꮅ': ['Li'],
  'Ꮆ': ['Lo'],
  'Ꮇ': ['Lu'],
  'Ꮈ': ['Lv'],
  'Ꮉ': ['Ma'],
  'Ꮊ': ['Me'],
  'Ꮋ': ['Mi'],
  'Ꮌ': ['Mo'],
  'Ꮍ': ['Mu'],
  'Ꮎ': ['Na'],
  'Ꮏ': ['Hna'],
  'Ꮐ': ['Nah'],
  'Ꮑ': ['Ne'],
  'Ꮒ': ['Ni'],
  'Ꮓ': ['No'],
  'Ꮔ': ['Nu'],
  'Ꮕ': ['Nv'],
  'Ꮖ': ['Qua'],
  'Ꮗ': ['Qie'],
  'Ꮘ': ['Qui'],
  'Ꮙ': ['Quo'],
  'Ꮚ': ['Quu'],
  'Ꮛ': ['Quv'],
  'Ꮜ': ['Sa'],
  'Ꮝ': ['S'],
  'Ꮞ': ['Se'],
  'Ꮟ': ['Si'],
  'Ꮠ': ['So'],
  'Ꮡ': ['Su'],
  'Ꮢ': ['Sv'],
  'Ꮣ': ['Da'],
  'Ꮤ': ['Ta'],
  'Ꮥ': ['De'],
  'Ꮦ': ['Te'],
  'Ꮧ': ['Di'],
  'Ꮨ': ['Ti'],
  'Ꮩ': ['Do'],
  'Ꮪ': ['Du'],
  'Ꮫ': ['Dv'],
  'Ꮬ': ['Dla'],
  'Ꮭ': ['Tla'],
  'Ꮮ': ['Tle'],
  'Ꮯ': ['Tli'],
  'Ꮰ': ['Tlo'],
  'Ꮱ': ['Tlu'],
  'Ꮲ': ['Tlv'],
  'Ꮳ': ['Tsa'],
  'Ꮴ': ['Tse'],
  'Ꮵ': ['Tsi'],
  'Ꮶ': ['Tso'],
  'Ꮷ': ['Tsu'],
  'Ꮸ': ['Tsv'],
  'Ꮹ': ['Wa'],
  'Ꮺ': ['We'],
  'Ꮻ': ['Wi'],
  'Ꮼ': ['Wo'],
  'Ꮽ': ['Wu'],
  'Ꮾ': ['Wv'],
  'Ꮿ': ['Ya'],
  'Ᏸ': ['Ye'],
  'Ᏹ': ['Yi'],
  'Ᏺ': ['Yo'],
  'Ᏻ': ['Yu'],
  'Ᏼ': ['Yv'],
  'Ᏽ': ['Mv'],
  'ᏸ': ['ye'],
  'ᏹ': ['yi'],
  'ᏺ': ['yo'],
  'ᏻ': ['yu'],
  'ᏼ': ['yv'],
  'ᏽ': ['mv'],
  'ꭰ': ['a'],
  'ꭱ': ['e'],
  'ꭲ': ['i'],
  'ꭳ': ['o'],
  'ꭴ': ['u'],
  'ꭵ': ['v'],
  'ꭶ': ['ga'],
  'ꭷ': ['ka'],
  'ꭸ': ['ge'],
  'ꭹ': ['gi'],
  'ꭺ': ['go'],
  'ꭻ': ['gu'],
  'ꭼ': ['gv'],
  'ꭽ': ['ha'],
  'ꭾ': ['he'],
  'ꭿ': ['hi'],
  'ꮀ': ['ho'],
  'ꮁ': ['hu'],
  'ꮂ': ['hv'],
  'ꮃ': ['la'],
  'ꮄ': ['le'],
  'ꮅ': ['li'],
  'ꮆ': ['lo'],
  'ꮇ': ['lu'],
  'ꮈ': ['lv'],
  'ꮉ': ['ma'],
  'ꮊ': ['me'],
  'ꮋ': ['mi'],
  'ꮌ': ['mo'],
  'ꮍ': ['mu'],
  'ꮎ': ['na'],
  'ꮏ': ['hna'],
  'ꮐ': ['nah'],
  'ꮑ': ['ne'],
  'ꮒ': ['ni'],
  'ꮓ': ['no'],
  'ꮔ': ['nu'],
  'ꮕ': ['nv'],
  'ꮖ': ['qua'],
  'ꮗ': ['que'],
  'ꮘ': ['qui'],
  'ꮙ': ['quo'],
  'ꮚ': ['quu'],
  'ꮛ': ['quv'],
  'ꮜ': ['sa'],
  'ꮝ': ['s'],
  'ꮞ': ['se'],
  'ꮟ': ['si'],
  'ꮠ': ['so'],
  'ꮡ': ['su'],
  'ꮢ': ['sv'],
  'ꮣ': ['da'],
  'ꮤ': ['ta'],
  'ꮥ': ['de'],
  'ꮦ': ['te'],
  'ꮧ': ['di'],
  'ꮨ': ['ti'],
  'ꮩ': ['do'],
  'ꮪ': ['du'],
  'ꮫ': ['dv'],
  'ꮬ': ['dla'],
  'ꮭ': ['tla'],
  'ꮮ': ['tle'],
  'ꮯ': ['tli'],
  'ꮰ': ['tlo'],
  'ꮱ': ['tlu'],
  'ꮲ': ['tlv'],
  'ꮳ': ['tsa'],
  'ꮴ': ['tse'],
  'ꮵ': ['tsi'],
  'ꮶ': ['tso'],
  'ꮷ': ['tsu'],
  'ꮸ': ['tsv'],
  'ꮹ': ['wa'],
  'ꮺ': ['we'],
  'ꮻ': ['wi'],
  'ꮼ': ['wo'],
  'ꮽ': ['wu'],
  'ꮾ': ['wv'],
  'ꮿ': ['ya']
};

langConverter.one2oneMap = langConverter.dictionaryToMap(private_use_map_combined);

  // Anything else needed?

  // Capitalize at start of sentences?
