// Convert from Latin form of Tangsa to Lakhum Unicode forms:

// Mappings for Tangsa Lakhum
var map_encoding_names = [
  'Gam Win',
  'Gam Win Unicode',
];

var private_use_map_combined = {
    'mnvungz': ['', '𖪜𖪬𖩸𖪄𖪐'],
    'mznvungz': ['', '𖪜𖪬𖩸𖪄𖪐'],
    'mnaungz': ['', '𖪜𖪬𖩴𖪄𖪐'],
    'mznaungz': ['', '𖪜𖪬𖩴𖪄𖪐'],
    'mrvkueq': ['', '𖪜𖪲𖩸𖪠𖪖'],
    'vungz': ['', '𖩸𖪄𖪐'],
    'vungc': ['', '𖩹𖪅𖪐'],
    'vungx': ['', '𖩻𖪇𖪐'],
    'vuk': ['', '𖩸𖪄𖪠'],
    'aungz': ['', '𖩴𖪄𖪐'],
    'aungc': ['', '𖩵𖪅𖪐'],
    'aungx': ['', '𖩷𖪇𖪐'],
    'auk': ['', '𖩴𖪄𖪠'],
    'auz': ['', '𖩴𖪄'],
    'auc': ['', '𖩵𖪅'],
    'aux': ['', '𖩷𖪇'],
    'vuq': ['', '𖩸𖪆'],
    'auq': ['', '𖩴𖪆'],
    'ovrz': ['', '𖩰𖩸𖪲'],
    'ovrc': ['', '𖩱𖩹𖪲'],
    'ovrx': ['', '𖩳𖩻𖪲'],
    'uiyq': ['', '𖪌𖪂'],
    'vyq': ['', '𖩸𖪂'],
    'oq': ['', '𖩲'],
    'aq': ['', '𖩶'],
    'vq': ['', '𖩺'],
    'eq': ['', '𖩾'],
    'iq': ['', '𖪂'],
    'uq': ['', '𖪆'],
    'awq': ['', '𖪊'],
    'uiq': ['', '𖪎'],
    'ueq': ['', '𖪖'],
    'uiuq': ['', '𖪘'],
    'uiuq': ['', '𖪌𖪆'],
    'uiuq': ['', '𖪎𖪆'],
    'ovyz': ['', '𖩰𖩸𖪀'],
    'ovyc': ['', '𖩱𖩹𖪁'],
    'ovyx': ['', '𖩳𖩻𖪃'],
    'oayz': ['', '𖩰𖪀'],
    'oayc': ['', '𖩱𖪁'],
    'oayx': ['', '𖩳𖪃'],
    'ayz': ['', '𖩴𖪀'],
    'ayc': ['', '𖩵𖪁'],
    'ayx': ['', '𖩷𖪃'],
    'vyz': ['', '𖩸𖪀'],
    'vyc': ['', '𖩹𖪁'],
    'vyx': ['', '𖩻𖪃'],
    'uyz': ['', '𖪄𖪀'],
    'uyc': ['', '𖪅𖪁'],
    'uyx': ['', '𖪇𖪃'],
    'uiyz': ['', '𖪌𖪀'],
    'uiyc': ['', '𖪍𖪁'],
    'uiyx': ['', '𖪏𖪇'],
    'ueyz': ['', '𖪕𖪀'],
    'ueyc': ['', '𖪔𖪁'],
    'ueyx': ['', '𖪗𖪃'],
    'ongz': ['', '𖩰𖪐'],
    'ongc': ['', '𖩱𖪐'],
    'ongx': ['', '𖩳𖪐'],
    'angz': ['', '𖩴𖪐'],
    'angc': ['', '𖩵𖪐'],
    'angx': ['', '𖩷𖪐'],
    'vngz': ['', '𖩸𖪐'],
    'vngc': ['', '𖩹𖪐'],
    'vngx': ['', '𖩻𖪐'],
    'engz': ['', '𖩼𖪐'],
    'engc': ['', '𖩽𖪐'],
    'engx': ['', '𖩿𖪐'],
    'ingz': ['', '𖪀𖪐'],
    'ingc': ['', '𖪁𖪐'],
    'ingx': ['', '𖪃𖪐'],
    'ungz': ['', '𖪄𖪐'],
    'ungc': ['', '𖪅𖪐'],
    'ungx': ['', '𖪇𖪐'],
    'awngz': ['', '𖩼𖪐'],
    'awngc': ['', '𖪉𖪐'],
    'awngx': ['', '𖪋𖪐'],
    'uingz': ['', '𖪌𖪐'],
    'uingc': ['', '𖪍𖪐'],
    'uingx': ['', '𖪏𖪐'],
    'uengz': ['', '𖪕𖪐'],
    'uengc': ['', '𖪔𖪐'],
    'uengx': ['', '𖪗𖪐'],
    'uiungz': ['', '𖪘𖪐'],
    'uiungc': ['', '𖪙𖪐'],
    'uiungx': ['', '𖪛𖪐'],
    'ovmz': ['', '𖩰𖩸𖪫'],
    'ovmc': ['', '𖩱𖩹𖪫'],
    'ovmx': ['', '𖩳𖩻𖪫'],
    'omz': ['', '𖩰𖪫'],
    'omc': ['', '𖩱𖪫'],
    'omx': ['', '𖩳𖪫'],
    'oamz': ['', '𖩰𖪫'],
    'oamc': ['', '𖩱𖪫'],
    'oamx': ['', '𖩳𖪫'],
    'amz': ['', '𖩴𖪫'],
    'amc': ['', '𖩵𖪫'],
    'amx': ['', '𖩷𖪫'],
    'vmz': ['', '𖩸𖪫'],
    'vmc': ['', '𖩹𖪫'],
    'vmx': ['', '𖩻𖪫'],
    'emz': ['', '𖩼𖪫'],
    'emc': ['', '𖩽𖪫'],
    'emx': ['', '𖩿𖪫'],
    'imz': ['', '𖪀𖪫'],
    'imc': ['', '𖪁𖪫'],
    'imx': ['', '𖪃𖪫'],
    'umz': ['', '𖪄𖪫'],
    'umc': ['', '𖪅𖪫'],
    'umx': ['', '𖪇𖪫'],
    'awmz': ['', '𖩼𖪫'],
    'awmc': ['', '𖪉𖪫'],
    'awmx': ['', '𖪋𖪫'],
    'uimz': ['', '𖪌𖪫'],
    'uimc': ['', '𖪍𖪫'],
    'uimx': ['', '𖪏𖪫'],
    'uemz': ['', '𖪕𖪫'],
    'uemc': ['', '𖪔𖪫'],
    'uemx': ['', '𖪗𖪫'],
    'uiumz': ['', '𖪘𖪫'],
    'uiumc': ['', '𖪙𖪫'],
    'uiumx': ['', '𖪛𖪫'],
    'ovnz': ['', '𖩰𖩸𖪬'],
    'ovnc': ['', '𖩱𖩹𖪬'],
    'ovnx': ['', '𖩳𖩻𖪬'],
    'oanz': ['', '𖩰𖪬'],
    'oanc': ['', '𖩱𖪬'],
    'oanx': ['', '𖩳𖪬'],
    'anz': ['', '𖩴𖪬'],
    'anc': ['', '𖩵𖪬'],
    'anx': ['', '𖩷𖪬'],
    'vnz': ['', '𖩸𖪬'],
    'vnc': ['', '𖩹𖪬'],
    'vnx': ['', '𖩻𖪬'],
    'enz': ['', '𖩼𖪬'],
    'enc': ['', '𖩽𖪬'],
    'enx': ['', '𖩿𖪬'],
    'inz': ['', '𖪀𖪬'],
    'inc': ['', '𖪁𖪬'],
    'inx': ['', '𖪃𖪬'],
    'unz': ['', '𖪄𖪬'],
    'unc': ['', '𖪅𖪬'],
    'unx': ['', '𖪇𖪬'],
    'awnz': ['', '𖩼𖪬'],
    'awnc': ['', '𖪉𖪬'],
    'awnx': ['', '𖪋𖪬'],
    'uinz': ['', '𖪌𖪬'],
    'uinc': ['', '𖪍𖪬'],
    'uinx': ['', '𖪏𖪬'],
    'uenz': ['', '𖪕𖪬'],
    'uenc': ['', '𖪔𖪬'],
    'uenx': ['', '𖪗𖪬'],
    'uiunz': ['', '𖪘𖪬'],
    'uiunc': ['', '𖪙𖪬'],
    'uiunx': ['', '𖪛𖪬'],
    'ovlz': ['', '𖩰𖩸𖪮'],
    'ovlc': ['', '𖩱𖩹𖪮'],
    'ovlx': ['', '𖩳𖩻𖪮'],
    'oalz': ['', '𖩰𖪮'],
    'oalc': ['', '𖩱𖪮'],
    'oalx': ['', '𖩳𖪮'],
    'alz': ['', '𖩴𖪮'],
    'alc': ['', '𖩵𖪮'],
    'alx': ['', '𖩷𖪮'],
    'vlz': ['', '𖩸𖪮'],
    'vlc': ['', '𖩹𖪮'],
    'vlx': ['', '𖩻𖪮'],
    'elz': ['', '𖩼𖪮'],
    'elc': ['', '𖩽𖪮'],
    'elx': ['', '𖩿𖪮'],
    'ilz': ['', '𖪀𖪮'],
    'ilc': ['', '𖪁𖪮'],
    'ilx': ['', '𖪃𖪮'],
    'ulz': ['', '𖪄𖪮'],
    'ulc': ['', '𖪅𖪮'],
    'ulx': ['', '𖪇𖪮'],
    'awlz': ['', '𖩼𖪮'],
    'awlc': ['', '𖪉𖪮'],
    'awlx': ['', '𖪋𖪮'],
    'uilz': ['', '𖪌𖪮'],
    'uilc': ['', '𖪍𖪮'],
    'uilx': ['', '𖪏𖪮'],
    'uelz': ['', '𖪕𖪮'],
    'uelc': ['', '𖪔𖪮'],
    'uelx': ['', '𖪗𖪮'],
    'uiulz': ['', '𖪘𖪮'],
    'uiulc': ['', '𖪙𖪮'],
    'uiulx': ['', '𖪛𖪮'],
    'ovrz': ['', '𖩰𖪲'],
    'ovrc': ['', '𖩱𖪲'],
    'ovrx': ['', '𖩳𖪲'],
    'oarz': ['', '𖩰𖪲'],
    'oarc': ['', '𖩱𖪲'],
    'oarx': ['', '𖩳𖪲'],
    'arz': ['', '𖩴𖪲'],
    'arc': ['', '𖩵𖪲'],
    'arx': ['', '𖩷𖪲'],
    'vrz': ['', '𖩸𖪲'],
    'vrc': ['', '𖩹𖪲'],
    'vrx': ['', '𖩻𖪲'],
    'erz': ['', '𖩼𖪲'],
    'erc': ['', '𖩽𖪲'],
    'erx': ['', '𖩿𖪲'],
    'irz': ['', '𖪀𖪲'],
    'irc': ['', '𖪁𖪲'],
    'irx': ['', '𖪃𖪲'],
    'urz': ['', '𖪄𖪲'],
    'urc': ['', '𖪅𖪲'],
    'urx': ['', '𖪇𖪲'],
    'awrz': ['', '𖩼𖪲'],
    'awrc': ['', '𖪉𖪲'],
    'awrx': ['', '𖪋𖪲'],
    'uirz': ['', '𖪌𖪲'],
    'uirc': ['', '𖪍𖪲'],
    'uirx': ['', '𖪏𖪲'],
    'uerz': ['', '𖪕𖪲'],
    'uerc': ['', '𖪔𖪲'],
    'uerx': ['', '𖪗𖪲'],
    'uiurz': ['', '𖪘𖪲'],
    'uiurc': ['', '𖪙𖪲'],
    'uiurx': ['', '𖪛𖪲'],
    'ok': ['', '𖩰𖪠'],
    'ak': ['', '𖩴𖪠'],
    'vk': ['', '𖩸𖪠'],
    'ek': ['', '𖩼𖪠'],
    'ik': ['', '𖪀𖪠'],
    'uk': ['', '𖪄𖪠'],
    'awk': ['', '𖪈𖪠'],
    'uik': ['', '𖪌𖪠'],
    'uek': ['', '𖪒𖪠'],
    'uiuk': ['', '𖪘𖪠'],
    'ovp': ['', '𖩰𖩸𖪧'],
    'oap ~ op': ['', '𖩰𖪧'],
    'op': ['', '𖩰𖪧'],
    'ap': ['', '𖩴𖪧'],
    'vp': ['', '𖩸𖪧'],
    'ep': ['', '𖩼𖪧'],
    'ip': ['', '𖪀𖪧'],
    'up': ['', '𖪄𖪧'],
    'awp': ['', '𖪈𖪧'],
    'uip': ['', '𖪌𖪧'],
    'uep': ['', '𖪒𖪧'],
    'uiup': ['', '𖪘𖪧'],
    'ovt': ['', '𖩰𖩸𖪰'],
    'oat': ['', '𖩰𖪰'],
    'at': ['', '𖩴𖪰'],
    'vt': ['', '𖩸𖪰'],
    'et': ['', '𖩼𖪰'],
    'it': ['', '𖪀𖪰'],
    'ut': ['', '𖪄𖪰'],
    'awt': ['', '𖪈𖪰'],
    'uit': ['', '𖪌𖪰'],
    'uet': ['', '𖪒𖪰'],
    'uiut': ['', '𖪘𖪰'],
    'oz': ['', '𖩰'],
    'oc': ['', '𖩱'],
    'ox': ['', '𖩳'],
    'az': ['', '𖩴'],
    'ac': ['', '𖩵'],
    'ax': ['', '𖩷'],
    'vz': ['', '𖩸'],
    'vc': ['', '𖩹'],
    'vx': ['', '𖩻'],
    'ez': ['', '𖩼'],
    'ec': ['', '𖩽'],
    'ex': ['', '𖩿'],
    'iz': ['', '𖪀'],
    'ic': ['', '𖪁'],
    'ix': ['', '𖪃'],
    'uz': ['', '𖪄'],
    'uc': ['', '𖪅'],
    'ux': ['', '𖪇'],
    'awz': ['', '𖩼'],
    'awc': ['', '𖪉'],
    'awx': ['', '𖪋'],
    'uiz': ['', '𖪌'],
    'uic': ['', '𖪍'],
    'uix': ['', '𖪏'],
    'uez': ['', '𖪕'],
    'uec': ['', '𖪔'],
    'uex': ['', '𖪗'],
    'uiuz': ['', '𖪘'],
    'uiuc': ['', '𖪙'],
    'uiux': ['', '𖪛'],
    'htt': ['', '𖪸'],
    'th': ['', '𖪹'],
    'ht': ['', '𖪯'],
    'ch': ['', '𖪼'],
    'kh': ['', '𖪡'],
    'ng': ['', '𖪣'],
    'ny': ['', '𖪨'],
    'ph': ['', '𖪩'],
    'nh': ['', '𖪳'],
    'sh': ['', '𖪴'],
    'ts': ['', '𖪶'],
    'gh': ['', '𖪷'],
    'f': ['', '𖪺'],
    'k': ['', '𖪠'],
    'g': ['', '𖪢'],
    's': ['', '𖪤'],
    'y': ['', '𖪥'],
    'w': ['', '𖪦'],
    'p': ['', '𖪧'],
    'b': ['', '𖪪'],
    'm': ['', '𖪫'],
    'n': ['', '𖪬'],
    'h': ['', '𖪭'],
    'l': ['', '𖪮'],
    't': ['', '𖪰'],
    'd': ['', '𖪱'],
    'r': ['', '𖪲'],
    'j': ['', '𖪵'],
    'v': ['', '𖩸'],
    ' ': [' '],
  };

var private_use_map_combined_OLD = {
  // Gam Win --> Lakhum personal area code
  'tv': ['𖪰𖩺'],  // ???
  'mnvungz': ['\ud81a\ude9c\ud81a\udeac\ud81a\ude7a\ud81a\ude84\ud81a\ude90'],
  'mznvungz': ['\ud81a\ude9c\ud81a\udeac\ud81a\ude7a\ud81a\ude84\ud81a\ude90'],
  'mnaungz': ['\ud81a\ude9c\ud81a\udeac\ud81a\ude74\ud81a\ude84\ud81a\ude90'],
  'vungz': ['\ud81a\ude7a\ud81a\ude84\ud81a\ude90'],
  'vungc': ['\ud81a\ude79\ud81a\ude85\ud81a\ude90'],
  'vungx': ['\ud81a\ude7b\ud81a\ude87\ud81a\ude90'],
  'vuk': ['\ud81a\ude7a\ud81a\ude86\ud81a\udea0'],
  'ovyz': ['\ud81a\ude70\ud81a\ude80'],
  'ovyc': ['\ud81a\ude71\ud81a\ude81'],
  'ovyx': ['\ud81a\ude73\ud81a\ude83'],
  'ovmz': ['\ud81a\ude70\ud81a\udeab'],
  'ovmc': ['\ud81a\ude71\ud81a\udeab'],
  'ovmx': ['\ud81a\ude73\ud81a\udeab'],
  'oamz': ['\ud81a\ude70\ud81a\udeab'],
  'oamc': ['\ud81a\ude71\ud81a\udeab'],
  'oamx': ['\ud81a\ude73\ud81a\udeab'],
  'omz': ['\ud81a\ude70\ud81a\udeab'],
  'omc': ['\ud81a\ude71\ud81a\udeab'],
  'omx': ['\ud81a\ude73\ud81a\udeab'],
  'ovnz': ['\ud81a\ude70\ud81a\udeac'],
  'ovnc': ['\ud81a\ude71\ud81a\udeac'],
  'ovnx': ['\ud81a\ude73\ud81a\udeac'],
  'ovlz': ['\ud81a\ude70\ud81a\udeae'],
  'ovlc': ['\ud81a\ude71\ud81a\udeae'],
  'ovlx': ['\ud81a\ude73\ud81a\udeae'],
  'ovrz': ['\ud81a\ude70\ud81a\udeb2'],
  'ovrc': ['\ud81a\ude71\ud81a\udeb2'],
  'ovrx': ['\ud81a\ude73\ud81a\udeb2'],
  'ovp': ['\ud81a\ude70\ud81a\udea7'],
  'ovt': ['\ud81a\ude70\ud81a\udeb0'],
  'mnaungz': ['\ud81a\ude9c\ud81a\udeac\ud81a\ude74\ud81a\ude84\ud81a\ude90'],
  'mznaungz': ['\ud81a\ude9c\ud81a\udeac\ud81a\ude74\ud81a\ude84\ud81a\ude90'],
  'mrvkueq': ['\ud81a\ude9c\ud81a\udeb2\ud81a\ude7a\ud81a\udea0\ud81a\ude96'],
  'aungz': ['\ud81a\ude74\ud81a\ude84\ud81a\ude90'],
  'aungc': ['\ud81a\ude75\ud81a\ude85\ud81a\ude90'],
  'aungx': ['\ud81a\ude77\ud81a\ude87\ud81a\ude90'],
  'auk': ['\ud81a\ude74\ud81a\ude86\ud81a\udea0'],
  'uiyq': ['\ud81a\ude8c\ud81a\ude82'],
  'vyq': ['\ud81a\ude7a\ud81a\ude82'],
  'oq': ['\ud81a\ude72'],
  'aq': ['\ud81a\ude76'],
  'vq': ['\ud81a\ude7a'],
  'eq': ['\ud81a\ude7e'],
  'iq': ['\ud81a\ude82'],
  'uq': ['\ud81a\ude86'],
  'awq': ['\ud81a\ude8a'],
  'uiq': ['\ud81a\ude8e'],
  'ueq': ['\ud81a\ude96'],
  'uiuq': ['\ud81a\ude9a'],
  'oayz': ['\ud81a\ude70\ud81a\ude80'],
  'oayc': ['\ud81a\ude71\ud81a\ude81'],
  'oayx': ['\ud81a\ude73\ud81a\ude83'],
  'ayz': ['\ud81a\ude74\ud81a\ude80'],
  'ayc': ['\ud81a\ude75\ud81a\ude81'],
  'ayx': ['\ud81a\ude77\ud81a\ude83'],
  'vyz': ['\ud81a\ude7a\ud81a\ude80'],
  'vyc': ['\ud81a\ude79\ud81a\ude81'],
  'vyx': ['\ud81a\ude7b\ud81a\ude83'],
  'uyz': ['\ud81a\ude84\ud81a\ude80'],
  'uyc': ['\ud81a\ude85\ud81a\ude81'],
  'uyx': ['\ud81a\ude87\ud81a\ude83'],
  'uiyz': ['\ud81a\ude8c\ud81a\ude80'],
  'uiyc': ['\ud81a\ude8d\ud81a\ude81'],
  'uiyx': ['\ud81a\ude8f\ud81a\ude83'],
  'ueyz': ['\ud81a\ude95\ud81a\ude80'],
  'ueyc': ['\ud81a\ude94\ud81a\ude81'],
  'ueyx': ['\ud81a\ude97\ud81a\ude83'],
  'ongz': ['\ud81a\ude70\ud81a\ude90'],
  'ongc': ['\ud81a\ude71\ud81a\ude90'],
  'ongx': ['\ud81a\ude73\ud81a\ude90'],
  'angz': ['\ud81a\ude74\ud81a\ude90'],
  'angc': ['\ud81a\ude75\ud81a\ude90'],
  'angx': ['\ud81a\ude77\ud81a\ude90'],
  'vngz': ['\ud81a\ude7a\ud81a\ude90'],
  'vngc': ['\ud81a\ude79\ud81a\ude90'],
  'vngx': ['\ud81a\ude7b\ud81a\ude90'],
  'engz': ['\ud81a\ude7c\ud81a\ude90'],
  'engc': ['\ud81a\ude7d\ud81a\ude90'],
  'engx': ['\ud81a\ude7f\ud81a\ude90'],
  'ingz': ['\ud81a\ude80\ud81a\ude90'],
  'ingc': ['\ud81a\ude81\ud81a\ude90'],
  'ingx': ['\ud81a\ude83\ud81a\ude90'],
  'ungz': ['\ud81a\ude84\ud81a\ude90'],
  'ungc': ['\ud81a\ude85\ud81a\ude90'],
  'ungx': ['\ud81a\ude87\ud81a\ude90'],
  'awngz': ['\ud81a\ude88\ud81a\ude90'],
  'awngc': ['\ud81a\ude89\ud81a\ude90'],
  'awngx': ['\ud81a\ude8b\ud81a\ude90'],
  'uingz': ['\ud81a\ude8c\ud81a\ude90'],
  'uingc': ['\ud81a\ude8d\ud81a\ude90'],
  'uingx': ['\ud81a\ude8f\ud81a\ude90'],
  'uengz': ['\ud81a\ude95\ud81a\ude90'],
  'uengc': ['\ud81a\ude94\ud81a\ude90'],
  'uengx': ['\ud81a\ude97\ud81a\ude90'],
  'uiungz': ['\ud81a\ude98\ud81a\ude90'],
  'uiungc': ['\ud81a\ude99\ud81a\ude90'],
  'uiungx': ['\ud81a\ude9b\ud81a\ude90'],
  'amz': ['\ud81a\ude74\ud81a\udeab'],
  'amc': ['\ud81a\ude75\ud81a\udeab'],
  'amx': ['\ud81a\ude77\ud81a\udeab'],
  'vmz': ['\ud81a\ude7a\ud81a\udeab'],
  'vmc': ['\ud81a\ude79\ud81a\udeab'],
  'vmx': ['\ud81a\ude7b\ud81a\udeab'],
  'emz': ['\ud81a\ude7c\ud81a\udeab'],
  'emc': ['\ud81a\ude7d\ud81a\udeab'],
  'emx': ['\ud81a\ude7f\ud81a\udeab'],
  'imz': ['\ud81a\ude80\ud81a\udeab'],
  'imc': ['\ud81a\ude81\ud81a\udeab'],
  'imx': ['\ud81a\ude83\ud81a\udeab'],
  'umz': ['\ud81a\ude84\ud81a\udeab'],
  'umc': ['\ud81a\ude85\ud81a\udeab'],
  'umx': ['\ud81a\ude87\ud81a\udeab'],
  'awmz': ['\ud81a\ude88\ud81a\udeab'],
  'awmc': ['\ud81a\ude89\ud81a\udeab'],
  'awmx': ['\ud81a\ude8b\ud81a\udeab'],
  'uimz': ['\ud81a\ude8c\ud81a\udeab'],
  'uimc': ['\ud81a\ude8d\ud81a\udeab'],
  'uimx': ['\ud81a\ude8f\ud81a\udeab'],
  'uemz': ['\ud81a\ude95\ud81a\udeab'],
  'uemc': ['\ud81a\ude94\ud81a\udeab'],
  'uemx': ['\ud81a\ude97\ud81a\udeab'],
  'uiumz': ['\ud81a\ude98\ud81a\udeab'],
  'uiumc': ['\ud81a\ude99\ud81a\udeab'],
  'uiumx': ['\ud81a\ude9b\ud81a\udeab'],
  'oanz': ['\ud81a\ude70\ud81a\udeac'],
  'oanc': ['\ud81a\ude71\ud81a\udeac'],
  'oanx': ['\ud81a\ude73\ud81a\udeac'],
  'anz': ['\ud81a\ude74\ud81a\udeac'],
  'anc': ['\ud81a\ude75\ud81a\udeac'],
  'anx': ['\ud81a\ude77\ud81a\udeac'],
  'vnz': ['\ud81a\ude7a\ud81a\udeac'],
  'vnc': ['\ud81a\ude79\ud81a\udeac'],
  'vnx': ['\ud81a\ude7b\ud81a\udeac'],
  'enz': ['\ud81a\ude7c\ud81a\udeac'],
  'enc': ['\ud81a\ude7d\ud81a\udeac'],
  'enx': ['\ud81a\ude7f\ud81a\udeac'],
  'inz': ['\ud81a\ude80\ud81a\udeac'],
  'inc': ['\ud81a\ude81\ud81a\udeac'],
  'inx': ['\ud81a\ude83\ud81a\udeac'],
  'unz': ['\ud81a\ude84\ud81a\udeac'],
  'unc': ['\ud81a\ude85\ud81a\udeac'],
  'unx': ['\ud81a\ude87\ud81a\udeac'],
  'awnz': ['\ud81a\ude88\ud81a\udeac'],
  'awnc': ['\ud81a\ude89\ud81a\udeac'],
  'awnx': ['\ud81a\ude8b\ud81a\udeac'],
  'uinz': ['\ud81a\ude8c\ud81a\udeac'],
  'uinc': ['\ud81a\ude8d\ud81a\udeac'],
  'uinx': ['\ud81a\ude8f\ud81a\udeac'],
  'uenz': ['\ud81a\ude95\ud81a\udeac'],
  'uenc': ['\ud81a\ude94\ud81a\udeac'],
  'uenx': ['\ud81a\ude97\ud81a\udeac'],
  'uiunz': ['\ud81a\ude98\ud81a\udeac'],
  'uiunc': ['\ud81a\ude99\ud81a\udeac'],
  'uiunx': ['\ud81a\ude9b\ud81a\udeac'],
  'oalz': ['\ud81a\ude70\ud81a\udeae'],
  'oalc': ['\ud81a\ude71\ud81a\udeae'],
  'oalx': ['\ud81a\ude73\ud81a\udeae'],
  'alz': ['\ud81a\ude74\ud81a\udeae'],
  'alc': ['\ud81a\ude75\ud81a\udeae'],
  'alx': ['\ud81a\ude77\ud81a\udeae'],
  'vlz': ['\ud81a\ude7a\ud81a\udeae'],
  'vlc': ['\ud81a\ude79\ud81a\udeae'],
  'vlx': ['\ud81a\ude7b\ud81a\udeae'],
  'elz': ['\ud81a\ude7c\ud81a\udeae'],
  'elc': ['\ud81a\ude7d\ud81a\udeae'],
  'elx': ['\ud81a\ude7f\ud81a\udeae'],
  'ilz': ['\ud81a\ude80\ud81a\udeae'],
  'ilc': ['\ud81a\ude81\ud81a\udeae'],
  'ilx': ['\ud81a\ude83\ud81a\udeae'],
  'ulz': ['\ud81a\ude84\ud81a\udeae'],
  'ulc': ['\ud81a\ude85\ud81a\udeae'],
  'ulx': ['\ud81a\ude87\ud81a\udeae'],
  'awlz': ['\ud81a\ude88\ud81a\udeae'],
  'awlc': ['\ud81a\ude89\ud81a\udeae'],
  'awlx': ['\ud81a\ude8b\ud81a\udeae'],
  'uilz': ['\ud81a\ude8c\ud81a\udeae'],
  'uilc': ['\ud81a\ude8d\ud81a\udeae'],
  'uilx': ['\ud81a\ude8f\ud81a\udeae'],
  'uelz': ['\ud81a\ude95\ud81a\udeae'],
  'uelc': ['\ud81a\ude94\ud81a\udeae'],
  'uelx': ['\ud81a\ude97\ud81a\udeae'],
  'uiulz': ['\ud81a\ude98\ud81a\udeae'],
  'uiulc': ['\ud81a\ude99\ud81a\udeae'],
  'uiulx': ['\ud81a\ude9b\ud81a\udeae'],
  'oarz': ['\ud81a\ude70\ud81a\udeb2'],
  'oarc': ['\ud81a\ude71\ud81a\udeb2'],
  'oarx': ['\ud81a\ude73\ud81a\udeb2'],
  'arz': ['\ud81a\ude74\ud81a\udeb2'],
  'arc': ['\ud81a\ude75\ud81a\udeb2'],
  'arx': ['\ud81a\ude77\ud81a\udeb2'],
  'vrz': ['\ud81a\ude7a\ud81a\udeb2'],
  'vrc': ['\ud81a\ude79\ud81a\udeb2'],
  'vrx': ['\ud81a\ude7b\ud81a\udeb2'],
  'erz': ['\ud81a\ude7c\ud81a\udeb2'],
  'erc': ['\ud81a\ude7d\ud81a\udeb2'],
  'erx': ['\ud81a\ude7f\ud81a\udeb2'],
  'irz': ['\ud81a\ude80\ud81a\udeb2'],
  'irc': ['\ud81a\ude81\ud81a\udeb2'],
  'irx': ['\ud81a\ude83\ud81a\udeb2'],
  'urz': ['\ud81a\ude84\ud81a\udeb2'],
  'urc': ['\ud81a\ude85\ud81a\udeb2'],
  'urx': ['\ud81a\ude87\ud81a\udeb2'],
  'awrz': ['\ud81a\ude88\ud81a\udeb2'],
  'awrc': ['\ud81a\ude89\ud81a\udeb2'],
  'awrx': ['\ud81a\ude8b\ud81a\udeb2'],
  'uirz': ['\ud81a\ude8c\ud81a\udeb2'],
  'uirc': ['\ud81a\ude8d\ud81a\udeb2'],
  'uirx': ['\ud81a\ude8f\ud81a\udeb2'],
  'uerz': ['\ud81a\ude95\ud81a\udeb2'],
  'uerc': ['\ud81a\ude94\ud81a\udeb2'],
  'uerx': ['\ud81a\ude97\ud81a\udeb2'],
  'uiurz': ['\ud81a\ude98\ud81a\udeb2'],
  'uiurc': ['\ud81a\ude99\ud81a\udeb2'],
  'uiurx': ['\ud81a\ude9b\ud81a\udeb2'],
  'ok': ['\ud81a\ude70\ud81a\udea0'],
  'ak': ['\ud81a\ude74\ud81a\udea0'],
  'vk': ['\ud81a\ude7a\ud81a\udea0'],
  'ek': ['\ud81a\ude7c\ud81a\udea0'],
  'ik': ['\ud81a\ude80\ud81a\udea0'],
  'uk': ['\ud81a\ude84\ud81a\ude98'],
  'awk': ['\ud81a\ude88\ud81a\udea0'],
  'uik': ['\ud81a\ude8c\ud81a\udea0'],  // Changed from 17, 23
  'uek': ['\ud81a\ude95\ud81a\udea0'],
  'uiuk': ['\ud81a\ude98\ud81a\udea0'],
  'oap': ['\ud81a\ude70\ud81a\udea7'],
  'op': ['\ud81a\ude70\ud81a\udea7'],
  'ap': ['\ud81a\ude74\ud81a\udea7'],
  'vp': ['\ud81a\ude7a\ud81a\udea7'],
  'ep': ['\ud81a\ude7c\ud81a\udea7'],
  'ip': ['\ud81a\ude80\ud81a\udea7'],
  'up': ['\ud81a\ude84\ud81a\udea7'],
  'awp': ['\ud81a\ude88\ud81a\udea7'],
  'uip': ['\ud81a\ude8c\ud81a\udea7'],
  'uep': ['\ud81a\ude95\ud81a\udea7'],
  'uiup': ['\ud81a\udea7\ud81a\udea7'],
  'oat': ['\ud81a\ude70\ud81a\udeb0'],
  'at': ['\ud81a\ude74\ud81a\udeb0'],
  'vt': ['\ud81a\ude78\ud81a\udeb0'],
  'et': ['\ud81a\ude7c\ud81a\udeb0'],
  'it': ['\ud81a\ude80\ud81a\udeb0'],
  'ut': ['\ud81a\ude84\ud81a\udeb0'],
  'awt': ['\ud81a\ude88\ud81a\udeb0'],
  'uit': ['\ud81a\ude8c\ud81a\udeb0'],
  'uet': ['\ud81a\ude95\ud81a\udeb0'],
  'uiut': ['\ud81a\udeb0\ud81a\udeb0'],
  'oz': ['\ud81a\ude70'],
  'oc': ['\ud81a\ude71'],
  'ox': ['\ud81a\ude73'],
  'az': ['\ud81a\ude74'],
  'ac': ['\ud81a\ude75'],
  'ax': ['\ud81a\ude77'],
  'vz': ['\ud81a\ude7a'],
  'vc': ['\ud81a\ude79'],
  'vx': ['\ud81a\ude7b'],
  'ez': ['\ud81a\ude7c'],
  'ec': ['\ud81a\ude7d'],
  'ex': ['\ud81a\ude7f'],
  'iz': ['\ud81a\ude80'],
  'ic': ['\ud81a\ude81'],
  'ix': ['\ud81a\ude83'],
  'uz': ['\ud81a\ude84'],
  'uc': ['\ud81a\ude85'],
  'ux': ['\ud81a\ude87'],
  'awz': ['\ud81a\ude88'],
  'awc': ['\ud81a\ude89'],
  'awx': ['\ud81a\ude8b'],
  'uiz': ['\ud81a\ude8c'],
  'uic': ['\ud81a\ude8d'],
  'uix': ['\ud81a\ude8f'],
  'uez': ['\ud81a\ude95'],
  'uec': ['\ud81a\ude94'],
  'uex': ['\ud81a\ude97'],
  'uiuz': ['\ud81a\ude98'],
  'uiuc': ['\ud81a\ude99'],
  'uiux': ['\ud81a\ude9b'],
  'htt': ['\ud81a\udeb8'],
  'th': ['\ud81a\udeb9'],
  'ht': ['\ud81a\udeaf'],
  'ch': ['\ud81a\udebd'],
  'kh': ['\ud81a\udea1'],
  'ng': ['\ud81a\udea3'],
  'ny': ['\ud81a\udea8'],
  'ph': ['\ud81a\udea9'],
  'nh': ['\ud81a\udeb3'],
  'sh': ['\ud81a\udeb4'],
  'ts': ['\ud81a\udeb6'],
  'gh': ['\ud81a\udeb7'],
  'f': ['\ud81a\udebb'],
  'k': ['\ud81a\udea0'],
  'g': ['\ud81a\udea2'],
  's': ['\ud81a\udea4'],
  'y': ['\ud81a\udea5'],
  'w': ['\ud81a\udea6'],
  'p': ['\ud81a\udea7'],
  'b': ['\ud81a\udeaa'],
  'm': ['\ud81a\udeab'],
  'n': ['\ud81a\udeac'],
  'h': ['\ud81a\udead'],
  'l': ['\ud81a\udeae'],
  't': ['\ud81a\udeb0'],
  'd': ['\ud81a\udeb1'],
  'r': ['\ud81a\udeb2'],
  'j': ['\ud81a\udea5'],
  'v': ['\ud81a\ude7a'],
  '\u000a': ['\u000a'],
};

var gamwin_latin_chars =
    "mnvungz|mznvungz|vungz|vungc|vungx|vuk|ovyz|ovyc|ovyx|" +
    "oamz|oamc|oamx|omz|omc|omx|ovnz|ovnc|ovnx|ovlz|ovlc|ovlx|" +
    "ovmz|ovmc|ovmx|ovrz|ovrc|ovrx|ovp|ovt|" +
    "mnaungz|mznaungz|mrvkueq|aungz|aungc|aungx|auk|uiyq|vyq|oq|aq|" +
    "vq|eq|iq|uq|awq|uiq|ueq|uiuq|oayz|oayc|oayx|ayz|ayc|ayx|vyz|vyc|" +
    "vyx|uyz|uyc|uyx|uiyz|uiyc|uiyx|ueyz|ueyc|ueyx|ongz|ongc|ongx|" +
    "angz|angc|angx|vngz|vngc|vngx|engz|engc|engx|ingz|ingc|ingx|" +
    "ungz|ungc|ungx|awngz|awngc|awngx|uingz|uingc|uingx|uengz|" +
    "uengc|uengx|uiungz|uiungc|uiungx|oamz|oamc|oamx|amz|amc|" +
    "amx|vmz|vmc|vmx|emz|emc|emx|imz|imc|imx|umz|umc|umx|awmz|" +
    "awmc|awmx|uimz|uimc|uimx|uemz|uemc|uemx|uiumz|uiumc|uiumx|" +
    "oanz|oanc|oanx|anz|anc|anx|vnz|vnc|vnx|enz|enc|enx|inz|inc|" +
    "inx|unz|unc|unx|awnz|awnc|awnx|uinz|uinc|uinx|uenz|uenc|" +
    "uenx|uiunz|uiunc|uiunx|oalz|oalc|oalx|alz|alc|alx|vlz|vl" +
    "c|vlx|elz|elc|elx|ilz|ilc|ilx|ulz|ulc|ulx|awlz|awlc|awlx|" +
    "uilz|uilc|uilx|uelz|uelc|uelx|uiulz|uiulc|uiulx|oarz|" +
    "oarc|oarx|arz|arc|arx|vrz|vrc|vrx|erz|erc|erx|irz|irc|irx|" +
    "urz|urc|urx|awrz|awrc|awrx|uirz|uirc|uirx|uerz|uerc|uerx|" +
//    "uiurz|uiurc|uiurx|ok|ak|vk|ek|ik|uk|awk|uik|uek|uiuk|oap|" +
    "uiurz|uiurc|uiurx|ok|ak|ek|ik|uk|awk|uik|uek|uiuk|oap|" +
    "ph|op|ap|vk|ep|ip|up|awp|uip|uep|uiup|oat|at|vt|et|it|ut|awt|" +
    "uit|uet|uiut|oz|oc|ox|az|ac|ax|vz|vc|vx|ez|ec|ex|iz|ic|ix|" +
    "uz|uc|ux|awz|awc|awx|uiz|uic|uix|uez|uec|uex|uiuz|uiuc|" +
    "uiux|htt|th|ht|ch|kh|ng|ny|nh|sh|ts|gh|f|k|g|s|y|w|p|" +
    "b|m|n|h|l|t|d|r|j|v|\u0020|,|\.|\u000a";

function preParseLatin(instring) {
  //  var regex1 = new RegExp(tangsa_latin_chars, "gi");
  var regex1 = new RegExp(gamwin_latin_chars, "gi");
  var outList = instring.match(regex1);
  return outList;
}

function convertEncodingToUnicode(inbox, outbox, encodingIndex) {
  var inarea = document.getElementById(inbox);
  var outarea = document.getElementById(outbox);

  // First, replace all single characters with their Unicode equivalents.
  var intext = inarea.value;
  var outtext = "";
  var out;
  var parsedText = preParseLatin(intext.toLowerCase());
  for (var index = 0; index < parsedText.length; index ++) {
    var c = parsedText[index];
    out = c;
    if (c in private_use_map_combined) {
      var result = private_use_map_combined[c][encodingIndex];
      if (result) {
        out = result;
      }
    }
    outtext += out;
  }

  var newText = outtext;
  // Insert more complex replacements here.

  //  ePattern = /([\u1031\u103c]\ufe00?)([\u1000-\u1029\u1075-\u1081\uaa60-\uaa76]\uf300?)/gi;
  //  eReplace = "$2$1";
  //  newText = outtext.replace(ePattern, eReplace);


  // Consider doubled combiners, e.g., 103a twice.
  if (outarea) {
    outarea.innerHTML = outarea.value = newText;
  }
  return newText;
}
