runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /testdata/.*
  static_dir: testdata
  application_readable: true

- url: /fonts
  static_dir: fonts

- url: /collation
  static_dir: collation

- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /layouts
  static_dir: layouts
  
- url: /images
  static_dir: images

- url: /download
  static_dir: download

- url: /resources
  static_dir: resources

- url: /help
  static_dir: help

- url: /base/.*
  script: base.app

- url: /demo_ccp/*
  script: chakma.app

- url: /aio/.*
  script: aiton.app

- url: /bax/.*
  script: bamum.app

- url: /bete/.*
  script: bete.app

- url: /bla/.*
  script: blackfoot.app

- url: /bn/.*
  script: bangali.app

- url: /bod/.*
  script: tibetan.app

- url: /bsq/.*
  script: bassa.app

- url: /bts/.*
  script: bataksimalungun.app

- url: /cja/.*
  script: cham.app

- url: /ccp/.*
  script: chakma.app

- url: /cho/.*
  script: choctaw.app

- url: /cr/.*
  script: cree.app

- url: /chr/.*
  script: cherokee.app

- url: /del/.*
  script: lenape.app

- url: /demo_win/.*
  script: hochunk.app

- url: /emoji/.*
  script: emoji.app

- url: /en_anangu/.*
  script: anangu.app

- url: /gon/.*
  script: gondi.app

- url: /esg/.*
  script: gondi.app

- url: /gno/.*
  script: gondi.app

- url: /wsg/.*
  script: gondi.app

- url: /hoc/.*
  script: ho.app

- url: /ijn/.*
  script: kalabari.app

- url: /ig/.*
  script: nsibidi.app

- url: /kgp/.*
  script: kaingang.app

- url: /kht/.*
  script: khamti.app

- url: /kpe/.*
  script: kpelle.app

- url: /lom/.*
  script: loma.app

- url: /lut/.*
  script: lushootseed.app

- url: /mni/.*
  script: meitei.app

- url: /myh/.*
  script: makah.app

- url: /omq/.*
  script: omq.app

- url: /ovd/.*
  script: elfdalian.app

- url: /tavt/.*
  script: taivietscript.app

- url: /win/.*
  script: hochunk.app

- url: /wo/.*
  script: wolof.app

- url: /aho/.*
  script: ahom.app

- url: /hnj/.*
  script: nyiakeng_hmong.app

- url: /ksw/.*
  script: karen.app

- url: /kyu/.*
  script: kayah.app

- url: /lampung/.*
  script: lampung.app

- url: /lep/.*
  script: lepcha.app

- url: /lzz/.*
  script: laz.app

- url: /men/.*
  script: mendekikakui.app

- url: /mez/.*
  script: menoninee.app

- url: /mn/.*
  script: mongolian.app

- url: /mor/.*
  script: moro.app

- url: /pcm/.*
  script: nigerianpidgin.app

- url: /my/.*
  script: burmese.app

- url: /nyiakeng/.*
  script: nyiakeng_hmong.app

- url: /nnp/.*
  script: wancho.app

- url: /nv/.*
  script: navajo.app

- url: /oj/.*
  script: ojibwe.app

- url: /one/.*
  script: oneida.app

- url: /phk/.*
  script: phake.app

- url: /rhg/.*
  script: rohingya.app

- url: /rw/.*
  script: kinyarwanda.app

- url: /shn/.*
  script: shan.app

- url: /srb/.*
  script: sora.app

- url: /sat/.*
  script: santali.app

- url: /sxx/.*
  script: silibario.app

- url: /syl/.*
  script: sylheti.app

- url: /tcy/.*
  script: tulu.app

- url: /tai/.*
  script: ahom.app

- url: /tmh/.*
  script: tamashek.app

- url: /nst/.*
  script: tangsa.app

- url: /suz/.*
  script: sunuwar.app

- url: /ta/.*
  script: tamil.app

- url: /to/.*
  script: tongan.app

- url: /xmf/.*
  script: mingrelian.app

- url: /unr/.*
  script: mundari.app

- url: /yo/.*
  script: yoruba.app

- url: /zag/.*
  script: zaghawa.app

- url: /kb/.*
  script: keyboard.app

- url: /games/.*
  script: games.app

- url: /test/.*
  script: test.app

- url: /feedback/.*
  script: feedback.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: django
  version: latest







