runtime: python312

instance_class: F2

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /testdata/.*
  static_dir: testdata

- url: /fonts
  static_dir: fonts

- url: /collation
  static_dir: collation

- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /layouts
  static_dir: layouts
  
- url: /images
  static_dir: images

- url: /download
  static_dir: download

- url: /resources
  static_dir: resources
 
- url: /help
  static_dir: help

- url: .*
  script: auto
