#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Raw English and Assamese data (encoded as Assamese New font)
en_as_raw_data = [
    ["type of rice", "¡Òx¡ ¢ÒF", "àËµÒ", "কাপক খাও", "হেতা"],
    ["to keep one portion", "¡Ò¡", "ÀÒ¤ ¡ÃÒ", "কাক", "ভাগ কৰা"],
    ["to spread (over) water", "¡Ò§", "¤åÅ àÂÒÇÒ", "কাঙ", "গলি যোৱা"],
    ["to be stuck in the throat", "¡Ò§", "å·å¹Å ÅÒå¤ ¸ÃÒ", "কাঙ", "দিনিল লাগি ধৰা"],
    ["a bow", "¡Ò§", "¡ÒÄ ¸¹Ø", "কাঙ", "কাড় ধনু"],
    ["chin", "¡Ò§", "¶ØíµÔÃ", "কাঙ", "থুঁতৰি"],
    ["middle", "¡Ò§", "ÁÒªµ", "কাঙ", "মাজত"],
    ["night", "¡Ò§ ¢ÒÁ", "ÃÒåµ", "কাঙ খাম", "ৰাতি"],
    ["paddy field", "¡Ò§ ¹Ò", "»¶ÒÃ", "কাঙ না", "পথাৰ"],
    ["in the middle of the water", "¡Ò§ ¹ÒÁ", "»Ò¹ÕÃ ÁÒªµ", "কাঙ নাম", "পানীৰ মাজত"],
    ["morning", "¡Ò§ ¹Òw", "ÃÒåµ »ØÇÒ", "কাঙ নাঔ", "ৰাতি পুৱা"],
    ["daytime", "¡Ò§ ÇÒ¹", "å·¹", "কাঙ ৱান", "দিন"],
    ["deer", "¡Ò§", "ËÃ »ËØ", "কাঙ", "হৰ পহু"],
    ["fishbone", "¡Ò§", "å¼í¨Ò", "কাঙ", "ফিঁচা"],
    ["wide", "¡Ò§", "¾ËÅ", "কাঙ", "বহল"],
    ["paddy field is big", "¡Ò§ ¡Ò§ ¡Ø§ ¡Ø§", "ÍÒËÅ ¾ËÅ", "কাঙ কাঙ কুঙ কুঙ", "আহল বহল"],
    ["a type of frog that lives inside the house", "¡Ò§ ¢Ò", "àÀí¡ØÅÕ", "কাঙ খা", "ভেঁকুলী"],
    ["cold", "¡Òµ", "°Ò³ì±Ò", "কাত", "ঠাণ্‍ডা"],
    ["to bite (used for small animals like mice, or insects)", "¡Òµ", "à¡Ò¯Ò", "কাত", "কোটা"],
    ["to be strong and active", "¡Òµ", "à¨Ò¡Ò", "কাত", "চোকা"],
    ["congratulations", "¡Òµ ¡Òµ", "à¨¡Ò à¨¡Ò", "কাত কাত", "চেকা চেকা"],
    ["to shoot or fire at an animal and miss it by a little", "ÍÅ» ¾Òå¨àÅ", "অলপ বাচিলে"],
    ["market", "¡Òµ", "¾ªÒÃ", "কাত", "বজাৰ"],
    ["to starve, to fast", "¡Ò¹ ¢ÒF", "ÀÒµ ¢Ò¾áÅ à¹Òà¢ÒÇÒ", "কান খাও", "ভাত খাবলৈ নোখোৱা"],
    ["to fight, where one person fights and the other does not fight", "¡Ò¹ ¡¹Ò ¡Ø¡ ¡Ø¡", "¾¤ÃÒ ¾¤ÃÕ", "কান কনা কুক কুক", "বগৰা বগৰী"],
    ["stripe", "¡Ò¹", "ÍÒ¨ ¯¹Ò", "কান", "আচ টনা"],
    ["to crawl", "¡Ò¹", "¾¤Òb ¢ØÃÒ", "কান", "বগাই খুৰা"],
    ["a kind of tree, whose wood was originally used for making pencils", "¡Ò¹ ¡ÒÁ", "gå¾¸ ¡ÅÁ ¾Ò ¤©", "কান কাম", "এবিধ কলম বা গছ"],
    ["each other, reciprocality", "¡Ò¹", "", "কান", ""],
    ["to join", "¡Ò»", "àªÒÃÒ Åà¤ÒÇÒ", "কাপ", "জোৰা লগোৱা"],
    ["join by join", "¡Ò» ¡Ò» à¨Ò à¨Ò", "àªÒÃÒ Åà¤ÒÇÒµ à¾å©", "কাপ কাপ চো চো", "জোৰা লগোৱাত বেছি"],
    ["to be tight", "¡Ò»", "¯Ò¹ àËÒÇÒ", "কাপ", "টান হোৱা"],
    ["outer part of plants", "¡Ò»", "¾Ò¡åÅ", "কাপ", "বাকলি"],
    ["the outer part of the banana plant", "¡Ò» ¡Øb", "¡ÅÃ ¾Ò¡åÅ", "কাপ কুই", "কলৰ বাকলি"],
    ["the outer part of bamboo", "¡Ò» ÁÒb ©Ò§", "¾ÒËÃ ¼ÅÒ", "কাপ মাই ছাঙ", "বাহৰ ফলা"],
    ["to make a presentation with two hands", "¡Ò»", "6¨Ãì¤", "কাপ", "উচৰ্‍গ"],
    ["to bite", "¡Ò»", "¡ÒàÁÒÃÒ", "কাপ", "কামোৰা"],
    ["before", "¡Ò ¹Ò", "ÍÒ¤µ", "কা না", "আগত"],
    ["behind", "¡Ò ÅÒ§", "å»©¼ÒàÅ", "কা লাঙ", "পিছফালে"],
    ["stuttering, stammering", "¡Ò", "à¢Ò¹Ò", "কা", "খোনা"],
    ["stuttering, stammering", "¡Ò ¡Ò ÇÒ ÇÒ", "à¢Ò¹Ò", "কা কা ৱা ৱা", "খোনা"],
    ["wrong, error", "¡Ò", "ÀØÅ", "কা", "ভুল"],
    ["what?", "¡Ò ©Ò§", "å¡", "কা ছাঙ", "কি"],
    ["to go", "¡Ò", "àÂÒÇÒ", "কা", "যোৱা"],
    ["crow", "¡Ò", "¡Ò6ÃÕ", "কা", "কাউৰী"],
    ["to dance", "¡Ò", "¹Ò¨", "কা", "নাচ"],
    ["value", "¡Ò", "·ÒÁ", "কা", "দাম"],
    ["to grind into powder", "å¡¡", "å»¨Ò ¤ØåÄ ¡ÃÒ", "কিক", "পিচা গ‍ুড়ি কৰা"],
    ["to make medicinal powder", "å¡¡ ÂÒ", "·Ã¾ ¤ØåÄ ¡ÃÒ", "কিক যা", "দৰব গ‍ুড়ি কৰা"],
    ["single person", "å¡¡", "å¾àÂÒÃ", "কিক", "বিযোৰ"],
    ["to like", "å¡¡", "»©¹ì· ¡ÃÒ", "কিক", "পছন্দ কৰা"],
    ["to try", "à¡¡", "ÁØ¢Êì¶ ¡ÃÒ", "কেক", "মুখস্‍থ কৰা"],
    ["small branch", "å¡§", "ÊÃØ ±ÒÅ", "কিঙ", "সৰু ডাল"],
    ["a small branch", "å¡§ ¢Ò", "±ÒÅ »Òµ", "কিঙ খা", "ডাল পাত"],
    ["the last strand of the rice plant which is cut off during harvesting, with the rice grain still attached to it", "å¡§", "¸Ò¹Ã à°Ò¡Ò", "কিঙ", "ধানৰ ঠোকা"],
    ["to roll", "å¡§", "¾Ò¤åÃ àÂÒÇÒ", "কিঙ", "বাগৰি যোৱা"],
    ["green", "å¡§", "àÊ6ªÕ¿Ò", "কিঙ", "সেউজীয়া"],
    ["iron tripod used for cooking rice", "å¡§", "ªÒíåµ", "কিঙ", "জাঁতি"],
    ["to cry with a full sound", "à¡§", "à¨FÃÒ", "কেঙ", "চেওৰা"],
    ["dwarfed", "à¡§", "¾Òåµ¿Ò", "কেঙ", "বাতিয়া"],
    ["to clean one's self (after evacuating the bowels)", "à¡§", "¨¼Ò ¡ÃÒ", "কেঙ", "চফা কৰা"],
    ["to clean one's self (after evacuating the bowels)", "à¡§ ¢Õ", "»¡Ã ¨¼Ò ¡ÃÒ", "কেঙ খী", "পকৰ চফা কৰা"],
    ["heart, core", "à¡¹", "¡°Ã ËÒÃå·", "কেন", "কঠৰ হাৰদি"],
    ["to cut around a tree, to ringbark a tree", "à¡¹", "¨ÒbF ¼ÒàÅ ¡¯Ò ¤©", "কেন", "চাইও ফালে কটা গছ"],
    ["earring", "à¡¹ àËÒ", "¡Ò³Ã ¼ØÅÕ", "কেন হো", "কাণৰ ফুলী"],
    ["in deep water", "à¡¹ à¡ä¡", "ÍÒ¸Ò ÁÃÒ", "কেন কৌক", "আধা মৰা"],
    ["to touch", "å¡µ", "à¨ÒÇÒ", "কিত", "চোৱা"],
    ["fish scale", "å¡µ", "Á©Ã ¾Ò¡åÅ", "কিত", "মছৰ বাকলি"],
    ["fish scale", "å¡µ »Ò", "Á©Ã ¾Ò¡åÅ", "কিত পা", "মছৰ বাকলি"],
    ["to go around (of an animal)", "à¡µ", "ÍÒ¤ àÀ¯Ò å·¿Ò", "কেত", "আগ ভেটা দিয়া"],
    ["to promise", "å¡¹", "¡¨Á à¢ÒÇÒ", "কিন", "কচম খোৱা"],
    ["to eat", "å¡¹", "à¢ÒÇÒ", "কিন", "খোৱা"],
    ["fish scale", "å¡µ", "ÁÒ©Ã ¾Ò¡åÅ, ¤©Ã ¾Ò¡åÅ", "কিত", "মাছৰ বাকলি, গছৰ বাকলি"],
    ["to take, to get", "å¡»", "àµÒÅÒ", "কিপ", "তোলা"],
    ["to take something and keep it", "å¡» ÇÒb", "àµÒåÅ ¶", "কিপ ৱাই", "তোলি থ"],
    ["to make a design of a flower on cloth, esp. on gamucha", "å¡» ÅÒb", "¤ÒàÁÒ¨Òµ ¼ØÅ µØÅÒ", "কিপ লাই", "গামোচাত ফুল তুলা"],
    ["husks", "à¡»", "à¨Òà¡ÒÃÒ", "কেপ", "চোকোৰা"],
    ["suddenly", "à¡» ¡Òb", "µb ©Ò¹µ", "কেপ কাই", "তই ছানত"],
    ["just now", "à¡» ¡Òb àÅä§", "àÊÒÁ ¡ÒàÅ µØÅ", "কেপ কাই লৌঙ", "সোম কালে তুল"],
    ["a kind of fever", "à¡»", "¤Ò å¾¢Ã à¾ÁÒÃ", "কেপ", "গা বিখৰ বেমাৰ"],
    ["to be crowded with so many people that one cannot walk through the middle and has to go by the side", "å¡Á àÁä¹ åËÁ àÁä¹", "å¡¹ÒÃµ", "কিম মৌন হিম মৌন", "কিনাৰত"],
    ["to aim", "à¡Á", "ÅVp ¡ÃÒ", "কেম", "ল্য কৰা"],
    ["to be angry, cross, irascible", "à¡Á", "¢§ì¤ÒÅ", "কেম", "খঙ্‍গাল"],
    ["cheek", "à¡Á", "¤ÒÅ", "কেম", "গাল"],
    ["a kind of bird", "¡Ø¡", "gå¾¸ ¨ÃÒb", "কুক", "এবিধ চৰাই"],
    ["a kind of tree", "¡Ø¡ à¡Ò", "gå¾¸ ¤©", "কুক কো", "এবিধ গছ"],
    ["table", "¡Ø§", "àÁª", "কুঙ", "মেজ"],
    ["prawn, shrimp", "¡Ø§", "åÁ©Ò ÁÒ©", "কুঙ", "মিছা মাছ"],
    ["spider", "¡Ø§ ¡Ò6", "Á¡ÃÒ", "কুঙ কাউ", "মকৰা"],
    ["a bow", "¡Ø§", "¸¹Ø", "কুঙ", "ধনু"],
    ["a type of bow", "¡Ø§ ¡§", "¸¹Ø ¡ÒÄ", "কুঙ কঙ", "ধনু কাড়"],
    ["cotton", "¡Øb", "µØÅÒ", "কুই", "তুলা"],
    ["to lever up with a stick", "¡Øb", "ÅØå¯¿Òb å·¿Ò", "কুই", "লুটিয়াই দিয়া"],
    ["banana", "¡Øb", "¡Å", "কুই", "কল"],
    ["convex, crooked", "¡Øµ", "à¾í¡Ò", "কুত", "বেঁকা"],
    ["zigzag", "¡Øµ ¡Øµ §¡ §¡", "àµÃÒ à¾í¡Ò", "কুত কুত ঙক ঙক", "তেৰা বেঁকা"],
    ["to uproot", "¡Ø¹", "6ÀÅÒ", "কুন", "উভলা"],
    ["person, man", "¡Ø¹", "ÁÒ¹ØË", "কুন", "মানুহ"],
    ["bottom", "¡Ø¹", "»¡íÃ", "কুন", "পকঁৰ"],
    ["to feel ache or tired,", "¡Ø¹", "å¾Ë ¾Ò ¡ìÅÒå¹ìµ Í¹ØÀÇ ¡ÃÒ", "কুন", "বিহ বা ক্‍লানি্‍ত অনুভৱ কৰা"],
    ["a sunhat, used by farmers", "¡Ø»", "ªÒå»", "কুপ", "জাপি"],
    ["frog", "¡Ø»", "কুপ"],
    ["eclipse of the moon", "¡Ø» å¡¹ à¹ä¹", "¨¹ì·iË³", "কুপ কিন নৌন", "চন্দiহণ"],
    ["eclipse of the sun", "¡Ø» å¡¹ ÇÒ¹", "কুপ কিন ৱান"],
    ["with", "¡Ø»", "áÊàµ", "কুপ", "সৈতে"],
    ["a pair", "¡Ø»", "gàÂÒÃ", "কুপ", "এযোৰ"],
    ["fear", "à¡Ò", "À¿", "কো", "ভয়"],
    ["bed", "à¡Ò", "»ÒàÅ×", "কো", "পালেং"],
    ["to bring clothes in after drying", "à¡Ò", "¡Ò»Ã 6à°ÒÇÒ", "কো", "কাপৰ উঠোৱা"],
    ["every", "à¡Ò", "»iàµp¡", "কো", "পiতে্যক"],
    ["always", "à¡Ò àÁä", "Ê·Ò¿", "কো মৌ", "সদায়"],
    ["old", "à¡", "»ØÃ°", "কে", "পুৰঠ"],
    ["to be unusable due to age, said of food that can no longer be eaten because it is too old", "à¡ à¡ä§", "»ØÃÒ »ØÃ°", "কে কৌঙ", "পুৰা পুৰঠ"],
    ["to unravel (thread), to untie", "à¡", "àÊÒÅÒ", "কে", "সোলা"],
    ["chicken, hen", "¡Òb", "¡Ø¡ØÃÒ", "কাই", "কুকুৰা"],
    ["far", "¡Òb", "¡ÙÃ", "কাই", "কূৰ"],
    ["quick", "¡Òb", "¢Ã à¢·Ò", "কাই", "খৰ খেদা"],
    ["to place something between two points", "¡Òb", "»ÃÒ", "কাই", "পৰা"],
    ["to be irritated", "¡Òb", "¢ªØÇÒ", "কাই", "খজুৱা"],
    ["very irritated", "¡Òb ¡Òb ÃÒÁ ÃÒÁ", "¢ªØÇÒ", "কাই কাই ৰাম ৰাম", "খজুৱা"],
    ["to push something with an implement", "¡Òb", "¯Òå¹ Í¹Ò ¯Ò¹", "কাই", "টানি অনা টান"],
    ["many many (used of ants)", "¡ÒÁ", "¾Ëµ à¾å© ¤Ø¯ à¢ÒÇÒ", "কাম", "বহত বেছি গ‍ুট খোৱা"],
    ["not proper; do not", "¡ÒÁ", "¹Ò»Ò¿", "কাম", "নাপায়"],
    ["to support", "¡ÒÁ", "à²Ò¡Ò å·¿Ò", "কাম", "ঢোকা দিয়া"],
    ["fate, luck", "¡ÒÁ", "ÀÒ¤p", "কাম", "ভাগ্য"],
    ["to join, to make a raft or a boat", "¡ÒÁ", "àÂÒÃÒ å·¿Ò", "কাম", "যোৰা দিয়া"],
    ["to gather together, together", "¡ØÁ", "à¡ÒÃÒ", "কুম", "কোৰা"],
    ["to make a heap", "¡ØÁ", "¸Òå¡ å·¿Ò", "কুম", "ধাকি দিয়া"],
    ["to bow the head", "¡ØÁ", "à¡ÒÂÒ àËÒÇÒ", "কুম", "কোযা হোৱা"],
    ["to use the voice gently", "¡ØÁ ¡Á ÅÁ ¢ÒÁ", "¹Á ÀÒà¾ ¡¶Ò à¡ÒÇÒ", "কুম কম লম খাম", "নম ভাবে কথা কোৱা"],
    ["to bend or hang down (of trees), to droop", "¡Á", "ËÒåÅ ¶¡Ò", "কম", "হালি থকা"],
    ["to try", "à¡ä¡", "à¨Éì¯Ò ¡ÃÒ", "কৌক", "চেষ্টা কৰা"],
    ["incomplete, unfinished", "à¡ä¡ à¡ä¡ àÅä¡ àÅä¡", "ÍÒ¸ÃØÇÒ", "কৌক কৌক লৌক লৌক", "আধৰুৱা"],
    ["a person who does not work very well", "à¡ä¡ àÅä¡ »Ò à¡ä¡ àÅä¡", "¼ÒÅ¯Ø", "কৌক লৌক পা কৌক লৌক", "ফালটু"],
    ["to stand with the bottom pointing back", "à¡ä§", "å»å° å·¿Ò", "কৌঙ", "পিঠি দিয়া"],
    ["same", "à¡ä§", "åÁÅÒ", "কৌঙ", "মিলা"],
    ["to remain", "à¡äµ", "¶Òå¡ àÂÒÇÒ", "কৌত", "থাকি যোৱা"],
    ["to cut", "à¡äµ", "¡Ò¯ ¡¯Ò", "কৌত", "কাট কটা"],
    ["to be half boiled", "à¡äµ ¡Òµ", "ÍÒ¸Ò åÊªÒ", "কৌত কাত", "আধা সিজা"],
    ["the sound of grinding teeth", "à¡äµ å»6", "·íÒµ ¡Ã¨Ò", "কৌত পিউ", "দাঁত কৰচা"],
    ["to push the ground with the heel of the foot of with the hand", "à¡ä¹", "¾ÒàÃ ¾ÒàÃ ¡©¡Ò", "কৌন", "বাৰে বাৰে কছকা"],
    ["a crowd", "à¡ä¹", "¾ËØµ", "কৌন", "বহুত"],
    ["now, just at this moment, as soon as", "à¡ä» àÅä§", "gåµ¿Ò", "কৌপ লৌঙ", "এতিয়া"],
    ["tight", "à¡äÁ", "¯Ò¹", "কৌম", "টান"],
    ["very tight", "à¡äÁ à¡äÁ", "¯Ò¹á¡", "কৌম কৌম", "টানকৈ"],
    ["salt", "à¡ä", "å¹Á¢", "কৌ", "নিমখ"],
    ["to boil oil", "å¡6", "àµÅ ¾à¤ÒÇÒ", "কিউ", "তেল বগোৱা"],
    ["a bundle, a heap", "å¡6", "ÃÒåÈ", "কিউ", "ৰাশি"],
    ["a bundle of silk", "å¡6 ÁÒb", "ÈØµÒÃ ¾Ò¹ì·Å", "কিউ মাই", "শুতাৰ বান্দল"],
    ["something which is narrow in the middle and thick at both ends, concave", "å¡6 ÃÒ§ åÃµ", "å¨Ò", "কিউ ৰাঙ ৰিত", "চিা"],
    ["to be old", "¡ÒF", "»ØÃ³Ò", "কাও", "পুৰণা"],
    ["I, me", "¡ÒF", "Áb", "কাও", "মই"],
    ["nine", "¡ÒF", "¹", "কাও", "ন"],
    ["owl", "¡ÒF", "à¼í¨Ò", "কাও", "ফেঁচা"],
    ["to ask for help from a supernatural power", "¡ÒF", "ÁÃ³ ¡ÇÒ", "কাও", "মৰণ কৱা"],
    ["a spider", "¡ÒF", "Á¡ÃÒ", "কাও", "মকৰা"],
    ["to be nearly blind, the eyes not seeing well", "¡ÒF", "ÀÒÅá¡ à¹à·¢Ò", "কাও", "ভালকৈ নেদেখা"],
    ["calf (of the leg)", "¡ÒF", "¡ÅÒ¼ØÅ", "কাও", "কলাফুল"],
    ["cup", "¡¡", "å¤ÅÒ¨", "কক", "গিলাচ"],
    ["a glass", "¡¡ ¼Ò¹", "å¨¨Ò å¤ÅÒ¨", "কক ফান", "চিচা গিলাচ"],
    ["to bend, to curve", "¡§", "à¾¡Ò", "কঙ", "বেকা"],
    ["a drum", "¡§", "à²ÒÅ", "কঙ", "ঢোল"],
    ["a type of large drum", "¡§ »Òµ", "±Ò§Ã à²ÒÅ", "কঙ পাত", "ডাঙৰ ঢোল"],
    ["to put, to place", "¡§", "à¶ÒÇÒ", "কঙ", "থোৱা"],
    ["poison", "¡§", "å¾Ë", "কঙ", "বিহ"],
    ["to embrace", "¡µ", "ÊÒ¾å¯ ¸ÃÒ", "কত", "সাবটি ধৰা"],
    ["to leave, to abandon", "¡µ", "gåÃ à¶ÒÇÒ", "কত", "এৰি থোৱা"],
    ["to scoop with two hands", "¡»", "·ØËÒµ µØåÅ àÅÒÇÒ", "কপ", "দুহাত তুলি লোৱা"],
    ["to hold, to cling", "¡»", "Å¤µ ¾Òå¹ì· àÅÒÇÒ", "কপ", "লগত বানি্দ লোৱা"],
    ["to bind a medicinal poltice", "¡» ÂÒ", "·Ã¾ ¾¹ì¸Ò", "কপ যা", "দৰব বন্ধা"],
    ["therefore", "¡» à»ä", "àÊb ¡ÒÃà³", "কপ পৌ", "সেই কাৰণে"],
    ["near", "¡Òw", "6¨Ã", "কাঔ", "উচৰ"],
    ["swollen", "¡Òw", "6¢ËÒ", "কাঔ", "উখহা"],
    ["alone", "¡b", "Í¡àÅ", "কই", "অকলে"],
    ["youngest son, youngest child", "¡b", "àÈÉÃ ÅAÃÒ", "কই", "শেষৰ লaৰা"],
    ["to be expert, to be cunning, to be quick (at doing somethin)", "¡pÒ§", "»Òá¡µ", "ক্যাঙ", "পাকৈত"],
    ["kyaa²", "a", "¡pÒ", "ႃ", "ক্যা"],
    ["kyaa²", "a", "¡pÒ", "ႃ", "ক্যা"],
    ["kyɔŋ² / dʒɔŋ²", "agq", "¡p§, Â§", "ႃင︀်", "ক্যঙ, যঙ"],
    ["to wish", "¢Ò¡", "¡åÃ¾áÅ Á¹ àÂÒ¾Ò", "খাক", "কৰিবলৈ মন যোবা"],
    ["to make something sharp, like a needle", "¢Ò¡", "ÅÒå° àªÒ§Ò ¡åÃ (»Òåµ à¶ÒÇÒ ÍÃÉì°)", "খাক", "লাঠি জোঙা কৰি (পাতি থোৱা অৰষ্ঠ)"],
    ["to open up a small dam and allow water to flow out of it", "¢Ò¡", "»Ò¹ÕÃ àÃÒÅ à¢ÒåÅ å·¿Ò", "খাক", "পানীৰ ৰোল খোলি দিয়া"],
    ["to make a noisy, to be noisy, as dogs", "¢Ò§", "¤Ø ªÃÒ (à¡¡Òb Á¡Ò)", "খাঙ", "গ‍ু জৰা (কেকাই মকা)"],
    ["lac, a kind of gum", "¢Ò§", "ÅÒ", "খাঙ", "লা"],
    ["a spinning top", "¢Ò§", "ÅÒ¯ØÁ", "খাঙ", "লাটুম"],
    ["to throw a stick or other long piece of wood with the hand, to hurl", "¢Ò§", "¼ÃìÁØå¯FÇÒ", "খাঙ", "ফৰ্মুটিওৱা"],
    ["to stand near", "¢Ò§", "F¨Ãµ å¶¿ àËÒÇÒ", "খাঙ", "ওচৰত থিয় হোৱা"],
    ["to say the opposite of, to contradict", "¢Ò§ å¢§", "খাঙ খিঙ"],
    ["to adhere", "¢Ò§", "ÅÒå¤ ¸ÃÒ", "খাঙ", "লাগি ধৰা"],
    ["to stop and start while speaking", "¢Ò§ à¢äµ", "ÅÒå¤ ÅÒå¤ ¸ÃÒ", "খাঙ খৌত", "লাগি লাগি ধৰা"],
    ["to tear, to be torn", "¢Òµ", "¼¯Ò", "খাত", "ফটা"],
    ["to be sold out", "¢Òµ", "å¾¡ìµÕ àËÒÇÒ", "খাত", "বিক্‍তী হোৱা"],
    ["overgrown, given as \"so many trees in there\"", "¢Òµ", "àªà§ ªÒ¾àÃàÃ ÀÃÒ", "খাত", "জেঙে জাবৰেৰে ভৰা"],
    ["to crow, as a cock", "¢Ò¹", "ÁØå¤ ±Ò¡ å·¿Ò", "খান", "মুগি ডাক দিয়া"],
    ["price", "¢Ò¹", "·ÒÁ", "খান", "দাম"],
    ["to advise", "¢Ò¹", "»¨Ò", "খান", "পচা"],
    ["rust", "¢Ò¹", "ÁÒÁÃ", "খান", "মামৰ"],
    ["lazy", "¢Ò¹", "à¤¸Ò", "খান", "গেধা"],
    ["axe", "¢Ò¹", "¡Ø°ÒÃ", "খান", "কুঠাৰ"],
    ["to place things in a row", "¢Ò»", "ªÒå»à¶ÒÇÒ", "খাপ", "জাপিথোৱা"],
    ["slough; cast off snake skin", "¢Ò»", "¾Ò¡åÅ", "খাপ", "বাকলি"],
    ["thatch", "¢Ò", "à¢Ã", "খা", "খেৰ"],
    ["a servant, a slave", "¢Ò", "¨Ò¡Ã", "খা", "চাকৰ"],
    ["to kill", "¢Ò", "ÁÒÃÒ", "খা", "মাৰা"],
    ["branch of a tree", "¢Ò", "±ÒÅ", "খা", "ডাল"],
    ["a branch of a tree which is damaged, and will soon break off", "¢Ò", "»å¨ ¾áÅ àÅÒÇÒ ¡Ò¯", "খা", "পচি বলৈ লোৱা কাট"],
    ["right (side)", "¢Ò", "àÊÒí ËÒµ", "খা", "সোঁ হাত"],
    ["thigh", "¢Ò", "å¯¡Ò", "খা", "টিকা"],
    ["to search, to seek", "¢Ò", "å¾¨ÃÒ", "খা", "বিচৰা"],
    ["and", "¢Ò", "ÍÒÃØ", "খা", "আৰু"],
    ["guest", "à¢¡", "ÍÒÅËÕ", "খেক", "আলহী"],
    ["to cut (the skin)", "à¢¡", "¼ÅÒ (©ÒÅ)", "খেক", "ফলা (ছাল)"],
    ["a snag, \"in the river when a tree comes across and stops in the middle of the water\"", "à¢¡", "à¾ÒÇµÕ »Ò¹Õµ Åå¤ ¶¡Ò àª× ªÒ¾Ã", "খেক", "বোৱতী পানীত লগি থকা জেং জাবৰ"],
    ["to weigh", "å¢§", "àªÒ¢Ò", "খিঙ", "জোখা"],
    ["time", "å¢§", "ÊÁ¿", "খিঙ", "সময়"],
    ["body", "å¢§", "¤Ò", "খিঙ", "গা"],
    ["ginger", "å¢§", "ÍÒ·Ò", "খিঙ", "আদা"],
    ["a small type of ginger", "å¢§ à¡§", "ÊÃØ ÍÒ·Ò", "খিঙ কেঙ", "সৰু আদা"],
    ["rack or shelf", "å¢§", "¨Ò×", "খিঙ", "চাং"],
    ["to compete, to fight on equal terms", "å¢§", "ÊÁÒà¹ ÊÁÒà¹ ÂØíªÒ", "খিঙ", "সমানে সমানে যুঁজা"],
    ["so that", "àª¹", "àÊb ¤åµà¡", "জেন", "সেই গতিকে"],
    ["to hang", "à¢¹", "FÅÁÒb à¶ÒÇÒ", "খেন", "ওলমাই থোৱা"],
    ["to raise up one end", "å¢µ", "·Ò× à¢ÒÇÒ", "খিত", "দাং খোৱা"],
    ["frog", "å¢µ", "à¾×", "খিত", "বেং"],
    ["an enemy", "å¢¹", "ÈµìÃØ", "খিন", "শত্ৰু"],
    ["to fall without touching, that is when cutting something, it falls off", "å¢¹", "F¼åÃ àÂÒÇÒ", "খিন", "ওফৰি যোৱা"],
    ["to cut the hair", "à¢»", "¨ØåÅ ¡¯Ò", "খেপ", "চুলি কটা"],
    ["a needle", "å¢Á", "à¾åª", "খিম", "বেজি"],
    ["half burned, scorched", "à¢Á", "»ÙåÃ àÂÒÇÒ å¹å¨¹Ò", "খেম", "পূৰি যোৱা নিচিনা"],
    ["to ride", "¢Õ", "6°Ò", "খী", "উঠা"],
    ["faeces", "¢Õ", "Ë¤Ò", "খী", "হগা"],
    ["to be in sorrow, given as \"thinking, very very thinking.\"", "¢Õ", "à¾ªÒÃ", "খী", "বেজাৰ"],
    ["mortar, an instrument for pounding rice into flour", "¢Ø¡", "à²í¡Õ", "খুক", "ঢেঁকী"],
    ["a small table with short legs", "¢Ø§", "ËÃØ àÁª", "খুঙ", "হৰু মেজ"],
    ["to cut into a tree, to dig into a tree", "¢Ø§", "¤© ¢¹ìµÒ", "খুঙ", "গছ খন্‍তা"],
    ["part of a river, divided into separate sections", "¢Ø§", "±ÃÒ", "খুঙ", "ডৰা"],
    ["the world, a level of the world", "¢Ø§", "»ØåÃ (Êì¾¤I)", "খুঙ", "পুৰি (স্বগi)"],
    ["this world, the earth", "¢Ø§ ¡Ò§", "খুঙ কাঙ"],
    ["the world below, hell", "¢Ø§ µÒw", "খুঙ তাঔ"],
    ["the world above, heaven", "¢Ø§ à¹ä", "খুঙ নৌ"],
    ["brother in law, male in law", "¢Øb", "àª°ÒåÃ", "খুই", "জেঠাৰি"],
    ["brother in law", "¢Øb ¶ÒF", "àª°ÒåÃ", "খুই থাও", "জেঠাৰি"],
    ["to pick up with the fingers, to finger powder out of a container", "¢Øb", "ÍÒ§ØåÅàÃ 6åÅ±ÇÒ", "খুই", "আঙুলিৰে উলিডৱা"],
    ["turbid, mud mixed with water, turbid water", "¢Ø¹", "¤Øà¤ÒÅÒ", "খুন", "গ‍ুগোলা"],
    ["hair, body hair", "¢Ø¹", "à¹ÒÁ", "খুন", "নোম"],
    ["eyelash, given as eye-hair", "¢Ø¹ µÒ", "¨¡ØÃ à¹ÒÁ", "খুন তা", "চকুৰ নোম"],
    ["a prince", "¢Ø¹", "ÃªÒ", "খুন", "ৰজা"],
    ["Brahma", "¢Ø¹ ©Ò§", "¾iËìÁÒ", "খুন ছাঙ", "বiহ্মা"],
    ["to mix", "¢Ø¹", "ÅÃÒb å·¿Ò", "খুন", "লৰাই দিয়া"],
    ["pants", "¢Ø¹", "à»¹ì¯", "খুন", "পেন্ট"],
    ["road", "¢Ø¹ µÒ§", "ÃÒÊìµÒ", "খুন তাঙ", "ৰাস্‍তা"],
    ["itchy", "¢Ø»", "¢ªØÇÒ", "খুপ", "খজুৱা"],
    ["a bridge", "¢Ù", "·Å×", "খূ", "দলং"],
    ["to laugh", "¢Ù", "ËËíÒ", "খূ", "হহাঁ"],
    ["party, company", "¢Ù", "·Å", "খূ", "দল"],
    ["to rule", "¢Ù", "ÈÒÊ¹ ¡ÃÒ", "খূ", "শাসন কৰা"],
    ["to clear the jungle to make a paddy field", "¢Ù", "àÁÒ¡ØåÅ ¡ÃÒ", "খূ", "মোকুলি কৰা"],
    ["to fry without oil", "¢Ù", "ÈØ¡Ò¹ ÀªÒ", "খূ", "শুকান ভজা"],
    ["egg", "¢Òb", "¡³Õ", "খাই", "কণী"],
    ["fever, illness", "¢Òb", "à¾ÁÒÃ", "খাই", "বেমাৰ"],
    ["a headache", "¢Òb àËÒ", "ÁØÃÃ å¾É", "খাই হো", "মুৰৰ বিষ"],
    ["to be spoiled (given as\"to put to one side\")", "¢Òb", "¤Ø¨", "খাই", "গ‍ুচ"],
    ["to tell, to say", "¢Òb", "à¡ÒÇÒ", "খাই", "কোৱা"],
    ["to spit out of the mouth", "¢Òb", "ÁØ¢Ã »ÃÒ 6åÅ¿Òb å·¿Ò", "খাই", "মুখৰ পৰা উলিয়াই দিয়া"],
    ["a buffalo", "¢Òb", "ÁAË", "খাই", "মaহ"],
    ["to sell", "¢Òb", "à¾¨Ò", "খাই", "বেচা"],
    ["to turn", "¢Òb", "¦ØÃÒ", "খাই", "ঘুৰা"],
    ["the neck", "¡", "å±å§", "ক", "ডিঙি"],
    ["greedy", "¡", "¢Ò¾áÅ b¨ì©Ò ¡ÃÒ", "ক", "খাবলৈ ইচ্ছা কৰা"],
    ["a hoe", "¡", "à¡ÒÃ", "ক", "কোৰ"],
    ["separate, different", "¡", "à¾àÅ¤", "ক", "বেলেগ"],
    ["cannot cross to stop", "¢ÒÁ", "ÅÒå¤ ¸ÃÒ", "খাম", "লাগি ধৰা"],
    ["gold", "¢ÒÁ", "àÊÒ³", "খাম", "সোণ"],
    ["night", "¢ÒÁ", "ÃÒåµ", "খাম", "ৰাতি"],
    ["word", "¢ÒÁ", "¡¶Ò", "খাম", "কথা"],
    ["to cross over", "¢ÒÁ", "»ÒÃ àËÒÇÒ", "খাম", "পাৰ হোৱা"],
    ["a well, a fish tank", "¢ØÁ", "»Ø¢ØåÃ (¤Òµ)", "খুম", "পুখুৰি (গাত)"],
    ["bitter", "¢ØÁ", "åµµÒ", "খুম", "তিতা"],
    ["a sharp edge", "¢ØÁ", "¸ÒÃ", "খুম", "ধাৰ"],
    ["to tickle someone", "¢ØÁ", "å¡Å å¡ÅÒ", "খুম", "কিল কিলা"],
    ["to turn upside down", "¢ØÁ", "FàÅÒà¯ÒÇÒ", "খুম", "ওলোটোৱা"],
    ["a bamboo implement for catching fish", "à¢ä¡", "ªÒá¡", "খৌক", "জাকৈ"],
    ["thing", "à¢ä§", "¾ÊìµØ", "খৌঙ", "বস্‍তু"],
    ["equal", "à¢ä§", "ÊÁÒ¹", "খৌঙ", "সমান"],
    ["sieve", "à¢ä§", "¨ÒÅÒ", "খৌঙ", "চালা"],
    ["to go together, be together", "à¢äµ", "Å¤ à»ÒÇÒ", "খৌত", "লগ পোৱা"],
    ["to go up", "à¢ä¹", "6°Ò", "খৌন", "উঠা"],
    ["night, midnight", "à¢ä¹", "ÁÒª ÃÒåµ", "খৌন", "মাজ ৰাতি"],
    ["and", "à¢ä¹", "ÍÒÃØ", "খৌন", "আৰু"],
    ["span from the thumb to the little finger, a Tai measurement", "à¢ä»", "à¾à¤µ", "খৌপ", "বেগেত"],
    ["make a heap of branches", "à¢äÁ", "ªÒå» å·¿Ò", "খৌম", "জাপি দিয়া"],
    ["a beam, a rafter, used to describe the rafters on the shorter side of a house. For the longer side, use 'pj²'.", "à¢ä", "ÁØ·¨", "খৌ", "মুদচ"],
    ["proud", "à¢ä", "¤»", "খৌ", "গপ"],
    ["to creep up", "à¢ä", "¾¤Òb àÂÒÇÒ", "খৌ", "বগাই যোৱা"],
    ["a sickle", "å¢6", "¡Òíå¨", "খিউ", "কাঁচি"],
    ["a tooth", "å¢6", "·Òíµ", "খিউ", "দাঁত"],
    ["blue", "å¢6", "¹ÕÅÒ", "খিউ", "নীলা"],
    ["bad smelling", "à¢6", "¡ÃØ 6¯Ò", "খেউ", "কৰু উটা"],
    ["rice", "¢ÒF", "ÀÒµ", "খাও", "ভাত"],
    ["turmeric, yellow cumin", "¢ÒF åÁ¹", "ËÒÅå¸", "খাও মিন", "হালধি"],
    ["to enter", "¢ÒF", "àÊÒàÁÒÇÒ", "খাও", "সোমোৱা"],
    ["they", "¢ÒF", "àÊËíµ", "খাও", "সেহঁত"],
    ["horn", "¢ÒF", "åÈ×", "খাও", "শিং"],
    ["a part of the loom", "¢ÒF", "¾Ë àµÒÅÒ", "খাও", "বহ তোলা"],
    ["to not see well, to see only a little", "¢ÒF", "ÍÅ» ÍÅ» à·¢Ò", "খাও", "অলপ অলপ দেখা"],
    ["white", "¢ÒF", "¾¤Ò", "খাও", "বগা"],
    ["shed", "¢¡", "খক"],
    ["room", "¢¡", "à¡Ò°Ò", "খক", "কোঠা"],
    ["chicken coop", "¢¡ ¡Òb", "¤ÃÒÅ", "খক কাই", "গৰাল"],
    ["room by room, so many rooms", "¢¡ ¢¡ à¢¡ à¢¡", "¾ËØµ à¡Ò°Ò", "খক খক খেক খেক", "বহুত কোঠা"],
    ["door platfrorm, a piece of wood across the bottom of a door.", "¢¡ ¢ÒÁ", "·ìÇÒÃ ÁØ¢", "খক খাম", "দ্ৱাৰ মুখ"],
    ["cow shed", "¢¡ ÇÙ", "à¤ÒËÒåÅ", "খক ৱূ", "গোহালি"],
    ["small basket", "¢§", "»Òå¨", "খঙ", "পাচি"],
    ["to stumble", "¢§", "6ªØå¯ à¢ÒÇÒ", "খঙ", "উজুটি খোৱা"],
    ["thing", "¢§", "¾ÊìµØ", "খঙ", "বস্‍তু"],
    ["to bind with cloth, to tie a knot with cloth", "¢µ", "¡Òà»ÒàÃàÃ ¾¹ì¸Ò", "খত", "কাপোৰেৰে বন্ধা"],
    ["to leave, to abandon", "¢µ", "gÃÒ", "খত", "এৰা"],
    ["to throw away, to discard", "¢µ", "à»ÅÒ", "খত", "পেলা"],
    ["smoke", "¢¹", "à¸ÒÇÒ", "খন", "ধোৱা"],
    ["to kill", "¢¹", "ÁÃÒ", "খন", "মৰা"],
    ["soul", "¢¹", "ÍÒµìÁÒ", "খন", "আত্মা"],
    ["an edge", "¢»", "»Ø¢ØÃÕ å¡¹ÒÃ", "খপ", "পুখুৰী কিনাৰ"],
    ["to get, to meet", "¢»", "à»ÒÇÒ", "খপ", "পোৱা"],
    ["to want to", "¢Òw", "b¨ì©Ò ¡ÃÒ", "খাঔ", "ইচ্ছা কৰা"],
    ["to cross, as in to cross the hands", "¢b", "খই"],
    ["penis, male sex organ", "¢b", "à¡ÅÒ", "খই", "কেলা"],
    ["to die", "¢b", "ÁÃÒ", "খই", "মৰা"],
    ["jaundice, a kind of fever", "§Ò¡", "gå¾¸ à¾ÁÒÃ", "ঙাক", "এবিধ বেমাৰ"],
    ["to pull apart", "§Ò¡", "¼ÒåÅå·¿Ò", "ঙাক", "ফালিদিয়া"],
    ["to pull apart", "§Ò§", "¼ÒåÅå·¿Ò", "ঙাঙ", "ফালিদিয়া"],
    ["to draw a line", "§Ò§", "ÍíÒ¨ »ÃÒ", "ঙাঙ", "অ‍াঁচ পৰা"],
    ["to be face to face in fighting", "§Ò¹", "à¼Ã »µÒ", "ঙান", "ফেৰ পতা"],
    ["Naga", "§Ò¹", "¦åÃ¿ÒÅÃ å¹å¨¹Ò ª¹ìµØ", "ঙান", "ঘৰিয়ালৰ নিচিনা জন্‍তু"],
    ["to think", "§Ò»", "À¾Ò", "ঙাপ", "ভবা"],
    ["to aim", "§Ò", "¯ØÇÒb à¶ÒÇÒ", "ঙা", "টুৱাই থোৱা"],
    ["sesame", "§Ò", "åµÅ", "ঙা", "তিল"],
    ["tusk", "§Ò", "ÍÒ¤ ·íÒµ", "ঙা", "আগ দাঁত"],
    ["an elephant's tusk, ivory", "§Ò ¨Ò§", "ËÒµÕÃ ·íÒµ", "ঙা চাঙ", "হাতীৰ দাঁত"],
    ["to move the head from side to side", "à§¡", "à·¢ØÇÒ", "ঙেক", "দেখুৱা"],
    ["the point of a sharp object such as a knife", "å§§", "ªØ§Ò ÍÒ¤", "ঙিঙ", "জুঙা আগ"],
    ["to bare the teeth", "à§¹", "·íÒµ à·¢ØÇÒ", "ঙেন", "দাঁত দেখুৱা"],
    ["to hear", "å§¹", "ÈØ¹Ò", "ঙিন", "শুনা"],
    ["to insert into a small space", "å§»", "¤Øåª à¶ÒÇÒ", "ঙিপ", "গ‍ুজি থোৱা"],
    ["army training", "à§»", "åÃËÒ¨Å ¡ÃÒ", "ঙেপ", "ৰিহাচল কৰা"],
    ["to insert into a small space", "à§Á", "àÊÒàÁÒÇÒ", "ঙেম", "সোমোৱা"],
    ["to be unanimous", "§Õ (¡Ò¹)", "åÁÅÒ", "ঙী (কান)", "মিলা"],
    ["a kind of deer, a hog-deer", "§Õ", "ËåÃ¹", "ঙী", "হৰিন"],
    ["a kind of fever", "§Õ", "gå¾¸ à¾ÁÒÃ", "ঙী", "এবিধ বেমাৰ"],
    ["the second son in a Tai Aiton family", "§Õ", "å·ìÇµÕ¿ »Øµi", "ঙী", "দি্ৱতীয় পুতi"],
    ["an elephant's trunk", "§Ø§", "ÈØíÄ", "ঙুঙ", "শুঁড়"],
    ["a kind of tree, which is used for a medicine or poison which snake fear", "§Ø¹", "¾Ã ¤ØÁØå¹", "ঙুন", "বৰ গ‍ুমুনি"],
    ["to be unable to see that which is near, to be absent-minded", "§Ø»", "à¹à·¢Ò", "ঙুপ", "নেদেখা"],
    ["a snake", "à§Ò", "ÊÒ»", "ঙো", "সাপ"],
    ["small", "à§", "ÊÃØ", "ঙে", "সৰু"],
    ["now", "§Òb", "gåµ¿Ò", "ঙাই", "এতিয়া"],
    ["a meal", "§Òb", "»åÃÁÒ³", "ঙাই", "পৰিমাণ"],
    ["a classifier for meals", "§Òb", "ÊÒ©Ø", "ঙাই", "সাছু"],
    ["easy", "§Òb", "6ªØ", "ঙাই", "উজু"],
    ["to cover", "§ÒÁ", "²Ò¡", "ঙাম", "ঢাক"],
    ["to bend at the hips whilst standing straight, as if to touch the toes, to reach downward", "§ØÁ", "¡ØªÒ àËÒÇÒ", "ঙুম", "কুজা হোৱা"],
    ["to ambush", "§Á", "àªÒ»Ò", "ঙম", "জোপা"],
    ["a crocodile", "à§ä¡", "¦åÃ¿ÒÅ", "ঙৌক", "ঘৰিয়াল"],
    ["to cut with a sword (not a knife), to slash", "à§äµ", "µàÃÒÇÒàÅàÃ ¡¯Ò", "ঙৌত", "তৰোৱালেৰে কটা"],
    ["to have protruding teeth, like an animal", "à§ä¹", "·íÒµ FàÅÒÇÒ", "ঙৌন", "দাঁত ওলোৱা"],
    ["silver", "à§ä¹", "ÃØ»", "ঙৌন", "ৰুপ"],
    ["money", "à§ä¹", "¯¡Ò", "ঙৌন", "টকা"],
    ["to stand up and look out for something, stretching the head forward", "à§ä¹", "6å°6å° à¨ÒÇÒ", "ঙৌন", "উঠিউঠি চোৱা"],
    ["to look at something with displeasure", "à§ä", "±Ò§Ã ¨¡ØàÃ à¨ÒÇÒ", "ঙৌ", "ডাঙৰ চকুৰে চোৱা"],
    ["to look at something in a confused way", "à§ä", "±¸Ò Å¤Ò", "ঙৌ", "ডধা লগা"],
    ["to fear", "à§6", "À¿ ÀÒÇ", "ঙেউ", "ভয় ভাৱ"],
    ["a shadow", "§ÒF", "©íÒ", "ঙাও", "ছাঁ"],
    ["to look without seeing, to look blankly", "§ÒF", "¯¸Ò Å¤Ò", "ঙাও", "টধা লগা"],
    ["base (of a tree)", "§ÒF", "¤ØÃ", "ঙাও", "গ‍ুৰ"],
    ["to catch, to grab", "§ÒF", "¸åÃ¾áÅ àÅÒÇÒ", "ঙাও", "ধৰিবলৈ লোৱা"],
    ["to grab and pull towards one", "§ÒF", "¯Ò¹ ¸ÃÒ", "ঙাও", "টান ধৰা"],
    ["zigzag, curly", "§¡", "à¡¡ØÃÒ", "ঙক", "কেকুৰা"],
    ["to rear up (of a snake)", "§¡", "à¼¯ µØÅÒ", "ঙক", "ফেট তুলা"],
    ["the shoot of a tree or a plant", "§¡", "¤ËÒ", "ঙক", "গহা"],
    ["only zig not zag", "§§", "à¡¡ØÃÒ", "ঙঙ", "কেকুৰা"],
    ["a small hill", "§¹", "å¯ÅÒ", "ঙন", "টিলা"],
    ["to look", "§»", "à¨ÒÇÒ", "ঙপ", "চোৱা"],
    ["to dig, to hoe", "¨Ò¡", "চাক"],
    ["machine", "¨Ò¡", "চাক"],
    ["to fire a gun", "¨Ò¡", "চাক"],
    ["to hate", "¨Ò§", "চাঙ"],
    ["to employ, to hire", "¨Ò§", "চাঙ"],
    ["an elephant", "¨Ò§", "চাঙ"],
    ["to know", "¨Ò§", "চাঙ"],
    ["a goldsmith", "¨Ò§ ¢ÒÁ", "চাঙ খাম"],
    ["a silversmith", "¨Ò§ à§ä¹", "চাঙ ঙৌন"],
    ["an ironsmith", "¨Ò§ åÅ¡", "চাঙ লিক"],
    ["to reach, to accomplish", "¨Òµ", "চাত"],
    ["a drama", "¨Òµ", "চাত"],
    ["period of life", "¨Òµ", "চাত"],
    ["the next life", "¨Òµ ¹Ò", "চাত না"],
    ["this life", "¨Òµ ¹Òb", "চাত নাই"],
    ["steep", "¨Ò¹", "চান"],
    ["to stand", "¨Ò¹", "চান"],
    ["to stand", "¨Ò¹", "চান"],
    ["an open platform extending in front or behind the house, a porch", "¨Ò¹", "চান"],
    ["a big bag", "¨Ò¹", "চান"],
    ["to be dull or tasteless", "¨Ò¹", "চান"],
    ["to adhere to, to stick to", "¨Ò»", "চাপ"],
    ["to perch", "¨Ò»", "চাপ"],
    ["to join", "¨Ò»", "চাপ"],
    ["to cover", "¨Ò", "চা"],
    ["rough, not slippery", "¨Ò", "চা"],
    ["angry", "¨Ò", "চা"],
    ["the highest part, such as of a tree", "å¨¡", "চিক"],
    ["mind", "å¨¡", "চিক"],
    ["a kind of poison", "å¨§", "চিঙ"],
    ["a corner", "å¨§", "চিঙ"],
    ["seven", "å¨µ", "চিত"],
    ["to wipe", "å¨µ", "চিত"],
    ["a piece", "å¨¹", "চিন"],
    ["painful", "å¨»", "চিপ"],
    ["to follow", "à¨»", "চেপ"],
    ["since", "å¨Á", "চিম"],
    ["at that time", "å¨Á àÁä", "চিম মৌ"],
    ["too salty", "à¨Á", "চেম"],
    ["soon", "å¨6", "চিউ"],
    ["to carry on two sticks which are borne by four men", "à¨6", "চেউ"],
    ["to roast on a fire", "¨Õ", "চী"],
    ["to point", "¨Õ", "চী"],
    ["to stand", "¨Ø¡", "চুক"],
    ["to lead by the hand", "¨Ø§", "চুঙ"],
    ["coffin", "¨Ø§", "চুঙ"],
    ["a rhinoceros", "¨Ø§", "চুঙ"],
    ["not tasty, tasteless", "¨Øµ", "চুত"],
    ["to miss a target but just a little bit", "¨Øµ", "চুত"],
    ["to kiss", "¨Ø»", "চুপ"],
    ["to turn upside down", "à¨Ò", "চো"],
    ["to persuade", "¨Ù", "চূ"],
    ["to agree", "µÙ", "তূ"],
    ["life", "¨Ù", "চূ"],
    ["breast, either a woman's or a man's", "¨Ù", "চূ"],
    ["paper", "à¨", "চে"],
    ["to soak in water", "à¨", "চে"],
    ["now", "à¨", "চে"],
    ["a city", "à¨", "চে"],
    ["to hate, to dislike", "à¨", "চে"],
    ["to be sloping", "¨Òb", "চাই"],
    ["to buy", "¨Òb", "চাই"],
    ["brother", "¨Òb", "চাই"],
    ["to put a kettle on the stove", "¨", "চ"],
    ["to neglect", "¨", "চ"],
    ["a spoon", "¨", "চ"],
    ["to touch with one finger, to make a dot", "¨ÒÁ", "চাম"],
    ["to enjoy", "¨ÒÁ", "চাম"],
    ["to try", "¨ÒÁ", "চাম"],
    ["spot", "¨ØÁ", "চুম"],
    ["to be pleased, to be happy", "¨ØÁ", "চুম"],
    ["to insert something between two objects, such as a leaf between two sheets of paper", "¨Á", "চম"],
    ["to follow", "¨Á", "চম"],
    ["to join", "à¨ä¡", "চৌক"],
    ["string", "à¨ä¡", "চৌক"],
    ["a type of defensive fighting", "à¨ä§", "চৌঙ"],
    ["a servant, an assistant, a helper", "à¨ä§", "চৌঙ"],
    ["to become well", "à¨ä¹", "চৌন"],
    ["to join", "à¨ä»", "চৌপ"],
    ["to leak out, (of water)", "à¨äÁ", "চৌম"],
    ["name", "à¨ä", "¹ÒÁ", "চৌ", "নাম"],
    ["caste, ancestry on the mother's side, maternal descent", "à¨ä", "চৌ"],
    ["a prince", "¨ÒF", "চাও"],
    ["a prefix to the name of a respected person, mister", "¨ÒF", "চাও"],
    ["soon", "¨ÒF", "চাও"],
    ["to pick up something with the fingers, such as picking up rice before eating it", "¨ÒF", "চাও"],
    ["to select, to choose", "¨ÒF", "চাও"],
    ["to take something out of something, to extract", "¨¡", "চক"],
    ["a corner", "¨¡", "চক"],
    ["an umbrella", "¨§", "চঙ"],
    ["all", "¨µ", "চত"],
    ["protuberant", "¨¹", "চন"],
    ["a mongoose", "¨¹", "চন"],
    ["to dip up, scoop up", "¨¹", "চন"],
    ["to get other's ideas, get information", "¨»", "চপ"],
    ["to be hungry and not to get to eat, to starve", "¨» ¢ÒF", "চপ খাও"],
    ["heart, mind", "¨Òw", "চাঔ"],
    ["to employ", "¨Òw", "চাঔ"],
    ["yes", "¨Òw", "চাঔ"],
    ["a tooth of the Lord Buddha", "¨b", "চই"],
    ["a type of iron", "¨b", "চই"],
    ["the little finger", "¨b", "চই"],
    ["to help", "¨b", "চই"],
    ["to wash", "©Ò¡", "ছাক"],
    ["a pestle", "©Ò¡", "ছাক"],
    ["left overs", "©Ò¡", "ছাক"],
    ["to offer to a king", "©Ò¡", "ছাক"],
    ["age", "©Ò¡", "ছাক"],
    ["a novice monk", "©Ò§", "ছাঙ"],
    ["to stab", "©Ò§", "ছাঙ"],
    ["steamer, powered boat", "©Ò§ ¼", "ছাঙ ফ"],
    ["to press", "©Òµ", "ছাত"],
    ["a bamboo mat", "©Òµ", "ছাত"],
    ["to shiver", "©Ò¹", "ছান"],
    ["the back of a knife", "©Ò¹", "ছান"],
    ["to hit with the back of a knife", "©Ò¹", "ছান"],
    ["to boil", "©Ò¹", "ছান"],
    ["to diffuse, given as 'to go around'", "©Ò¹", "ছান"],
    ["to stab", "©Ò»", "ছাপ"],
    ["a Buddhist holiday, the eighth, fifteenth and twenty-third days of the Tai month.", "©Ò µÒ§", "ছা তাঙ"],
    ["a candle", "©Ò ÁÕ", "ছা মী"],
    ["an incense stick", "©Ò ÁÕ ËÁ", "ছা মী হম"],
    ["a teacher", "©Ò ÃÒ", "ছা ৰা"],
    ["the remains of food, such as the left over tea leaves", "©Ò", "ছা"],
    ["thank you", "©Ò ¶Ù", "ছা থূ"],
    ["so many fruits on the tree", "©Ò", "ছা"],
    ["beautiful, good", "©Ò", "ছা"],
    ["a type of bamboo basket, used only by the Tais.", "©Ò", "ছা"],
    ["to shoo away dogs", "å©¡", "ছিক"],
    ["a section of a fruit, a piece of a fruit", "å©¡", "ছিক"],
    ["to block", "å©§", "ছিঙ"],
    ["to finish, to end", "å©§", "ছিঙ"],
    ["sound", "å©§", "ছিঙ"],
    ["should", "å©§", "ছিঙ"],
    ["a diamond", "å©§", "ছিঙ"],
    ["to roar", "à©¹", "ছেন"],
    ["beautiful", "à©¹", "ছেন"],
    ["to fry", "à©¹", "ছেন"],
    ["to hate", "å©µ", "ছিত"],
    ["morality, Sila", "å©¹", "ছিন"],
    ["a skirt", "å©¹", "ছিন"],
    ["ten", "å©»", "ছিপ"],
    ["to thrust into", "å©»", "ছিপ"],
    ["pointed", "å©Á", "ছিম"],
    ["to insert", "å©Á", "ছিম"],
    ["four", "©Õ", "ছী"],
    ["to find", "©Õ", "ছী"],
    ["to", "©Õ", "ছী"],
    ["a tooth (of a comb)", "©Õ", "ছী"],
    ["ripe", "©Ø¡", "ছুক"],
    ["to wash", "©Ø¡", "ছুক"],
    ["to use", "©Ø§", "ছুঙ"],
    ["tall", "©Ø§", "ছুঙ"],
    ["to soak in water, to dab with water", "©Øb", "ছুই"],
    ["protection", "©Øb", "ছুই"],
    ["a mosquito net", "©Øµ", "ছুত"],
    ["to be worn away by friction", "©Øµ", "ছুত"],
    ["to push aside a little, as when making more space while sitting on a bench", "©Øµ", "ছুত"],
    ["to knit, to make a net", "©Ø¹", "ছুন"],
    ["a garden", "©Ø¹", "ছুন"],
    ["to put on", "©Ø»", "ছুপ"],
    ["mouth", "©Ø»", "ছুপ"],
    ["to agree", "©Ù", "ছূ"],
    ["you all", "©Ù", "ছূ"],
    ["to carry with a stick", "à©", "ছে"],
    ["to clean the teeth", "à© å¢6", "ছে খিউ"],
    ["fourth son", "©Òb", "ছাই"],
    ["a kind of fish trap", "©Òb", "ছাই"],
    ["intestines", "©Òb", "ছাই"],
    ["to return, to go back", "©Òb", "ছাই"],
    ["jealous", "©Òb", "ছাই"],
    ["to push", "©Òb", "ছাই"],
    ["sand", "©Òb", "ছাই"],
    ["string", "©Òb", "ছাই"],
    ["to persuade, to advise to work", "©", "ছ"],
    ["to urinate", "©", "ছ"],
    ["to have an injection", "©ÒÁ", "ছাম"],
    ["to repeat", "©ÒÁ", "ছাম"],
    ["a harpoon for attacking fish", "©ÒÁ", "ছাম"],
    ["three", "©ÒÁ", "ছাম"],
    ["third son", "©ÒÁ", "ছাম"],
    ["a bamboo fish trap", "©ØÁ", "ছুম"],
    ["to lose", "©ØÁ", "ছুম"],
    ["a little hut in the rice field, used for resting", "©ØÁ", "ছুম"],
    ["sour", "©ØÁ", "ছুম"],
    ["blue", "©Á", "ছম"],
    ["funeral", "©Á", "ছম"],
    ["to transplant paddy", "©Á", "ছম"],
    ["to fight, war", "à©ä¡", "ছৌক"],
    ["the cooking house of monks", "à©ä§", "ছৌঙ"],
    ["a kind of tree", "à©ä§", "ছৌঙ"],
    ["to hide", "à©ä§", "ছৌঙ"],
    ["the day before yesterday", "à©ä¹", "ছৌন"],
    ["to join", "à©ä»", "ছৌপ"],
    ["to buy", "à©ä", "ছৌ"],
    ["straight", "à©ä", "ছৌ"],
    ["shirt", "à©ä", "ছৌ"],
    ["a tiger", "à©ä", "ছৌ"],
    ["a chisel", "å©6", "ছিউ"],
    ["pimple", "å©6", "ছিউ"],
    ["king crow, given as 'a kind of bird'", "à©6", "ছেউ"],
    ["to catch", "à©6", "ছেউ"],
    ["to stay", "©ÒF", "ছাও"],
    ["gloomy", "©ÒF", "ছাও"],
    ["a post, a pole", "©ÒF", "ছাও"],
    ["twenty", "©ÒF", "ছাও"],
    ["a long bamboo pole used for getting coconut", "©ÒF", "ছাও"],
    ["a young girl", "©ÒF", "ছাও"],
    ["a cubit", "©¡", "ছক"],
    ["to seek out, to search for", "©¡", "ছক"],
    ["to joke", "©¡ åÅ¹", "ছক লিন"],
    ["a type of bamboo basket", "©§", "ছঙ"],
    ["to grab someone by the arm or by the shoulder", "©§", "ছঙ"],
    ["a type of fish-trap", "©§ ©Òb", "ছঙ ছাই"],
    ["joking", "©§", "ছঙ"],
    ["two", "©§", "ছঙ"],
    ["to burn", "©µ", "ছত"],
    ["to gossip", "©µ", "ছত"],
    ["so many", "©µ å©6", "ছত ছিউ"],
    ["a funnel", "©µ", "ছত"],
    ["to insert", "©¹", "ছন"],
    ["a type of fish-trap", "©¹", "ছন"],
    ["to catch fish using a sɔn³.", "©¹", "ছন"],
    ["to place in between, as sheets between paper", "©¹ ¡Ò¹", "ছন কান"],
    ["so many people", "©¹ ¡Ò¹ (à©ä» ¡Ò¹)", "ছন কান (ছৌপ কান)"],
    ["to teach", "©¹", "ছন"],
    ["to learn", "©¹", "ছন"],
    ["mad", "©»", "ছপ"],
    ["to put into", "©Òw", "ছাঔ"],
    ["OK, yes", "©Òw", "ছাঔ"],
    ["clear, as water", "©Òw", "ছাঔ"],
    ["to get narrower, to taper", "©b", "ছই"],
    ["to cut vegetables into small pieces", "©b", "ছই"],
    ["to be up in a tree", "©b", "ছই"],
    ["wisdom", "Ò¹", "ান"],
    ["a rehearsal for a drama", "Ò»", "াপ"],
    ["to get", "Ò", "া"],
    ["medicine", "Ò", "া"],
    ["to hear", "å¹", "নি"],
    ["to plant paddy", "å»", "পি"],
    ["to eat, spoken when angry", "àÁ", "মে"],
    ["same", "Õ", "ী"],
    ["to eat, used in a jocular sense", "Á", "ম"],
    ["a kind of tree, found in the temple compound", "§", "ঙ"],
    ["a glass given to the Buddha by his mother", "§ àÃ", "ঙ ৰে"],
    ["big", "Òw", "াঔ"],
    ["to bring water from the pond", "µÒ¡", "তাক"],
    ["will, expression of future tense", "µÒ¡", "তাক"],
    ["to make a clicking sound with the tongue", "µÒ¡ åÅ¹", "তাক লিন"],
    ["to dry in the sun, to expose to the sun", "µÒ¡", "তাক"],
    ["to count", "µÒ¡", "তাক"],
    ["a leech", "µÒ¡", "àªÒ¡", "তাক", "জোক"],
    ["to ask a question", "µÒ¡", "তাক"],
    ["a table, used for sitting on", "µÒ§", "àÁª", "তাঙ", "মেজ"],
    ["to set up, to make something stand", "µÒ§", "তাঙ"],
    ["to put on, to place on", "µÒ§", "তাঙ"],
    ["another", "µÒ§", "তাঙ"],
    ["another place", "µÒ§ µÕ", "তাঙ তী"],
    ["road", "µÒ§", "তাঙ"],
    ["to come to meet by short cut", "µÒµ ¨Ù", "à»Ò¹áË ÍËÒ", "তাত চূ", "পোনহৈ অহা"],
    ["to cut grass", "µÒµ", "তাত"],
    ["to bar, to obstruct, given as 'the water is shut up and you cannot go'", "µÒ¹", "তান"],
    ["like, the same as", "µÒ¹", "তান"],
    ["cancer", "µÒ¹", "তান"],
    ["to speak, to say", "µÒ¹", "তান"],
    ["the liver", "µÒ»", "তাপ"],
    ["a town", "µÒ»", "তাপ"],
    ["must", "µÒ»", "তাপ"],
    ["lustful, given as \"sex mind\"", "µÒ¹Ò", "তানা"],
    ["a fence", "µÒ", "তা"],
    ["to paint, to apply", "µÒ", "তা"],
    ["eye", "µÒ", "তা"],
    ["blind", "µÒ ¾µ", "তা বত"],
    ["broken", "àµ¡", "তেক"],
    ["a box", "àµ¡", "তেক"],
    ["a radio", "àµ¡ Á ¢ÒÁ", "তেক ম খাম"],
    ["a television", "àµ¡ ËÒ§", "তেক হাঙ"],
    ["to measure", "àµ¡", "তেক"],
    ["a kind of stringed musical instrument, like a guitar", "åµ§", "তিঙ"],
    ["a water leech", "åµ§", "তিঙ"],
    ["to place pressure on", "åµ§", "তিঙ"],
    ["to punch", "åµ§", "তিঙ"],
    ["to stab", "àµ§", "তেঙ"],
    ["to bargain", "àµ§", "তেঙ"],
    ["to touch", "àµµ", "তেত"],
    ["leg", "åµ¹", "তিন"],
    ["to walk on the side of the foot", "åµ¹ »Òb", "তিন পাই"],
    ["leg in plaster", "åµ¹ ÁÒ¹", "তিন মান"],
    ["a broken leg", "åµ¹ ÃÒ¡", "তিন ৰাক"],
    ["to jump, to hop", "åµ¹", "তিন"],
    ["to move from side to side, while not free from a bundle which is tied to his back", "åµ¹ µ¡", "তিন তক"],
    ["to kill", "àµ¹", "তেন"],
    ["a hornet", "àµ¹", "তেন"],
    ["narrow", "åµ»", "তিপ"],
    ["to cut", "àµ»", "তেপ"],
    ["full", "åµÁ", "তিম"],
    ["to write", "àµÁ", "তেম"],
    ["to clear land", "µÕ", "তী"],
    ["place", "µÕ", "তী"],
    ["at", "µÕ", "তী"],
    ["to hit, to kill, to beat", "µØ¡", "তুক"],
    ["to fall down", "µØ¡", "তুক"],
    ["the sound of falling down", "µØ¡ µØ¡", "তুক তুক"],
    ["a man's lungi", "µØ§", "তুঙ"],
    ["to accept, receive a gift with both hands", "µØ§", "তুঙ"],
    ["joist", "µØ§", "তুঙ"],
    ["to welcome somebody, to greet", "µØ§", "তুঙ"],
    ["a transvestite", "µØb", "তুই"],
    ["equal, same", "µØb", "তুই"],
    ["a kind of horn", "µØµ", "তুত"],
    ["to pass wind, to fart", "µØµ", "তুত"],
    ["to convert", "µØ¹", "তুন"],
    ["to insert into a pipe", "µØ¹", "তুন"],
    ["a tree", "µØ¹", "তুন"],
    ["a plant", "µØ¹", "তুন"],
    ["to belch", "µØ¹", "তুন"],
    ["shallow", "µØ¹", "তুন"],
    ["to slap; to kill (mosquito);to swat", "µØ»", "তুপ"],
    ["to swat a mosquito", "µØ» ÂØ§", "তুপ যুঙ"],
    ["to wrap up", "µØ»", "তুপ"],
    ["body", "µÙ", "তূ"],
    ["animal", "µÙ", "তূ"],
    ["classifier for animals", "µÙ", "তূ"],
    ["same, alike", "µÙ", "তূ"],
    ["to begin, to start, opening", "àµ", "তে"],
    ["to discover", "àµ µÒ§", "তে তাঙ"],
    ["to make a road, to construct a road", "àµ µÒ§", "তে তাঙ"],
    ["a path through a rice field", "àµ", "তে"],
    ["to come into the house, said of rain, to beat into the house", "àµ", "তে"],
    ["true", "àµ", "তে"],
    ["surely", "àµ àµ", "তে তে"],
    ["to walk, as a monkey walks on a branch", "µÒb", "তাই"],
    ["a little, used for tastes such as spicy or sour", "µÒb", "তাই"],
    ["Tai, the name for the Tai people", "µÒb", "তাই"],
    ["a friend", "µÒb ¡", "তাই ক"],
    ["a tune", "µÒb", "তাই"],
    ["to die", "µÒb", "তাই"],
    ["near", "µÒb", "তাই"],
    ["to play games", "µ", "ত"],
    ["a kind of bee, a hornet", "µ", "ত"],
    ["to accidentally bump into", "µ", "ত"],
    ["selfish", "µ ·Ø¡", "ত দুক"],
    ["to fight", "µ (¡Ò¹)", "ত (কান)"],
    ["to weave", "µ", "ত"],
    ["the stump of a tree", "µ ·¡", "ত দক"],
    ["to carry", "µ", "ত"],
    ["penis", "µ µ", "ত ত"],
    ["low", "µÒÁ", "¨Ò»Ã", "তাম", "চাপৰ"],
    ["short (in height)", "µÒÁ", "তাম"],
    ["a brush, like a tooth-brush", "µÒÁ »Ù", "তাম পূ"],
    ["to pound", "µÒÁ", "তাম"],
    ["punishment", "µÒÁ", "তাম"],
    ["to heap, (i.e. with rice)", "µØÁ", "তুম"],
    ["a kind of large basket made of bamboo and rattan, which sits on the ground. It is only used by the Tais", "µØÁ", "তুম"],
    ["to boil", "µØÁ", "তুম"],
    ["used to describe very small, round things", "µÁ", "তম"],
    ["to hover", "µÁ", "তম"],
    ["worm", "àµä¡", "তৌক"],
    ["to fight", "àµä¡", "তৌক"],
    ["end", "àµä¡", "তৌক"],
    ["deep", "àµä§", "তৌঙ"],
    ["to curse", "àµä§", "তৌঙ"],
    ["not to hear clearly, as when somebody speaks and another cannot hear them", "àµä§", "তৌঙ"],
    ["a memorial", "àµä§ å©µ ¨Ò", "তৌঙ ছিত চা"],
    ["a deer, such as that which Rama killed", "àµä§", "তৌঙ"],
    ["to pull", "àµäµ", "তৌত"],
    ["to pull and fall down onto the ground", "àµäµ ÅÒ¡ ÅØµ", "তৌত লাক লুত"],
    ["to wake", "àµä¹", "তৌন"],
    ["to tear", "àµä¹", "তৌন"],
    ["to scratch", "àµä¹", "তৌন"],
    ["to be lying down", "àµä¹ àÅä¹", "তৌন লৌন"],
    ["blunt", "àµäÁ", "তৌম"],
    ["foolish, not brilliant", "àµäÁ", "তৌম"],
    ["to hold", "àµä", "তৌ"],
    ["to drop", "àµä", "তৌ"],
    ["a tortoise", "µÒF", "তাও"],
    ["the shuttle of a loom", "µÒF", "তাও"],
    ["to spit", "µÒF", "তাও"],
    ["a hunter", "µÒF", "তাও"],
    ["to touch", "µÒF", "তাও"],
    ["ashes", "µÒF", "তাও"],
    ["to pour water from a pot - given as 'water falling down from the pot'", "µÒF", "তাও"],
    ["a sword", "µÒF", "তাও"],
    ["name of one of the Aiton castes, an army caste, a surname", "µÒF ©§", "তাও ছঙ"],
    ["to hammer", "µ¡", "তক"],
    ["the name of a Tai book, a story of the life of the Buddha", "µ¡ ¨ØÁ", "তক চুম"],
    ["to print (a book)", "µ¡ åÅ¡", "তক লিক"],
    ["a strip of bamboo", "µ¡", "তক"],
    ["art", "µ¡", "তক"],
    ["a type of lizard", "µ¡ µ", "তক ত"],
    ["tɔk¹ tɛk¹", "ikq", "µ¡ àµ¡", "ိက︀်", "তক তেক"],
    ["a scale, to weigh", "µ¡", "তক"],
    ["bright", "µ§", "তঙ"],
    ["the sound of bells ringing", "µ§ µ§", "তঙ তঙ"],
    ["brass", "µ§", "তঙ"],
    ["a large leaf, such as a banana leaf", "µ§", "তঙ"],
    ["a kind of leaf, used for wrapping food", "µ§ å¨§", "তঙ চিঙ"],
    ["to know, to understand", "µ§", "তঙ"],
    ["to request", "µ§ »Ò¹", "তঙ পান"],
    ["to touch or hit something, as to hit with your head something which is hanging from the roof, or to shave something with your shoulder or elbow", "µ§", "তঙ"],
    ["stomach", "µ§", "তঙ"],
    ["to have a tight stomch, to be constipated", "µ§ ¡Ò»", "তঙ কাপ"],
    ["a condition in which there is a large amount of gas in the stomach and it cannot escape, so the stomach becomes bloated", "µ§ ¡Òw", "তঙ কাঔ"],
    ["tɔŋ³ kyaa²", "a", "µ§ ¡pÒ", "ႃ", "তঙ ক্যা"],
    ["to have a bound up stomach", "µ§ àµ§", "তঙ তেঙ"],
    ["to have a puffed-up stomach", "µ§ »§", "তঙ পঙ"],
    ["a type of dysentry which is not bloody", "µ§ ÂÒ§ ¾¹", "তঙ যাঙ বন"],
    ["bloody dystentry", "µ§ àÅäµ", "তঙ লৌত"],
    ["to bite, as a snake or bird", "µµ", "তত"],
    ["to castrate", "µ¹", "তন"],
    ["an expert", "µ¹", "তন"],
    ["to be short-tempered", "µ¹", "তন"],
    ["to remind", "µ¹", "তন"],
    ["a piece", "µ¹", "তন"],
    ["piece by piece", "µ¹ µ¹ àµ¹ àµ¹", "তন তন তেন তেন"],
    ["to reply", "µ»", "তপ"],
    ["to cook with gas", "µ»", "তপ"],
    ["the kidney", "µÒw", "তাঔ"],
    ["to not give something in return. This word is used when, for example, one person who is eating gives something to another, and the second person does not give anything", "µÒw", "তাঔ"],
    ["below", "µÒw", "তাঔ"],
    ["to knock, to hit", "µb", "তই"],
    ["to revise", "µb", "তই"],
    ["to peel", "¶Ò¡", "থাক"],
    ["to leave the monkhood, to disrobe", "¶Ò¡", "থাক"],
    ["to pour", "¶Ò§", "থাঙ"],
    ["facilities", "¶Ò§ ÅÒ", "থাঙ লা"],
    ["easy", "¶Ò§", "থাঙ"],
    ["a broad field", "¶Ò§ ¡Ò§ (¶Ò§ ¡Ø§)", "থাঙ কাঙ (থাঙ কুঙ)"],
    ["to stop, said of rain", "¶Òµ", "থাত"],
    ["memorial", "¶Òµ", "থাত"],
    ["there", "¶Ò¹", "থান"],
    ["coal", "¶Ò¹ (¼Òb)", "থান (ফাই)"],
    ["a palm-tree", "¶Ò¹", "থান"],
    ["to cover", "¶Ò»", "থাপ"],
    ["a face-cover", "¶Ò» ¹Ò", "থাপ না"],
    ["to scold", "¶Ò", "থা"],
    ["to quarrel", "¶Ò ¡Ò¹", "থা কান"],
    ["to relapse; to become ill again over and over again", "¶Ò", "থা"],
    ["to wait", "¶Ò", "থা"],
    ["to have a hair cut, to shave", "¶Ò", "থা"],
    ["to match", "à¶¡", "থেক"],
    ["to argue", "å¶§", "থিঙ"],
    ["a small hut which is built in a tree, used as a refuge from wild animals", "å¶§", "থিঙ"],
    ["to join together", "à¶§", "থেঙ"],
    ["to send", "å¶¹", "থিন"],
    ["to kick", "å¶»", "থিপ"],
    ["to throw", "å¶Á", "থিম"],
    ["to get water from an earthen pot to present to someone", "à¶Á", "থেম"],
    ["to whistle", "å¶6", "থিউ"],
    ["selfish, a miser", "¶Õ", "থী"],
    ["(push) with force", "¶Õ", "থী"],
    ["a decoration or architectural feature around the temple", "¶Õ", "থী"],
    ["correct", "¶Ø¡", "থুক"],
    ["to hit", "¶Ø¡", "থুক"],
    ["to get", "¶Ø¡", "»Ò¿", "থুক", "পায়"],
    ["tradition, custom", "¶Ø§", "থুঙ"],
    ["bag", "¶Ø§", "থুঙ"],
    ["to pull out", "¶Øb", "থুই"],
    ["the new front leaf of a plant", "¶Øµ", "থুত"],
    ["good, auspicious", "¶Ø¹", "থুন"],
    ["complete", "¶Ø¹", "থুন"],
    ["bean", "¶Ù", "থূ"],
    ["a type of long bean", "¶Ù ¡Ò§ à¡", "থূ কাঙ কে"],
    ["a type of small bean", "¶Ù à¶»", "থূ থেপ"],
    ["red lentils", "¶Ù à·§", "থূ দেঙ"],
    ["black lentils", "¶Ù å·¹", "থূ দিন"],
    ["a type of tuber, type of bean", "¶Ù ÁÒ¹ ¡Òµ", "থূ মান কাত"],
    ["a type of small bean", "¶Ù ÁÒ g¹", "থূ মা এন"],
    ["yellow lentils, used for making dhal", "¶Ù àÅä§", "থূ লৌঙ"],
    ["to push", "à¶Ò", "থো"],
    ["to rub", "¶Ù", "থূ"],
    ["to give more", "à¶", "থে"],
    ["to change", "¶Òb", "থাই"],
    ["here", "¶Òb", "থাই"],
    ["to plough", "¶Òb", "থাই"],
    ["to push with the hand, as in to push a boat", "¶", "থ"],
    ["to push with an implement", "¶", "থ"],
    ["a cave", "¶ÒÁ", "¤ØËÒ", "থাম", "গ‍ুহা"],
    ["Dharma, righteousness", "¶ÒÁ ÁÒ", "¸IÁ", "থাম মা", "ধiম"],
    ["to ask", "¶ÒÁ", "àÊÒ¸Ò", "থাম", "সোধা"],
    ["flood", "¶ØÁ", "থুম"],
    ["to listen", "¶Á", "থম"],
    ["male, used for animals", "à¶ä¡", "থৌক"],
    ["to reach", "à¶ä§", "থৌঙ"],
    ["a type of large basket", "à¶ä§", "থৌঙ"],
    ["a forest", "à¶ä¹", "থৌন"],
    ["to touch without catching, as when attempting to catch fish by hand in the river, touching them but not catching", "à¶ä»", "থৌপ"],
    ["covered by earth", "à¶äÁ", "থৌম"],
    ["to cut with a saw or hacksaw", "à¶ä", "থৌ"],
    ["to change", "¶¡", "থক"],
    ["to bind the legs, such as binding the legs of a horse", "¶§", "থঙ"],
    ["to break, such as when a cow breaks a wall", "¶§", "থঙ"],
    ["to take out, to pull out", "¶µ", "থত"],
    ["to cover", "¶»", "থপ"],
    ["where", "¶Òw", "থাঔ"],
    ["to lie", "¶b", "থই"],
    ["heavy", "¹Ò¡", "নাক"],
    ["to beat", "¹Ò¡", "নাক"],
    ["7th son", "¹Ò¡", "নাক"],
    ["black", "¹Ò¡", "নাক"],
    ["same", "¹Ò§", "নাঙ"],
    ["nose", "¹Ò§", "নাঙ"],
    ["noise", "¹Ò§", "নাঙ"],
    ["to sit", "¹Ò§", "নাঙ"],
    ["skin", "¹Ò§", "নাঙ"],
    ["explained as \"to take a big log and put rollers under the heavy object", "¹Ò§", "নাঙ"],
    ["Miss", "¹Ò§", "নাঙ"],
    ["lady, queen", "¹Ò§", "নাঙ"],
    ["that", "¹Òµ", "নাত"],
    ["slowly", "¹Ò¹", "নান"],
    ["to extinguish, to put out (of a fire)", "¹Ò»", "নাপ"],
    ["sword", "¹Ò»", "নাপ"],
    ["to quarrel", "¹Ò", "না"],
    ["paddy field", "¹Ò", "না"],
    ["to hang paddy out in the paddy field", "¹Ò", "না"],
    ["face", "¹Ò", "না"],
    ["forehead", "¹Ò ¼Ò¡", "না ফাক"],
    ["north", "¹Ò Ë§", "না হঙ"],
    ["uncle", "¹Ò", "না"],
    ["thick", "¹Ò", "না"],
    ["to criticise", "å¹¡", "নিক"],
    ["to press with the heal of the foot", "å¹§", "নিঙ"],
    ["tea", "å¹§", "নিঙ"],
    ["to realise", "à¹§", "নেঙ"],
    ["red", "à¹§", "নেঙ"],
    ["to flick with the fingers, to pluck", "å¹µ", "নিত"],
    ["sunlight", "à¹µ", "নেত"],
    ["to hurry", "à¹µ", "নেত"],
    ["earth", "å¹¹", "নিন"],
    ["to hit, given as \"to hit but not dead\"", "å¹¹", "নিন"],
    ["raw", "å¹»", "নিপ"],
    ["living", "å¹»", "নিপ"],
    ["quiet, silent", "å¹Á", "নিম"],
    ["a finger", "å¹6", "নিউ"],
    ["sticky", "å¹6", "নিউ"],
    ["good", "¹Õ", "নী"],
    ["bile, given as \"internal organ\"", "¹Õ", "নী"],
    ["debt", "¹Õ", "নী"],
    ["bone", "¹Ø¡", "নুক"],
    ["bird", "¹Ø¡", "নুক"],
    ["crow", "¹Ø¡ ¡Ò", "নুক কা"],
    ["mynah", "¹Ø¡ å¡6", "নুক কিউ"],
    ["owl", "¹Ø¡ ¡ÒF", "নুক কাও"],
    ["sparrow", "¹Ø¡ ¨¡", "নুক চক"],
    ["a type of sparrow that nests in a coconut tree. It appears in the seventh and eighth months.", "¹Ø¡ ¨¡ »ìÃÒ", "নুক চক প্ৰা"],
    ["a type of bird", "¹Ø¡ ©Òb", "নুক ছাই"],
    ["a type of bird", "¹Ø¡ àµ¡ »ìÃÒ»", "নুক তেক প্ৰাপ"],
    ["parrot", "¹Ø¡ àµµ", "নুক তেত"],
    ["dove", "¹Ø¡ µÙ", "নুক তূ"],
    ["a type of large bird", "¹Ø¡ å¹¡", "নুক নিক"],
    ["small bird", "¹Ø¡ å»µ", "নুক পিত"],
    ["bulbul", "¹Ø¡ à»§ à»ìÅ6", "নুক পেঙ পে্‍লউ"],
    ["crane", "¹Ø¡ ÂÒ§", "নুক যাঙ"],
    ["peacock", "¹Ø¡ ÂÖ§", "নুক যৃঙ"],
    ["to wear", "¹Ø§", "নুঙ"],
    ["tired", "¹Øb", "নুই"],
    ["beard, moustache", "¹Øµ", "নুত"],
    ["to massage", "¹Øµ", "নুত"],
    ["to be crumpled, to be not ironed", "¹Ø¹ (å¹¹)", "নুন (নিন)"],
    ["to look at", "¹Ù", "নূ"],
    ["rat", "¹Ù", "নূ"],
    ["to get", "¹Òb", "নাই"],
    ["this", "¹Òb", "নাই"],
    ["to vow", "¹Òb", "নাই"],
    ["alone, blank (as of a cassette)", "¹Òb", "নাই"],
    ["dew", "¹Òb", "নাই"],
    ["maternal grandmother", "¹Òb", "নাই"],
    ["shoot, sprout", "¹", "ন"],
    ["water", "¹ÒÁ", "নাম"],
    ["liquid", "¹ÒÁ", "নাম"],
    ["milk", "¹ÒÁ à¨", "নাম চে"],
    ["tears", "¹ÒÁ µÒ", "নাম তা"],
    ["oil", "¹ÒÁ ÁÒ¹", "নাম মান"],
    ["mustard oil", "¹ÒÁ ÁÒ¹ å¨¹", "নাম মান চিন"],
    ["kerosene", "¹ÒÁ åÁ¹", "নাম মিন"],
    ["mucous", "¹ÒÁ ÁØ¡", "নাম মুক"],
    ["ink", "¹ÒÁ àÁä¡", "নাম মৌক"],
    ["saliva", "¹ÒÁ ÅÒb", "নাম লাই"],
    ["many", "¹ÒÁ", "নাম"],
    ["thorn", "¹ÒÁ", "নাম"],
    ["young", "¹ØÁ", "নুম"],
    ["to smell", "¹ØÁ", "নুম"],
    ["base, low, mean, explained as \"if a person kills another, he is called kun² nɔm²; a servant is also called nɔm²\"", "¹Á", "নম"],
    ["lazy, not brilliant", "à¹ä¡", "নৌক"],
    ["to steam", "à¹ä§", "নৌঙ"],
    ["hot", "à¹äµ", "নৌত"],
    ["an exclamation of annoyance, e.g. damn!", "à¹äµ", "নৌত"],
    ["the moon", "à¹ä¹", "নৌন"],
    ["month", "à¹ä¹", "নৌন"],
    ["meat, flesh", "à¹ä", "নৌ"],
    ["above", "à¹ä", "নৌ"],
    ["rotten", "¹ÒF", "নাও"],
    ["star", "¹ÒF", "নাও"],
    ["cold", "¹ÒF", "নাও"],
    ["rotten", "¹¡", "নক"],
    ["outside", "¹¡", "নক"],
    ["heavy, to weigh", "¹§", "নঙ"],
    ["younger sibling", "¹§", "নঙ"],
    ["brother-in-law (male speaking)", "¹§ ¢Øb", "নঙ খুই"],
    ["younger brother", "¹§ ¨Òb", "নঙ চাই"],
    ["younger sister", "¹§ ©ÒF", "নঙ ছাও"],
    ["sister-in-law", "¹§ »Òw", "নঙ পাঔ"],
    ["brother-in-law (female speaking)", "¹§ ÁÒF", "নঙ মাও"],
    ["brother-in-law (female speaking)", "¹§ ¾ÒF", "নঙ বাও"],
    ["a pond", "¹§", "নঙ"],
    ["to sleep", "¹¹", "নন"],
    ["worms", "¹¹", "নন"],
    ["type of worm", "¹¹ ¢Õ ÇÙ", "নন খী ৱূ"],
    ["to offer to the king", "¹»", "নপ"],
    ["in", "¹Òw", "নাঔ"],
    ["which?", "¹Òw", "নাঔ"],
    ["morning", "¹Òw", "নাঔ"],
    ["hill, mountain", "¹b", "নই"],
    ["small, little", "¹b", "নই"],
    ["nose", "·Ò§", "দাঙ"],
    ["noise", "·Ò§", "দাঙ"],
    ["to extinguish, to put out (of a fire)", "·Ò»", "দাপ"],
    ["sword", "·Ò»", "দাপ"],
    ["to quarrel", "·Ò", "দা"],
    ["to hang paddy out in the paddy field", "·Ò", "দা"],
    ["red", "à·§", "দেঙ"],
    ["to flick with the fingers, to pluck", "å·µ", "দিত"],
    ["sunlight", "à·µ", "দেত"],
    ["earth", "å·¹", "দিন"],
    ["raw", "å·»", "দিপ"],
    ["living", "å·»", "দিপ"],
    ["good", "·Õ", "দী"],
    ["bile, given as \"internal organ\"", "·Õ", "দী"],
    ["to look at", "·Ù", "দূ"],
    ["to get", "·Òb", "দাই"],
    ["alone, blank (as of a cassette)", "·Òb", "দাই"],
    ["to smell", "·ØÁ", "দুম"],
    ["hot", "à·äµ", "দৌত"],
    ["an exclamation of annoyance, e.g. damn!", "à·äµ", "দৌত"],
    ["the moon", "à·ä¹", "দৌন"],
    ["month", "à·ä¹", "দৌন"],
    ["star", "·ÒF", "দাও"],
    ["rotten", "·¡", "দক"],
    ["which?", "·Òw", "দাঔ"],
    ["hill, mountain", "·b", "দই"],
    ["mouth", "»Ò¡", "পাক"],
    ["one hundred", "»Ò¡", "পাক"],
    ["one hundred and fifty", "»ÒË »Òb", "পাহ পাই"],
    ["straw", "»Ò¡", "পাক"],
    ["to part", "»Ò¡", "পাক"],
    ["broken", "»Ò§", "পাঙ"],
    ["to join, to tie together", "»Ò§", "পাঙ"],
    ["to invite", "»Ò§", "পাঙ"],
    ["a kind of worm that lives in the body", "»Ò§", "পাঙ"],
    ["to sweep", "»Òµ", "পাত"],
    ["to cut, as in to cut rice stalks during harvest", "»Òµ", "পাত"],
    ["a type of tree frog", "»ìÃÒµ", "প্ৰাত"],
    ["to hang something, as in to hang clothes", "»Òµ", "পাত"],
    ["to go around, to whirl", "»Ò¹", "পান"],
    ["to give, to distribute", "»Ò¹", "পান"],
    ["fist", "»Ò¹", "পান"],
    ["a classifier of time", "»Ò¹", "পান"],
    ["", "»Ò¹", "ÅÒå¤ ¸ÃÒ", "পান", "লাগি ধৰা"],
    ["a book", "»Ò»", "পাপ"],
    ["fish", "»Ò", "পা"],
    ["a type of fish", "»Ò ¨Ò§ å¨»", "পা চাঙ চিপ"],
    ["a type of fish", "»Ò å©§ à§", "পা ছিঙ ঙে"],
    ["a type of fish", "»Ò µ§ »»", "পা তঙ পপ"],
    ["a type of large fish", "»Ò »Ò à¢", "পা পা খে"],
    ["a type of fish", "»Ò »Ò å©6", "পা পা ছিউ"],
    ["a kind of catfish", "»Ò »Ò ·Ø¡", "পা পা দুক"],
    ["a type of fish", "»Ò »Ò »¡", "পা পা পক"],
    ["a type of fish", "»Ò »Ò ÃÒµ", "পা পা ৰাত"],
    ["a type of fish", "»Ò »Ò ÅÒb", "পা পা লাই"],
    ["a type of fish", "»Ò »Ò Å¹", "পা পা লন"],
    ["a type of fish", "»Ò ËÙ ¢Ò¹", "পা হূ খান"],
    ["a type of fish", "»Ò 6» ÍÒ»", "পা উপ আপ"],
    ["to carry on the back of the head", "»Ò", "পা"],
    ["a classifier for monks", "»Ò", "পা"],
    ["aunt", "»Ò", "পা"],
    ["a Tai basket", "»Ò", "পা"],
    ["debt", "»Ò", "পা"],
    ["wing", "å»¡", "পিক"],
    ["to destroy", "à»¡", "পেক"],
    ["to reach up", "å»§", "পিঙ"],
    ["to roast", "å»§", "পিঙ"],
    ["to rule over", "à»§", "পেঙ"],
    ["time", "à»§", "পেঙ"],
    ["more noise", "à»§", "পেঙ"],
    ["cake", "à»§", "পেঙ"],
    ["cooking vegetables in a leaf", "à»¹", "পেন"],
    ["to stick up out of, like a stick out of water", "à»¹", "পেন"],
    ["plank of wood", "à»¹", "পেন"],
    ["to pick (a flower), to pluck", "å»µ", "পিত"],
    ["to kick with the back of the foot, as to kick a horse", "å»µ", "পিত"],
    ["duck", "å»µ", "পিত"],
    ["eight", "à»µ", "পেত"],
    ["gum, as gum of a tree, sap", "à»µ", "পেত"],
    ["to turn over, as the page of a book", "å»¹", "পিন"],
    ["to turn over the pages of a book", "å»¹ ¼Ø¹", "পিন ফুন"],
    ["to be, to become", "å»¹", "পিন"],
    ["to stimulate", "à»»", "পেপ"],
    ["to kiss", "å»Á", "পিম"],
    ["happy, joyful", "à»6", "পেউ"],
    ["to fly", "à»6", "পেউ"],
    ["to run very fast", "à»6", "পেউ"],
    ["flute", "»Õ", "পী"],
    ["a buffalo horn flute", "»Õ ¢ÒF ¢Òb", "পী খাও খাই"],
    ["a Tai flute", "»Õ µÒb", "পী তাই"],
    ["fat", "»Õ", "পী"],
    ["year", "»Õ", "পী"],
    ["last year", "»Õ ¡Òb", "পী কাই"],
    ["next year", "»Õ ¹Ò", "পী না"],
    ["this year", "»Õ ¹Òb", "পী নাই"],
    ["pen", "»Õ", "পী"],
    ["elder.sibling", "»Õ", "পী"],
    ["elder brother", "»Õ ¨Òb", "পী চাই"],
    ["elder brother-in-law", "»Õ ¨ÒF", "পী চাও"],
    ["elder sister", "»Õ ©ÒF", "পী ছাও"],
    ["relatives", "»Õ ¹§", "পী নঙ"],
    ["to plant", "»Ø¡", "পুক"],
    ["a paragraph", "»Ø¡", "পুক"],
    ["to wake", "»Ø¡", "পুক"],
    ["white ant", "»Ø¡", "পুক"],
    ["baggage", "»Ø¡", "পুক"],
    ["a story", "»Ø§", "পুঙ"],
    ["to push down, to keep down", "»Ø§", "পুঙ"],
    ["soft", "»Øb", "পুই"],
    ["to open", "»Øµ", "পুত"],
    ["to inherit", "»Øµ", "পুত"],
    ["to shoot (with a bow)", "»Øµ", "পুত"],
    ["to unbutton, to open a shirt button", "»Øµ ÁÒ¡ à©ä", "পুত মাক ছৌ"],
    ["gone away, past, over", "»Ø¹", "পুন"],
    ["grandfather", "»Ù", "পূ"],
    ["a crab", "»Ù", "পূ"],
    ["to cover, to spread", "»Ù", "পূ"],
    ["betel leaves", "»Ù", "পূ"],
    ["Brahma", "à» µÒ§", "পে তাঙ"],
    ["a type of tree", "à»", "পে"],
    ["a rafter along the long side of the house, a purlin", "à»", "পে"],
    ["to win", "à»", "পে"],
    ["to be able", "à»", "পে"],
    ["sheep", "à»", "পে"],
    ["a goat", "à» ÂÒ", "পে যা"],
    ["don't, a negative word", "»Òb", "পাই"],
    ["to go", "»Òb", "পাই"],
    ["to cut slightly", "»Òb", "পাই"],
    ["a match", "»Òb ¼Òb", "পাই ফাই"],
    ["top", "»Òb", "পাই"],
    ["top of the hand", "»Òb àÁä", "পাই মৌ"],
    ["the south", "»Òb ¨Ò¹", "পাই চান"],
    ["to worship", "»Òb", "পাই"],
    ["to go away", "»Òb", "পাই"],
    ["to be born (again)", "»", "প"],
    ["enough", "»", "প"],
    ["that is", "»", "প"],
    ["to kill", "»", "প"],
    ["to make", "»", "প"],
    ["father", "»", "প"],
    ["male", "»", "প"],
    ["father-in-law", "» ¨ÒF", "প চাও"],
    ["uncle", "» ¹Ò", "প না"],
    ["to cut down, as in to cut down a tree", "»ÒÁ", "পাম"],
    ["the belly", "»ØÁ", "পুম"],
    ["to puff up the cheeks", "»ØÁ", "পুম"],
    ["to make a heap, to heap up many things", "»ØÁ", "পুম"],
    ["to hide", "»Á", "পম"],
    ["the skin of fruits, peel", "à»ä¡", "পৌক"],
    ["to be puffed up", "à»ä§", "পৌঙ"],
    ["to govern", "à»ä§", "পৌঙ"],
    ["others, another person", "à»ä¹", "পৌন"],
    ["to cut from one side", "à»ä", "পৌ"],
    ["vacant", "»ÒF", "পাও"],
    ["to blow", "»ÒF", "পাও"],
    ["a type of tree", "»ÒF", "পাও"],
    ["a spot", "»ÒF", "পাও"],
    ["to call with a loud voice", "»ÒF", "পাও"],
    ["to peel", "»¡", "পক"],
    ["to come back, to return", "»¡", "পক"],
    ["a spot", "»§", "পঙ"],
    ["to accompany, to join with", "»§", "পঙ"],
    ["puffed up", "»§", "পঙ"],
    ["a joint of bamboo", "»§", "পঙ"],
    ["a lung", "»µ", "পত"],
    ["to clean", "»µ", "পত"],
    ["to feed", "»¹", "পন"],
    ["to keep watch", "»Òw", "পাঔ"],
    ["to release, to set free, to leave", "»b", "পই"],
    ["a festival", "»b", "পই"],
    ["beads", "»b", "পই"],
    ["pyaa¹ caaŋ4", "acgq", "»pÒ ¨Ò§", "ႃꩡ︀င︀်", "প্যা চাঙ"],
    ["pyaa²", "a", "»pÒ", "ႃ", "প্যা"],
    ["pyaa² cat¹", "actq", "»pÒ ¨Òµ", "ႃꩡ︀တ︀်", "প্যা চাত"],
    ["broken", "»ìÃÒ§", "প্ৰাঙ"],
    ["to slip down", "»ìÃÒµ", "প্ৰাত"],
    ["tug of war pulling", "»ìÃÒÁ", "প্ৰাম"],
    ["a vegetable", "¼Ò¡", "ফাক"],
    ["banana, as food", "¼Ò¡ ¡Øb", "ফাক কুই"],
    ["beans, as food", "¼Ò¡ ¶Ù", "ফাক থূ"],
    ["meat", "»Ò¡ à¹ä", "পাক নৌ"],
    ["food, diet. The word literally means vegetables and fish and refers to the food eaten by Tai people in a general sense.", "¼Ò¡ »Ò", "ফাক পা"],
    ["a condiment cooked with eggs", "¼Ò¡ ¢Òb", "ফাক খাই"],
    ["a sheath", "¼Ò¡", "ফাক"],
    ["to collect into a little heap", "¼Ò¡ ¼Òb", "ফাক ফাই"],
    ["to dig the earth", "¼Ò¡", "ফাক"],
    ["to send", "¼Ò¡", "ফাক"],
    ["to separate", "¼Ò¡", "ফাক"],
    ["flattened bamboo, used for flooring", "¼Ò¡", "ফাক"],
    ["the opposite bank of the river", "¼Ò¡", "ফাক"],
    ["placenta, given as :\"comes out with the new born animal\"", "¼Ò§ ¼Ò¡", "ফাঙ ফাক"],
    ["to bury", "¼Ò§", "ফাঙ"],
    ["to get stuck in the mud", "¼Ò§ àµä¡", "ফাঙ তৌক"],
    ["to be unable to go straight, given as \"go straight but cannot go\"", "¼Ò§ ¼Òb", "ফাঙ ফাই"],
    ["to pretend;to lie", "¼Ò§", "ফাঙ"],
    ["to be unable to see clearly", "¼Ò§", "ফাঙ"],
    ["to dash against, to collide with", "¼Ò§", "ফাঙ"],
    ["to read (aloud)", "¼Òµ", "ফাত"],
    ["to hit", "¼Òµ", "ফাত"],
    ["astringent in taste", "¼Òµ", "ফাত"],
    ["to cut", "¼Ò¹", "ফান"],
    ["caste, tribe, clan", "¼Ò¹", "ফান"],
    ["to fight with knives", "¼Ò¹ (¡Ò¹)", "ফান (কান)"],
    ["to twist, as in to twist strands into rope", "¼Ò¹", "ফান"],
    ["to peel", "¼Ò¹", "ফান"],
    ["a deer", "¼Ò¹", "ফান"],
    ["poor", "¼Ò¹", "ফান"],
    ["to split", "¼Ò", "ফা"],
    ["to saw wood", "¼Ò ÁÒb", "ফা মাই"],
    ["cloth", "¼Ò", "ফা"],
    ["purdah", "¼Ò ¡Ò§", "ফা কাঙ"],
    ["silk", "¼Ò ÁÒb", "ফা মাই"],
    ["a shawl, especially for women", "¼Ò ÁÒb", "ফা মাই"],
    ["sky", "¼Ò", "ফা"],
    ["cloud", "¼Ò", "ফা"],
    ["thunder", "¼Ò ¹Ò§ (·Ò§)", "ফা নাঙ (দাঙ)"],
    ["sunny", "¼Ò à¹µ (à·µ)", "ফা নেত (দেত)"],
    ["thunderbolt", "¼Ò ¼Ò", "ফা ফা"],
    ["rainy", "¼Ò ¼Ø¹", "ফা ফুন"],
    ["stormy", "¼Ò àÁ»", "ফা মেপ"],
    ["windy", "¼Ò ÅØÁ", "ফা লুম"],
    ["to promise", "¼Ò ¼Ò", "ফা ফা"],
    ["wall", "¼Ò", "ফা"],
    ["to invite", "å¼¡", "ফিক"],
    ["an operation in hospital", "à¼¡", "ফেক"],
    ["packet", "à¼¡", "ফেক"],
    ["a letter", "à¼¡ åÅ¡", "ফেক লিক"],
    ["to disturb", "à¼¡", "ফেক"],
    ["to be united, to be joined, given as \"same\"", "å¼§, à¼§", "ফিঙ, ফেঙ"],
    ["classifier for thin or flat things", "à¼¹", "ফেন"],
    ["wrong, mistake", "å¼µ", "ফিত"],
    ["chili taste", "å¼µ", "ফিত"],
    ["to make sugar by means of buffalo, not by using a crushing machine", "å¼¹", "ফিন"],
    ["to wink", "å¼»", "ফিপ"],
    ["to wink", "å¼» µÒ", "ফিপ তা"],
    ["to milk (a cow)", "å¼Á", "ফিম"],
    ["to miss by a little, as when shooting", "å¼6", "ফিউ"],
    ["to clear something away", "å¼6", "ফিউ"],
    ["to fidget", "å¼6", "ফিউ"],
    ["to sprinkle, as to sprinkle salt on rice", "å¼6", "ফিউ"],
    ["a god, a ghost, a spirit", "¼Õ", "ফী"],
    ["phii¹ saaŋ² khyɛŋ² / khɛŋ²", "igq", "¼Õ ©Ò§ à¢p§", "ိင︀်", "ফী ছাঙ খে্যঙ"],
    ["a forest spirit", "¼Õ à¶ä¹", "ফী থৌন"],
    ["a one-legged forest spirit", "¼Õ à¶ä¹ åµ¹ å¹6/å·6", "ফী থৌন তিন নিউ/দিউ"],
    ["a large forest spirit", "¼Õ à¶ä¹ ÅØ§", "ফী থৌন লুঙ"],
    ["a spirit that eats men without boiling or burning them", "¼Õ ¹Øµ / ·Øµ", "ফী নুত / দুত"],
    ["a red mouse spirit", "¼Õ ¹Ù à¹§ / à·§", "ফী নূ নেঙ / দেঙ"],
    ["a small mouse spirit", "¼Õ ¹Ù ÍÁ", "ফী নূ অম"],
    ["a water spirit", "¼Õ ¹ÒÁ", "ফী নাম"],
    ["a goat spirit", "¼Õ å»§ Ò", "ফী পিঙ া"],
    ["a type of spirit", "¼Õ »Ø¡", "ফী পুক"],
    ["a type of spirit", "¼Õ à¼µ ¨Ò", "ফী ফেত চা"],
    ["Agni, the fire god", "¼Õ ¼Òb", "ফী ফাই"],
    ["spirits of Ravana's caste, from the Ramayana", "¼Õ ¼Òb", "ফী ফাই"],
    ["a tree spirit", "¼Õ ÁÒb ËØ§", "ফী মাই হুঙ"],
    ["a black monkey spirit", "¼Õ ÅÒ ¡Ù", "ফী লা কূ"],
    ["a bad spirit", "¼Õ ËÒb", "ফী হাই"],
    ["to bind", "¼Ø¡", "ফুক"],
    ["a bamboo mat", "¼Ø¡", "ফুক"],
    ["to darn, to repair clothes", "¼Ø§", "ফুঙ"],
    ["a group, a crowd", "¼Ø§", "ফুঙ"],
    ["to spray around on all sides", "¼Ø§", "ফুঙ"],
    ["the edge of the house, the eaves", "¼Øb", "ফুই"],
    ["when water drops from the edge of the house in the early morning", "¼Øb ¢Ò", "ফুই খা"],
    ["to rise up", "¼Øµ (Í¡)", "ফুত (অক)"],
    ["to bubble as boiling water", "¼Øµ", "ফুত"],
    ["firewood", "¼Ø¹", "ফুন"],
    ["to roam", "¼Ø¹", "ফুন"],
    ["rain", "¼Ø¹", "ফুন"],
    ["classifier for books", "¼Ø¹", "ফুন"],
    ["a husband", "¼Ù", "ফূ"],
    ["to float", "¼Ù", "ফূ"],
    ["a male animal", "¼Ù", "ফূ"],
    ["to spread out", "à¼", "ফে"],
    ["broken", "à¼", "ফে"],
    ["to give birth", "à¼", "ফে"],
    ["fire", "¼Òb", "ফাই"],
    ["to knit", "¼Òb", "ফাই"],
    ["to row, as to row a boat", "¼Òb", "ফাই"],
    ["to walk", "¼Òb", "ফাই"],
    ["to cut on a slant", "¼Òb", "ফাই"],
    ["sharp", "¼Òb", "ফাই"],
    ["to make", "¼", "ফ"],
    ["to take out from the mouth", "¼", "ফ"],
    ["a kind of fever, causing men to grow fat", "¼", "ফ"],
    ["a type of disease, caused by caterpillar hairs", "¼ÒÁ", "ফাম"],
    ["a type of butterfly", "¼ÒÁ", "ফাম"],
    ["a part of the loom", "¼ØÁ", "ফুম"],
    ["hair of the head", "¼ØÁ", "ফুম"],
    ["to help", "¼Á", "ফম"],
    ["taro", "à¼ä¡", "ফৌক"],
    ["white", "à¼ä¡", "ফৌক"],
    ["the evil influence of planets", "à¼ä¡ » à¼ä¡ å¡6", "ফৌক প ফৌক কিউ"],
    ["bee", "à¼ä§", "ফৌঙ"],
    ["to stand up in support of some other thing", "à¼ä", "ফৌ"],
    ["the top part of a tree", "à¼ä", "ফৌ"],
    ["don't know", "¼ÒF", "ফাও"],
    ["to sprinkle", "¼¡", "ফক"],
    ["to unnecessarily waste something", "¼¡", "ফক"],
    ["wave", "¼§", "ফঙ"],
    ["to wrap", "¼µ", "ফত"],
    ["small", "¼¹", "ফন"],
    ["to run, of animals", "¼»", "ফপ"],
    ["who", "¼Òw", "ফাঔ"],
    ["to sing a tune", "¼b", "ফই"],
    ["a mole (on the body)", "¼b", "ফই"],
    ["to close the cover, such as of a box", "¼ìÃÒ»", "ফ্ৰাপ"],
    ["a type of disease, caused by caterpillar hairs", "¼ìÃÒÁ", "ফ্ৰাম"],
    ["taro", "à¼ìÃä¡", "ফে্ৰৗক"],
    ["to run, of animals", "¼ìÃ»", "ফ্ৰপ"],
    ["to cut", "ÁÒ¡", "মাক"],
    ["a shoulder", "ÁÒ¡ ÁÒ", "মাক মা"],
    ["fruit", "ÁÒ¡", "মাক"],
    ["Assamese apple", "ÁÒ¡ ¡Ò", "মাক কা"],
    ["a pineapple", "ÁÒ¡ å¡§", "মাক কিঙ"],
    ["trouser button", "ÁÒ¡ ¢Ø¹", "মাক খুন"],
    ["testicles", "ÁÒ¡ ¢ÒÁ", "মাক খাম"],
    ["Assamese grapes, a type of very bitter crab apple", "ÁÒ¡ ¢", "মাক খ"],
    ["testicles", "ÁÒ¡ ¢b", "মাক খই"],
    ["papaya", "ÁÒ¡ ©Ò§ ¼", "মাক ছাঙ ফ"],
    ["a button", "ÁÒ¡ à©ä", "মাক ছৌ"],
    ["a type of fruit", "ÁÒ¡ àµ§", "åÊÃÒ", "মাক তেঙ", "সিৰা"],
    ["jujube", "ÁÒË »Ò ¢ÒÁ", "মাহ পা খাম"],
    ["a kind of vegetable", "ÁÒ¡ »Ò ¨§ ¨§", "মাক পা চঙ চঙ"],
    ["a type of fruit", "ÁÒ¡ »Ò ¹Ò§ ¡§", "মাক পা নাঙ কঙ"],
    ["a type of fruit", "ÁÒ¡ »Ò ¹Ò§ å¹¹/å·¹", "মাক পা নাঙ নিন/দিন"],
    ["a fruit with a bitter taste; it is used to make medicine", "ÁÒ¡ »Ò ¹Ò", "মাক পা না"],
    ["the Ahom plum, smaller than a western plum", "ÁÒ¡ »Ò ÁØ¹", "মাক পা মুন"],
    ["a type of plum, the Nora plum", "ÁÒ¡ »Ò ÁÒF", "মাক পা মাও"],
    ["a jackfruit", "ÁÒ¡ »Ò ÅÒ§", "মাক পা লাঙ"],
    ["sour citrus fruits, such as lemon, lime", "ÁÒ¡ »Ò åÅ6", "মাক পা লিউ"],
    ["a fruit which causes stomach pains and diarrhoea", "ÁÒ¡ »Ò Åµ µ§", "মাক পা লত তঙ"],
    ["an orange", "ÁÒ¡ ÁÒ à§", "মাক মা ঙে"],
    ["a mango", "ÁÒ¡ ÁØ§", "মাক মুঙ"],
    ["a magic mango", "ÁÒ¡ ÁØ§ ÍÒÁ »Ò ÅÒ", "মাক মুঙ আম পা লা"],
    ["betel nut", "ÁÒ¡ ÁÙ", "মাক মূ"],
    ["a football", "ÁÒ¡ ¾Á", "মাক বম"],
    ["to be rich", "ÁÒ¡", "মাক"],
    ["to kill, to hit", "ÁÒ§", "মাঙ"],
    ["to fight", "ÁÒ§ ¡Ò¹", "মাঙ কান"],
    ["not quite dry, damp; used when clothes have been put out to dry but are not yet quite dry", "ÁÒ§", "মাঙ"],
    ["to stay in one place", "ÁÒ§ ÁØµ", "মাঙ মুত"],
    ["sometimes", "ÁÒ¡ »¡", "মাক পক"],
    ["some", "ÁÒ§ ¼§", "মাঙ ফঙ"],
    ["dog lice", "ÁÒµ (ÁÒ)", "মাত (মা)"],
    ["to remember", "ÁÒµ", "মাত"],
    ["to respect", "ÁÒµ", "মাত"],
    ["to aim", "ÁÒµ", "মাত"],
    ["potato, yam", "ÁÒ¹", "মান"],
    ["potato", "ÁÒ¹ ¡Ò ÅÒ", "মান কা লা"],
    ["a type of potato, literally \"potato-compete-man\"", "ÁÒ¹ å¢§ ¡Ø¹", "মান খিঙ কুন"],
    ["sweet potato", "ÁÒ¹ ©Ò§ ¼", "মান ছাঙ ফ"],
    ["a type of potato; its leaves are like five fingers", "ÁÒ¹ ÁÒb", "মান মাই"],
    ["a type of round potato", "ÁÒ¹ Í¹", "মান অন"],
    ["fertiliser", "ÁÒ¹ å¹¹/å·¹", "মান নিন/দিন"],
    ["lard, pig fat", "ÁÒ¹ ÁÙ", "মান মূ"],
    ["permanent", "ÁÒ¹", "মান"],
    ["glass", "ÁÒ¹", "মান"],
    ["lamp", "ÁÒ¹ b§", "মান ইঙ"],
    ["to be certain, given as \"his aim is good\"", "ÁÒ¹", "মান"],
    ["truly", "ÁÒ¹ ÁÒ¹", "মান মান"],
    ["magic", "ÁÒ¹ µÒ¹", "মান তান"],
    ["to become pregnant, to conceive", "ÁÒ¹", "মান"],
    ["a village", "ÁÒ¹", "মান"],
    ["the name of an Turung village, called Titabor in Assamese. It literally means \"ricefield village\".", "ÁÒ¹ ¹Ò", "মান না"],
    ["Burmese", "ÁÒ¹", "মান"],
    ["he, she, it", "ÁÒ¹", "মান"],
    ["not fully round or sperical; as when a sphere has a concave depression in it", "ÁÒ»", "মাপ"],
    ["yesterday", "ÁÒ §Ò", "মা ঙা"],
    ["the day before yesterday", "ÁÒ à©ä¹", "মা ছৌন"],
    ["today", "ÁÒ ¹Òb", "মা নাই"],
    ["tomorrow", "ÁÒ ËØ¡", "মা হুক"],
    ["the day after tomorrow", "ÁÒ àËä", "মা হৌ"],
    ["to overflow, to flow out", "ÁÒ", "মা"],
    ["a shoulder", "ÁÒ", "মা"],
    ["to come", "ÁÒ", "মা"],
    ["mad", "ÁÒ", "মা"],
    ["horse", "ÁÒ", "মা"],
    ["dog", "ÁÒ", "মা"],
    ["to carry on the shoulder", "àÁ¡", "মেক"],
    ["to divide", "àÁ§", "মেঙ"],
    ["insect", "àÁ§", "মেঙ"],
    ["a firefly", "àÁ§ à¡§", "মেঙ কেঙ"],
    ["a type of cicada; it's sound is kɔ1 wjN².", "àÁ§ ¡ àÇ§", "মেঙ ক ৱেঙ"],
    ["a type of long worm, a millipede", "àÁ§ ¢Ò", "মেঙ খা"],
    ["a firefly", "àÁ§ å¢§", "মেঙ খিঙ"],
    ["a type of flying insect which touches the water; a dragonfly", "àÁ§ ¨Òb ¹ÒÁ", "মেঙ চাই নাম"],
    ["a type of insect, which makes the sound cɔ³ cj³ when touched.", "àÁ§ ¨ à¨", "মেঙ চ চে"],
    ["a type of insect", "àÁ§ ©Ò¡ ©¹", "মেঙ ছাক ছন"],
    ["a cockroach", "àÁ§ ©Ò»", "মেঙ ছাপ"],
    ["a type of fly which hovers about the eyes of people", "àÁ§ µÁ µÒ", "মেঙ তম তা"],
    ["a kind of centipede. It rolls up when touched.", "àÁ§ µ§ µb", "মেঙ তঙ তই"],
    ["a tick, a little ant", "àÁ§ à¹§/à·§", "মেঙ নেঙ/দেঙ"],
    ["a type of insect", "àÁ§ ¹ÒÁ", "মেঙ নাম"],
    ["a butterfly", "àÁ§ ÁÕ/¾Õ", "মেঙ মী/বী"],
    ["a dung beetle. It lives in cow dung.", "àÁ§ ÁØµ ¢Øb ¢Õ", "মেঙ মুত খুই খী"],
    ["a housefly", "àÁ§ ÁØ¹", "মেঙ মুন"],
    ["a termite. It comes out of its mound in the evening.", "àÁ§ ÁÒF", "মেঙ মাও"],
    ["to be destroyed; given as \"teeth are broken and black\"", "àÁ§", "মেঙ"],
    ["protruding", "àÁ¹", "মেন"],
    ["a porcupine", "àÁ¹", "মেন"],
    ["to twist", "åÁµ", "মিত"],
    ["too many twists", "åÁµ àÁä§", "মিত মৌঙ"],
    ["nose", "åÁµ åÅ6 àÅ§", "মিত লিউ লেঙ"],
    ["a knife", "åÁµ", "মিত"],
    ["a fishhook", "åÁµ", "মিত"],
    ["body lice", "åÁ¹", "মিন"],
    ["chipped", "åÁ¹", "মিন"],
    ["stinking, bad smell", "åÁ¹", "মিন"],
    ["to fly", "åÁ¹", "মিন"],
    ["to squeeze", "àÁ»", "মেপ"],
    ["to draw water out from a tube well", "àÁ»", "মেপ"],
    ["lightning", "àÁ»", "মেপ"],
    ["to evacuate a little from the bowels", "àÁ»", "মেপ"],
    ["caste, race", "åÁ6", "মিউ"],
    ["a cat", "àÁ6", "মেউ"],
    ["to have", "ÁÕ", "মী"],
    ["to be rich", "ÁÕ", "মী"],
    ["a wife", "ÁÕ", "মী"],
    ["charcoal", "ÁÕ", "মী"],
    ["very black colour", "ÁÕ", "মী"],
    ["a bear", "ÁÕ", "মী"],
    ["dirty", "ÁØ¡", "àÅàµÃÒ", "মুক", "লেতেৰা"],
    ["a thinking man", "ÁØ¡ µÒF ©ÒF ¢Õ", "মুক তাও ছাও খী"],
    ["a group", "ÁØ¡", "মুক"],
    ["a hunter", "ÁØ¡ à©ä", "মুক ছৌ"],
    ["to cover with earth or powder, to bury", "ÁØ¡", "মুক"],
    ["a pipe or other receptacle for carrying water and fish", "ÁØ§", "মুঙ"],
    ["to make a roof", "ÁØ§", "মুঙ"],
    ["allergy", "ÁØ§", "মুঙ"],
    ["to expect, to wait for", "ÁØ§", "মুঙ"],
    ["to look out and wonder whether somebody is coming", "ÁØ§ ¹Ù/·Ù", "মুঙ নূ/দূ"],
    ["a kind of dipper, made from a coconut shell", "ÁØb", "মুই"],
    ["a type of tree", "ÁØb", "মুই"],
    ["to be dead on one side, such as a tree", "ÁØb", "মুই"],
    ["fog, snow", "ÁØb", "মুই"],
    ["finished up", "ÁØµ", "মুত"],
    ["an ant", "ÁØµ", "মুত"],
    ["powder covering the body", "ÁØ¹", "মুন"],
    ["hives, allergy", "ÁØ¹ ÁÒ¹", "মুন মান"],
    ["dust", "ÁØ¹ å¹¹/å·¹", "মুন নিন/দিন"],
    ["glass powder", "ÁØ¹ ÁÒ¹", "মুন মান"],
    ["slippery", "ÁØ¹", "মুন"],
    ["glory", "ÁØ¹", "মুন"],
    ["to burrow", "ÁØ¹", "মুন"],
    ["to hit", "ÁØ»", "মুপ"],
    ["a hat", "ÁØ»", "মুপ"],
    ["stagnant water", "ÁØ»", "মুপ"],
    ["to hem a garment", "ÁØ»", "মুপ"],
    ["a lotus", "ÁÙ", "মূ"],
    ["to be dizzy, to be drunk", "ÁÙ", "মূ"],
    ["to become fat and healthy, used for babies", "ÁÙ", "মূ"],
    ["a pig, a hog", "ÁÙ", "মূ"],
    ["more than", "àÁ", "মে"],
    ["to repair", "àÁ", "মে"],
    ["mother", "àÁ", "মে"],
    ["an exclamation, \"let go\"", "àÁ", "মে"],
    ["to cover with a shawl, to cover with cloth", "ÁÒb", "মাই"],
    ["to trouble, to cause trouble", "ÁÒb", "মাই"],
    ["to burn", "ÁÒb", "মাই"],
    ["wood", "ÁÒb", "মাই"],
    ["tree", "ÁÒb", "মাই"],
    ["thread", "ÁÒb", "মাই"],
    ["a widow, a widower", "ÁÒb", "মাই"],
    ["slanted, not straight, not at 90 degrees", "ÁÒb", "মাই"],
    ["to enamour", "ÁÒb", "মাই"],
    ["to be disturbing, to be noisy", "Á", "ম"],
    ["a pot", "Á", "ম"],
    ["to sing, to recite poetry", "Á", "ম"],
    ["food for a baby", "ÁÒÁ", "মাম"],
    ["to bind with medicine, to bind a poltice", "ÁÒÁ", "মাম"],
    ["a muscle", "ÁÒÁ", "মাম"],
    ["to ripen", "ÁØÁ", "মুম"],
    ["to congeal, given as \"The water comes and stays in one place; when we kill, the blood is come and stays at one place\"", "ÁØÁ", "à¤Ò¯ à¢ÒÇÒ", "মুম", "গোট খোৱা"],
    ["to congeal, given as \"When our body is cut, then the water comes and stays in one place\"", "ÁØÁ ¹§", "মুম নঙ"],
    ["loose", "ÁØÁ", "মুম"],
    ["to top of the head, the crown of the head", "ÁÁ", "মম"],
    ["ink", "àÁä¡", "মৌক"],
    ["foolish", "àÁä¡", "মৌক"],
    ["a country", "àÁä§", "মৌঙ"],
    ["the earth, the world", "àÁä§ ¡Ò§", "মৌঙ কাঙ"],
    ["the earth, the world", "àÁä§ ¡Ø¹", "মৌঙ কুন"],
    ["China", "àÁä§ à¢", "মৌঙ খে"],
    ["Burma", "àÁä§ ÁÒ¹", "মৌঙ মান"],
    ["a mythical country, Muang Hi Ham", "àÁä§ ËÕ ËÒÁ", "মৌঙ হী হাম"],
    ["to be reticent to speak, given as \"He does bad work and I cannot say anything to him. I cannot speak to him face to face. This is m&N³.\"", "àÁä§", "মৌঙ"],
    ["a piece of broken pot, a potsherd", "àÁä§", "মৌঙ"],
    ["he, she, it", "àÁä¹", "মৌন"],
    ["a hand", "àÁä", "মৌ"],
    ["bored", "àÁä", "মৌ"],
    ["very bored", "àÁä àÁä åÁ¹ åÁ¹", "মৌ মৌ মিন মিন"],
    ["time", "àÁä", "মৌ"],
    ["then", "àÁä ¹Ò¹", "মৌ নান"],
    ["when", "àÁä ¹Òw", "মৌ নাঔ"],
    ["not, a particle used to negate a sentence", "ÁÒF", "মাও"],
    ["light, not heavy", "ÁÒF", "মাও"],
    ["to jump up out of the water, used of fish", "ÁÒF", "মাও"],
    ["a powdery cake made from rice", "ÁÒF", "মাও"],
    ["young man", "ÁÒF", "মাও"],
    ["a pipe, a tube", "Á¡", "মক"],
    ["a flower", "Á¡", "মক"],
    ["to tell", "Á¡", "মক"],
    ["the sky, clouds", "Á¡", "মক"],
    ["to bore, to pierce", "Á§", "মঙ"],
    ["to preserve meat, vegetables or fruit; to make jam", "Á§", "মঙ"],
    ["to be successful in wooing, to win a wife", "Á§", "মঙ"],
    ["dim, dark", "Á§", "মঙ"],
    ["blind", "Áµ", "মত"],
    ["to extinguish a fire, to put out a fire", "Áµ", "মত"],
    ["a weevil, a small insect that eats wood and paper", "Áµ", "মত"],
    ["to put under", "Á¹", "মন"],
    ["a silkworm", "Á¹", "মন"],
    ["to be happy, to be contented", "Á¹", "মন"],
    ["a pillow", "Á¹ ËÙ", "মন হূ"],
    ["broken, cracked", "Á»", "মপ"],
    ["new", "ÁÒw", "মাঔ"],
    ["you, the second person singular pronoun", "ÁÒw", "মাঔ"],
    ["leaf", "ÁÒw", "মাঔ"],
    ["pan leaf", "ÁÒw »Ù", "মাঔ পূ"],
    ["foolish, given as \"He sees but he does not know what he sees.\"", "ÁÒw", "মাঔ"],
    ["tired", "Áb", "মই"],
    ["hair on the private parts, pubic hair", "Áb", "মই"],
    ["to cut", "¾Ò¡", "বাক"],
    ["a shoulder", "¾Ò¡ ¾Ò", "বাক বা"],
    ["a village", "¾Ò¹", "বান"],
    ["the name of an Turung village, called Titabor in Assamese. It literally means \"ricefield village\".", "¾Ò¹ ¹Ò", "বান না"],
    ["to overflow, to flow out", "¾Ò", "বা"],
    ["a shoulder", "¾Ò", "বা"],
    ["mad", "¾Ò", "বা"],
    ["to carry on the shoulder", "à¾¡", "বেক"],
    ["to divide", "à¾§", "বেঙ"],
    ["to twist", "å¾µ", "বিত"],
    ["too many twists", "å¾µ à¾ä§", "বিত বৌঙ"],
    ["nose", "å¾µ åÅ6 àÅ§", "বিত লিউ লেঙ"],
    ["a fishhook", "å¾µ", "বিত"],
    ["chipped", "å¾¹", "বিন"],
    ["to fly", "å¾¹", "বিন"],
    ["to draw water out from a tube well", "à¾»", "বেপ"],
    ["a kind of dipper, made from a coconut shell", "ÁØb", "মুই"],
    ["to hit", "¾Ø»", "বুপ"],
    ["stagnant water", "¾Ø»", "বুপ"],
    ["to become fat and healthy, used for babies", "¾Ù", "বূ"],
    ["an exclamation, \"let go\"", "à¾", "বে"],
    ["to cover with a shawl, to cover with cloth", "¾Òb", "বাই"],
    ["slanted, not straight, not at 90 degrees", "¾Òb", "বাই"],
    ["to congeal, given as \"The water comes and stays in one place; when we kill, the blood is come and stays at one place\"", "¾ØÁ", "à¤Ò¯ à¢ÒÇÒ", "বুম", "গোট খোৱা"],
    ["to congeal, given as \"When our body is cut, then the water comes and stays in one place\"", "¾ØÁ ¹§", "বুম নঙ"],
    ["loose", "¾ØÁ", "বুম"],
    ["a piece of broken pot, a potsherd", "à¾ä§", "বৌঙ"],
    ["bored", "à¾ä", "বৌ"],
    ["light, not heavy", "¾ÒF", "বাও"],
    ["young man", "ÁÒF", "মাও"],
    ["a pipe, a tube", "¾¡", "বক"],
    ["a flower", "¾¡", "বক"],
    ["to bore, to pierce", "¾§", "বঙ"],
    ["to preserve meat, vegetables or fruit; to make jam", "¾§", "বঙ"],
    ["blind", "¾µ", "বত"],
    ["broken, cracked", "¾»", "বপ"],
    ["leaf", "¾Òw", "বাঔ"],
    ["foolish, given as \"He sees but he does not know what he sees.\"", "¾Òw", "বাঔ"],
    ["pan leaf", "¾Òw »Ù", "বাঔ পূ"],
    ["to cut again and again", "ÂÒ¡", "যাক"],
    ["to take two leaves of the tea plant", "ÂÒ¡", "যাক"],
    ["pain", "ÂÒ¡", "যাক"],
    ["to show", "ÂÒ§", "যাঙ"],
    ["is, have", "ÂÒ§", "যাঙ"],
    ["gum", "ÂÒ§", "যাঙ"],
    ["to dry with smoke", "ÂÒ§", "যাঙ"],
    ["to step (in meditation)", "ÂÒ§", "যাঙ"],
    ["to make longer", "ÂÒ¹", "যান"],
    ["to stretch out the legs", "ÂÒ¹", "যান"],
    ["a line", "ÂÒ¹", "ÈÒÃÕ", "যান", "শাৰী"],
    ["separate", "ÂÒ¹", "যান"],
    ["to sew", "ÂÒ»", "যাপ"],
    ["difficult", "ÂÒ»", "যাপ"],
    ["to cure, to mend, to make good", "ÂÒ", "যা"],
    ["to shoo away (birds)", "ÂÒ", "যা"],
    ["medicine", "ÂÒ", "যা"],
    ["mosquito medicine }", "ÂÒ ÂØ§", "যা যুঙ"],
    ["tobacco", "ÂÒ 6Á", "যা উম"],
    ["grass", "ÂÒ", "যা"],
    ["many grasses", "ÂÒ ÂÒ ÂÒ» ÂÒ»", "যা যা যাপ যাপ"],
    ["a type of tree", "ÂÒ ÅØ§", "যা লুঙ"],
    ["grandmother", "ÂÒ", "যা"],
    ["woman", "åÂ§", "যিঙ"],
    ["to spin (thread)", "åÂµ", "যিত"],
    ["cold, cool, used of food and water", "åÂ¹", "যিন"],
    ["to stamp, to tread", "åÂ»", "যিপ"],
    ["to look repeatedly, given as \"to see who is coming\", to peep", "ªØåÁ à¨ÒÇÒ", "জুমি চোৱা"],
    ["urine", "åÂ6", "যিউ"],
    ["to raise up", "ÂØ¡", "যুক"],
    ["mosquito", "ÂØ§", "যুঙ"],
    ["tangled", "ÂØ§", "যুঙ"],
    ["tangled", "ÂØ§", "যুঙ"],
    ["very excited and very distressed", "ÂØ§ ÂÒ§ (¡Ò¹)", "যুঙ যাঙ (কান)"],
    ["to pick up with the five fingers", "ÂØ»", "যুপ"],
    ["offering, given as \"last prayer to God\"", "àÂ ¨Ò¡", "যে চাক"],
    ["a granary, a store", "ÂÕ", "যী"],
    ["a bank", "ÂÕ à§ä¹", "যী ঙৌন"],
    ["a library", "ÂÕ »Ò»", "যী পাপ"],
    ["to make fit", "ÂÒb", "যাই"],
    ["to remind", "ÂÒb", "যাই"],
    ["to melt", "ÂÒb", "যাই"],
    ["congratulations", "Â", "য"],
    ["not sharp", "Â", "য"],
    ["to go back", "Â", "য"],
    ["loose, to loosen", "Â", "å²ÅÒ", "য", "ঢিলা"],
    ["to be wet", "ÂÒÁ", "যাম"],
    ["to aim well", "ÂÒÁ", "যাম"],
    ["to chew", "ÂÒÁ", "যাম"],
    ["to believe", "ÂØÁ", "যুম"],
    ["a tree with so many branches and leaves", "ÂØÁ", "যুম"],
    ["trees and grasses, a little jungle", "ÂØÁ ÂÒ", "যুম যা"],
    ["a type of caterpillar", "ÂÁ", "যম"],
    ["to decrease, to get less", "ÂÁ", "যম"],
    ["thin", "ÂÁ", "যম"],
    ["damp", "àÂä¡", "যৌক"],
    ["to follow, to imitate", "àÂä§", "যৌঙ"],
    ["like, as", "àÂä§", "যৌঙ"],
    ["when we sing", "àÂäµ", "যৌত"],
    ["to hand over", "àÂä¹", "যৌন"],
    ["cold, cool, used of food and water", "àÂä¹", "যৌন"],
    ["silence, given as \"not any sound there\"", "àÂä¹", "যৌন"],
    ["flattened grass", "àÂä»", "যৌপ"],
    ["to borrow", "àÂäÁ", "যৌম"],
    ["to shoot", "àÂä", "যৌ"],
    ["food for birds, prey", "àÂä", "যৌ"],
    ["a word denoting that an action is completed. Given in Assamese as \"was\"", "ÂÒF", "àËÒÇÒ", "যাও", "হোৱা"],
    ["and next", "ÂÒF ÇÒb", "যাও ৱাই"],
    ["long", "ÂÒF", "যাও"],
    ["a joke", "Â¡", "যক"],
    ["to pierce", "Â¡", "যক"],
    ["to pick up", "Â§", "যঙ"],
    ["a piece", "Â§", "যঙ"],
    ["to press with the foot", "Â§ åÂ»", "যঙ যিপ"],
    ["to praise", "Â§ Â§ Â Â", "যঙ যঙ য য"],
    ["to drop, to fall down drop by drop", "Âµ", "যত"],
    ["the youngest part of a tree, a new shoot", "Âµ", "যত"],
    ["to walk backwards", "Â¹", "যন"],
    ["to ask for, to beg", "Â¹", "যন"],
    ["alas, to regret", "Â¹", "যন"],
    ["to move up and down quickly", "Â»", "যপ"],
    ["big", "ÂÒw", "যাঔ"],
    ["web, spider's web", "ÂÒw", "যাঔ"],
    ["hanging", "Âb", "যই"],
    ["to break", "ÃÒ¡", "ৰাক"],
    ["a nest", "ÃÒ§", "ৰাঙ"],
    ["dirty", "¾Ò§", "বাঙ"],
    ["to hate", "ÃÒ§", "ৰাঙ"],
    ["an item of clothing worn by women across the middle of the waist", "ËÒ§", "হাঙ"],
    ["fast flowing", "ÃÒµ", "ৰাত"],
    ["to be half-boiled", "ÃÒµ", "ৰাত"],
    ["to be undeveloped, said of fruits which are not fully developed, such as mangoes out of season.", "ÃÒµ", "ৰাত"],
    ["jealous", "ÃÒ¹", "ৰান"],
    ["an enemy", "ÃÒ¹ ©Ù", "ৰান ছূ"],
    ["to stay for a short time", "ÃÒ»", "ৰাপ"],
    ["to be disobedient, given as: 'I told him not to write, and still he does, this is called raa².'", "ÃÒ", "ৰা"],
    ["to call", "åÃ¡", "ৰিক"],
    ["naughty", "àÃ§", "ৰেঙ"],
    ["naughty", "àÃ§ àÃ§ à¡§ à¡§", "ৰেঙ ৰেঙ কেঙ কেঙ"],
    ["smallish, shortish, used to describe a man", "àÃ§", "ৰেঙ"],
    ["to eat greedily, to be greedy", "åÃµ", "ৰিত"],
    ["the sound of fire or air", "åÃ6", "ৰিউ"],
    ["naughty", "åÃ6", "ৰিউ"],
    ["to send somebody away, given as 'Say to somebody, go away!'", "ÃÒÁ", "ৰাম"],
    ["greedy", "ÃÒÁ ÁÒ¡", "ৰাম মাক"],
    ["sloping", "àÃä¡", "ৰৌক"],
    ["naughty", "àÃä§", "ৰৌঙ"],
    ["a lance", "Ã¡", "ৰক"],
    ["a post", "ÅÒ¡", "লাক"],
    ["to steal", "ÅÒ¡", "লাক"],
    ["the back", "ÅÒ§", "লাঙ"],
    ["to walk", "ÅÒ§", "লাঙ"],
    ["to burn", "ÅÒ§", "লাঙ"],
    ["to wash", "ÅÒ§", "লাঙ"],
    ["the ground under the house", "ÅÒ§", "লাঙ"],
    ["an expert", "ÅÒµ", "লাত"],
    ["to fall down one step", "ÅÒ¹", "লান"],
    ["classifier for the pages of book", "ÅÒ¹", "লান"],
    ["a grandchild of either sex, a nephew or a niece", "ÅÒ¹", "লান"],
    ["a grandson-in-law", "ÅÒ¹ ¢Øb", "লান খুই"],
    ["grandson or nephew", "ÅÒ¹ ¨Òb", "লান চাই"],
    ["a granddaughter-in-law", "ÅÒ¹ »Òw", "লান পাঔ"],
    ["to sharpen a knife or a stone", "ÅÒ»", "লাপ"],
    ["to hide", "ÅÒ»", "লাপ"],
    ["to be afraid, to be frightened", "ÅÒ»", "লাপ"],
    ["a donkey", "ÅÒ", "লা"],
    ["to want", "ÅÒ", "লা"],
    ["late, late in the morning", "ÅÒ", "লা"],
    ["child", "ÅÒ ¢Ò", "লা খা"],
    ["a book", "åÅ¡", "লিক"],
    ["iron", "àÅ¡", "লেক"],
    ["small", "àÅ¡", "লেক"],
    ["a monkey", "åÅ§", "লিঙ"],
    ["to feed", "åÅ§", "লিঙ"],
    ["to bind", "àÅ§", "লেঙ"],
    ["light", "àÅ§", "লেঙ"],
    ["a vehicle", "àÅ§", "লেঙ"],
    ["a train", "àÅ§ ¼Òb", "লেঙ ফাই"],
    ["an aeroplane", "àÅ§ åÁ¹/å¾¹", "লেঙ মিন/বিন"],
    ["a bicycle", "àÅ§ åÅ6", "লেঙ লিউ"],
    ["to run", "àÅ¹", "লেন"],
    ["to eat greedily, to be greedy", "åÅµ", "লিত"],
    ["the tongue", "åÅ¹", "লিন"],
    ["great-grandchild", "åÅ¹", "লিন"],
    ["a type of squirrel, a small animal coloured green and red", "åÅ¹", "লিন"],
    ["to play", "åÅ¹", "লিন"],
    ["a fingernail or toenail, used of animals", "åÅ»", "লিপ"],
    ["to go around the edge of something", "åÅ»", "লিপ"],
    ["to look", "àÅÁ", "লেম"],
    ["an arrow", "àÅÁ", "লেম"],
    ["clever", "àÅÁ", "লেম"],
    ["a finger", "åÅ6", "লিউ"],
    ["to twist", "åÅ6", "লিউ"],
    ["the top of a tree, such as the top of the banana or the coconut", "ÅÕ", "লী"],
    ["bile, given as \"internal organ\"", "ÅÕ", "লী"],
    ["long", "ÅÕ", "লী"],
    ["to get up, to rise", "ÅØ¡", "লুক"],
    ["to get up and sit", "ÅØ¡ ¹Ò§", "লুক নাঙ"],
    ["to get up late", "ÅØ¡ ÅÒ", "লুক লা"],
    ["from", "ÅØ¡", "লুক"],
    ["a child", "ÅØ¡", "লুক"],
    ["a son-in-law", "ÅØ¡ ¢Øb", "লুক খুই"],
    ["a son", "ÅØ¡ ¨Òb", "লুক চাই"],
    ["a daughter", "ÅØ¡ ©ÒF", "লুক ছাও"],
    ["a daughter-in-law", "ÅØ¡ »Òw", "লুক পাঔ"],
    ["an elder uncle", "ÅØ§", "লুঙ"],
    ["sister's husband", "ÅØ§ µÒ", "লুঙ তা"],
    ["to go down", "ÅØ§", "লুঙ"],
    ["sloping", "ÅØ§ Å", "লুঙ ল"],
    ["big, large", "ÅØ§", "লুঙ"],
    ["very big", "ÅØ§ ÅØ§", "লুঙ লুঙ"],
    ["straight, such as of a dog's tail, and opposed to haaN1 kɔN1 \"curly tail\".", "ÅØb", "লুই"],
    ["with", "ÅØb", "লুই"],
    ["to slip off", "ÅØµ", "লুত"],
    ["to fall down, such as when a flower drops", "ÅØ¹", "লুন"],
    ["to cover a second time, to cover again", "ÅØ»", "লুপ"],
    ["to donate", "ÅÙ", "লূ"],
    ["to leave the monkhood, to disrobe", "ÅÙ ¶Ò¡", "লূ থাক"],
    ["a sister-in-law", "ÅÙ", "লূ"],
    ["damaged", "ÅÙ", "লূ"],
    ["to lick", "àÅ", "লে"],
    ["to roam", "àÅ", "লে"],
    ["to push away, used of animals", "ÅÒb", "লাই"],
    ["to flow", "ÅÒb", "লাই"],
    ["a pattern", "ÅÒb", "লাই"],
    ["saliva", "ÅÒb", "লাই"],
    ["to change", "ÅÒb", "লাই"],
    ["many, so many", "ÅÒb", "লাই"],
    ["to pour water", "Å", "ল"],
    ["to come forward to fight", "Å", "ল"],
    ["CLF.-long.things", "ÅÒÁ", "লাম"],
    ["to spread, of a fire", "ÅÒÁ", "লাম"],
    ["a bamboo pipe for cooking sticky rice in", "ÅÒÁ", "লাম"],
    ["wind", "ÅØÁ", "লুম"],
    ["to fall down", "ÅØÁ", "লুম"],
    ["to surround, to fence", "ÅÁ", "লম"],
    ["deep", "àÅä¡", "লৌক"],
    ["a kind of fly which bites like a mosquito, a gadfly", "àÅä¡ ÅÒb", "লৌক লাই"],
    ["to choose", "àÅä¡", "লৌক"],
    ["one", "àÅä§", "লৌঙ"],
    ["yellow", "àÅä§", "লৌঙ"],
    ["blood", "àÅäµ", "লৌত"],
    ["to run", "àÅä¹", "লৌন"],
    ["a bundle", "àÅä»", "লৌপ"],
    ["to love someone outside of marriage, given as \"to have one wife and love another\"", "àÅäÁ", "লৌম"],
    ["to forget", "àÅäÁ", "লৌম"],
    ["to rest", "àÅä", "লৌ"],
    ["a great great grandparent", "àÅä", "লৌ"],
    ["to saw crosswise, to cut crosswise", "àÅä", "লৌ"],
    ["too much, excessive", "àÅä", "লৌ"],
    ["to soothe a baby", "ÅÒF", "লাও"],
    ["liquor, alcohol", "ÅÒF", "লাও"],
    ["to tell", "ÅÒF", "লাও"],
    ["a post", "ÅÒF", "লাও"],
    ["to frighten", "Å¡", "লক"],
    ["to skin, to peel", "Å¡", "লক"],
    ["to flow downstream", "Å§", "লঙ"],
    ["line", "Å§", "লঙ"],
    ["short", "Åµ", "লত"],
    ["to insert", "Åµ", "লত"],
    ["to throw", "Å¹", "লন"],
    ["a great great great grandparent", "Å¹", "লন"],
    ["not fully dreaming; to appear to be awake whilst actually sleeping, to talk in one's sleep", "ÅÒw", "লাঔ"],
    ["slow", "Åb", "লই"],
    ["to swim", "Åb", "লই"],
    ["to row", "ÇÒ¡", "ৱাক"],
    ["to scratch", "ÇÒ¡", "ৱাক"],
    ["wax, gum", "ÇÒ¡", "ৱাক"],
    ["Assamese incense stick", "ÇÒ¡", "ৱাক"],
    ["to be surprised, to be confused", "ÇÒ§", "ৱাঙ"],
    ["to be surprised", "ÇÒ§ åÇ§", "ৱাঙ ৱিঙ"],
    ["compound", "ÇÒ§", "ৱাঙ"],
    ["compound around a house", "ÇÒ§ àËä¹", "ৱাঙ হৌন"],
    ["in between", "ÇÒ§", "ৱাঙ"],
    ["a temple", "ÇÒµ", "ৱাত"],
    ["the sun", "ÇÒ¹", "ৱান"],
    ["a day", "ÇÒ¹", "ৱান"],
    ["bowl", "ÇÒ¹", "ৱান"],
    ["classifier for the capacity of a bowl", "ÇÒ¹", "ৱান"],
    ["straw", "ÇÒ¹", "ৱান"],
    ["sweet", "ÇÒ¹", "ৱান"],
    ["misshapen, given as 'not fully round (of a fruit or similar object)'", "ÇÒ»", "ৱাপ"],
    ["a bunch", "ÇÒ", "ৱা"],
    ["a bunch of betel nuts", "ÇÒ ¾¡", "ৱা বক"],
    ["the Buddhist rains retreat", "ÇÒ", "ৱা"],
    ["to say, to speak", "ÇÒ", "ৱা"],
    ["a fence", "åÇ§", "ৱিঙ"],
    ["to throw", "àÇ§", "ৱেঙ"],
    ["to hope", "àÇ§", "ৱেঙ"],
    ["to leave", "åÇ¹", "ৱিন"],
    ["to jump", "àÇ¹", "ৱেন"],
    ["a bangle", "àÇ¹", "ৱেন"],
    ["to scoop", "åÇµ", "ৱিত"],
    ["to clear bamboo or wood", "åÇµ", "ৱিত"],
    ["to turn", "åÇ¹", "ৱিন"],
    ["puncture", "àÇ»", "ৱেপ"],
    ["a fan", "ÇÕ", "ৱী"],
    ["a comb", "ÇÕ", "ৱী"],
    ["a hand of bananas", "ÇÕ", "ৱী"],
    ["to burst out into flames", "ÇØ¡", "ৱুক"],
    ["to bless", "ÇØb", "ৱুই"],
    ["bad luck; bad fate", "ÇØµ", "ৱুত"],
    ["to pull back a bow in preparation for shooting an arrow", "ÇØµ", "ৱুত"],
    ["an otter", "ÇØ¹", "ৱুন"],
    ["oxen, cattle", "ÇÙ", "ৱূ"],
    ["to go to one side", "àÇ", "ৱে"],
    ["to put aside", "àÇ", "ৱে"],
    ["to put, to keep", "ÇÒb", "ৱাই"],
    ["to shake", "ÇÒb", "ৱাই"],
    ["to turn from side to side", "ÇÒb", "ৱাই"],
    ["to be finished", "ÇÒb", "ৱাই"],
    ["rattan", "ÇÒb", "ৱাই"],
    ["to catch, to snatch", "ÇÒÁ", "ৱাম"],
    ["a valley", "ÇÒF ·¿", "ৱাও দয়"],
    ["the early morning light", "ÇÒF àÅ§", "ৱাও লেঙ"],
    ["not to be able to see clearly", "ÇÒF", "ৱাও"],
    ["a ruler; a king", "Ç§", "ৱঙ"],
    ["accompanied with", "Ç¹", "ৱন"],
    ["to break", "ËÒ¡", "হাক"],
    ["to love", "ËÒ¡", "হাক"],
    ["colour", "ËÒ¡", "হাক"],
    ["vomit", "ËÒ¡", "হাক"],
    ["a root", "ËÒ¡", "হাক"],
    ["nest, hive", "ËÒ§", "হাঙ"],
    ["dirty", "ËÒ§", "হাঙ"],
    ["to hate", "ËÒ§", "হাঙ"],
    ["wide apart", "ËÒ§", "হাঙ"],
    ["up, upwards", "ËÒ§", "হাঙ"],
    ["to need, to want", "ËÒ§", "হাঙ"],
    ["a picture", "ËÒ§", "হাঙ"],
    ["the tail", "ËÒ§", "হাঙ"],
    ["selfish", "ËÒµ", "হাত"],
    ["to tie", "ËÒµ", "হাত"],
    ["food spoiled by dust, given as \"so much dust in the eaten things\".", "ËÒµ", "হাত"],
    ["to see", "ËÒ¹", "হান"],
    ["a goose", "ËÒ¹", "হান"],
    ["gaps in the wall", "ËÒ¹", "হান"],
    ["lame", "ËÒ¹", "হান"],
    ["a step", "ËÒ¹", "হান"],
    ["brave", "ËÒ¹", "হান"],
    ["to shut", "ËÒ»", "হাপ"],
    ["to welcome", "ËÒ»", "হাপ"],
    ["to catch", "ËÒ»", "হাপ"],
    ["to carry on the shoulder by using a long stick, the load being suspended from both ends", "ËÒ»", "হাপ"],
    ["the sound of rain; when rain is heard, the word haa1 is used.", "ËÒ", "হা"],
    ["to sigh, to breathe out", "ËÒ", "হা"],
    ["body gas", "ËÒ", "হা"],
    ["five", "ËÒ", "হা"],
    ["a fever", "ËÒ", "হা"],
    ["aluminium", "åË¡", "হিক"],
    ["to call", "åË¡", "হিক"],
    ["to punch", "åË§", "হিঙ"],
    ["one thousand", "åË§", "হিঙ"],
    ["one thousand five hundred", "åË§ »Òb", "হিঙ পাই"],
    ["strong, strength", "àË§", "হেঙ"],
    ["dry", "àË§", "হেঙ"],
    ["to look upwards", "àË¹", "হেন"],
    ["scabies, given as \"a kind of fever\"", "åËµ", "হিত"],
    ["to do, to make", "åËµ", "হিত"],
    ["a stone", "åË¹", "হিন"],
    ["a civet cat", "åË¹", "হিন"],
    ["to clasp, to clip", "àË»", "হেপ"],
    ["near, at the side of", "åËÁ", "হিম"],
    ["to snatch", "åËÁ", "হিম"],
    ["a type of plant", "åË6", "হিউ"],
    ["a type of plant", "åË6 ©Ò§", "হিউ ছাঙ"],
    ["to take out water, to pour", "ËÕ", "হী"],
    ["vagina, female sex organ", "ËÕ", "হী"],
    ["a loom", "ËØ¡", "হুক"],
    ["six", "ËØ¡", "হুক"],
    ["untidy", "ËØ¡", "হুক"],
    ["to be displeased with, to be on bad terms with", "ËØ§", "হুঙ"],
    ["to cook vegetables and other dishes, to boil, not used for rice", "ËØ§", "হুঙ"],
    ["a classifier for fruit and similar round things", "ËØb", "হুই"],
    ["a stream, a creek", "ËØb", "হুই"],
    ["to shrink", "ËØµ", "হুত"],
    ["to step backwards", "ËØ¹", "হুন"],
    ["to pounce", "ËØ»", "হুপ"],
    ["to meet", "ËØ»", "হুপ"],
    ["a hole", "ËÙ", "হূ"],
    ["to know", "ËÙ", "হূ"],
    ["deaf", "ËÙ ¹Ø¡", "হূ নুক"],
    ["the head", "ËÙ", "হূ"],
    ["to block, to prevent", "àË", "হে"],
    ["to ring, to beat something to make a sound", "ËÒb", "হাই"],
    ["to cry", "ËÒb", "হাই"],
    ["dry land ricefield", "ËÒb", "হাই"],
    ["a pot for cooking or steaming rice", "ËÒb", "হাই"],
    ["to excavate, to cut down a hill", "ËÒb", "হাই"],
    ["bad", "ËÒb", "হাই"],
    ["angry", "ËÒb", "হাই"],
    ["much", "ËÒb", "হাই"],
    ["to be lost, to disappear", "ËÒb", "হাই"],
    ["to bundle, to wrap up", "Ë", "হ"],
    ["to deliver a sermon", "Ë", "হ"],
    ["to drive away, used particularly with animals such as cattle", "Ë", "হ"],
    ["to take", "Ë", "হ"],
    ["a palace", "Ë", "হ"],
    ["a golden palace", "Ë ¢ÒÁ", "হ খাম"],
    ["to roll", "ËÒÁ", "হাম"],
    ["testicles", "ËÒÁ", "হাম"],
    ["abandoned, left", "ËÒÁ", "হাম"],
    ["to prohibit", "ËÒÁ", "হাম"],
    ["to carry by means of a stick, held by ² or more persons", "ËÒÁ", "হাম"],
    ["to cover with a blanket", "ËØÁ", "হুম"],
    ["to cover", "ËØÁ", "হুম"],
    ["with, along with", "ËØÁ", "হুম"],
    ["shade", "ËØÁ", "হুম"],
    ["to gather", "ËÁ", "হম"],
    ["indigo", "ËÁ", "হম"],
    ["sweet-smelling, fragrant", "ËÁ", "হম"],
    ["gums", "àËä¡", "হৌক"],
    ["sloping", "àËä¡", "হৌক"],
    ["the glare of fire", "àËä§", "হৌঙ"],
    ["a long time", "àËä§", "হৌঙ"],
    ["an exclamation, \"Don't disturb!\"", "àËäµ", "হৌত"],
    ["a bed bug", "àËäµ", "হৌত"],
    ["not tasty", "àËä¹", "হৌন"],
    ["a house", "àËä¹", "হৌন"],
    ["to drive animals, such as cattle", "àËä»", "হৌপ"],
    ["to wish", "àËäÁ", "হৌম"],
    ["sweat", "àËä", "হৌ"],
    ["a boat", "àËä", "হৌ"],
    ["bright", "àËä", "হৌ"],
    ["to bark", "ËÒF", "হাও"],
    ["a louse", "ËÒF", "হাও"],
    ["we, 1st person plural pronoun", "ËÒF", "হাও"],
    ["a bridge", "ËÒF", "হাও"],
    ["from the roof to the floor", "ËÒF", "হাও"],
    ["very angry", "ËÒF", "হাও"],
    ["to yawn", "ËÒF ËÒb", "হাও হাই"],
    ["a lance", "Ë¡", "হক"],
    ["grey hair", "Ë¡", "হক"],
    ["to jump from one place to another; hɔŋ¹ is used to refer to jumping from a stationary position, not to refer to a running jump.", "Ë§", "হঙ"],
    ["to help somebody to lift something", "Ë§", "হঙ"],
    ["a room", "Ë§", "হঙ"],
    ["to call", "Ë§", "হঙ"],
    ["a drain", "Ë§", "হঙ"],
    ["to arrive", "Ëµ", "হত"],
    ["to cut", "Ë¹", "হন"],
    ["very hot", "Ë¹", "হন"],
    ["a cockscomb", "Ë¹", "হন"],
    ["to carry something in both arms", "Ë»", "হপ"],
    ["round, one complete round", "Ë»", "হপ"],
    ["to give", "ËÒw", "হাঔ"],
    ["to cause, to allow, to let", "ËÒw", "হাঔ"],
    ["a symbol, a mark", "Ëb", "হই"],
    ["to hang", "Ëb", "হই"],
    ["shellfish", "Ëb", "হই"],
    ["the body", "ÍÒ§ ¡Ò", "আঙ কা"],
    ["dish", "ÍÒ§", "আঙ"],
    ["a type of lizard that lives in the forest", "ÍÒ§ ¢Ò§", "আঙ খাঙ"],
    ["a basin for rice, a rice dish", "ÍÒ§ ¢ÒF", "আঙ খাও"],
    ["dirty water, sullage", "ÍÒ§ ÍÒ¡", "আঙ আক"],
    ["a kind of tattoo which gives protection from being shot", "ÍÒ§", "আঙ"],
    ["to say bad things, to tell about bad actions", "ÍÒ§", "আঙ"],
    ["seventh daughter", "ÍÒµ", "আত"],
    ["chess", "ÍÒ¹ ¨Ò", "আন চা"],
    ["which", "ÍÒ¹", "আন"],
    ["a classifier for many things", "ÍÒ¹", "আন"],
    ["food stuck in the throat", "ÍÒ¹", "আন"],
    ["to count", "ÍÒ¹", "আন"],
    ["big, said of rice only", "ÍÒ¹", "আন"],
    ["to offer", "ÍÒ»", "আপ"],
    ["to bathe", "ÍÒ»", "আপ"],
    ["to bathe", "ÍÒ» ¹ÒÁ", "আপ নাম"],
    ["another", "ÍÒ µÒ§", "আ তাঙ"],
    ["maternal uncle", "ÍÒ ¹Ò", "আ না"],
    ["sin", "ÍÒ à»µ", "আ পেত"],
    ["age", "ÍÒ ©Ò¡", "আ ছাক"],
    ["aunt", "ÍÒ", "আ"],
    ["to open", "ÍÒ", "আ"],
    ["baby", "ÍÒ", "আ"],
    ["more", "b¡", "ইক"],
    ["to lean on something", "b§", "ইঙ"],
    ["a type of house lizard", "b§ å¢§", "ইঙ খিঙ"],
    ["a water pot", "g§", "এঙ"],
    ["waist", "g§", "এঙ"],
    ["tendons", "b¹", "ইন"],
    ["small", "g¹", "এন"],
    ["sixth daughter", "bµ", "ইত"],
    ["a kind of ox", "g»", "এপ"],
    ["to sit close by", "g»", "এপ"],
    ["full, used for food", "bÁ", "ইম"],
    ["to shout", "b6", "ইউ"],
    ["pity", "u ·Ù", "ঈ দূ"],
    ["second daughter", "u", "ঈ"],
    ["fifth daughter", "6¡", "উক"],
    ["low part of the hand, given as \"when capping the hand, the low part is called 'uN³ m&²'.", "6§", "উঙ"],
    ["an exclamation of reply or response", "6b", "উই"],
    ["a tune", "6b", "উই"],
    ["to close a hole", "6µ", "উত"],
    ["warm", "6¹", "উন"],
    ["to gargle", "6¹", "উন"],
    ["soft", "6¹", "উন"],
    ["offering tray", "6»", "উপ"],
    ["to offer", "6»", "উপ"],
    ["to keep carefully", "àÍÒ", "আে"],
    ["to stay at, to live at", "^", "ঊ"],
    ["father", "^", "ঊ"],
    ["hope, wish", "g", "এ"],
    ["fourth daughter", "ÍÒb", "আই"],
    ["to cough", "ÍÒb", "আই"],
    ["an exclamation", "ÍÒb", "আই"],
    ["shy", "ÍÒb", "আই"],
    ["gas", "ÍÒb", "আই"],
    ["first son", "ÍÒb", "আই"],
    ["ʒes", "Í", "অ"],
    ["happy", "ÍÒÁ", "আম"],
    ["to be unable to say, to keep secret", "ÍÒÁ", "আম"],
    ["not, negative", "ÍÒÁ", "আম"],
    ["third daughter", "ÍÒÁ", "আম"],
    ["to offer a dowry", "6Á", "উম"],
    ["to hold in the arms", "6Á", "উম"],
    ["to hold in the mouth", "6Á", "উম"],
    ["not spending more", "ÍÁ", "অম"],
    ["napkin", "ÍÁ", "অম"],
    ["dirty", "àÍä¡", "অৌক"],
    ["proud, haughty", "àÍäµ", "অৌত"],
    ["to swallow, to drink", "àÍä¹", "অৌন"],
    ["starving", "àÍä»", "অৌপ"],
    ["to cover", "àÍäÁ", "অৌম"],
    ["yes", "àÍä", "অৌ"],
    ["to take", "ÍÒF", "আও"],
    ["an uncle, the father's younger brother", "ÍÒF", "আও"],
    ["to come out", "Í¡", "অক"],
    ["to win", "Í§", "অঙ"],
    ["small, soft", "Í¹", "অন"],
    ["to lead", "Í¹", "অন"],
    ["painful", "ÍÒw", "আঔ"],
    ["to feed animals", "Íb", "অই"],
    ["sugar cane", "Íb", "অই"],
]
