# -*- coding: utf-8 -*-
# Sort a regex in reverse order by length.

import ast
import sys

# import adlamToLatin

#adlam_to_latin_map = # {
#     "𞤀": "A",
#     "𞤢": "a",
#     "𞤀𞥄": "AA",
#     "𞤀𞥄": "Aa",
#     "𞤢𞥄": "aa",
#     "𞤄": "B",
#     "𞤦": "b",
#     "𞤄𞥆": "BB",
#     "𞤄𞥆": "Bb",
#     "𞤦𞥆": "bb",
#     "𞤇": "Ɓ",
#     "𞤩": "ɓ",
#     "𞤇𞥆": "ƁƁ",
#     "𞤇𞥆": "Ɓɓ",
#     "𞤩𞥆": "ɓɓ",
#     "𞤇": "BH",
#     "𞤇": "Bh",
#     "𞤇𞥆": "BBH",
#     "𞤇𞥆": "Bbh",
#     "𞤩": "bh",
#     "𞤩𞥆": "bbh",
#     "𞤕": "C",
#     "𞤷": "c",
#     "𞤕𞥆": "CC",
#     "𞤕𞥆": "Cc",
#     "𞤷𞥆": "cc",
#     "𞤁": "D",
#     "𞤣": "d",
#     "𞤁𞥆": "DD",
#     "𞤁𞥆": "Dd",
#     "𞤣𞥆": "dd",
#     "𞤍": " Ɗ",
#     "𞤯": "ɗ",
#     "𞤍𞥆": " ƊƊ",
#     "𞤍𞥆": " Ɗɗ",
#     "𞤯𞥆": "ɗɗ",
#     "𞤍": "DH",
#     "𞤯": "dh",
#     "𞤍𞥆": "DDH",
#     "𞤍𞥆": "Ddh",
#     "𞤯𞥆": "ddh",
#     "𞤉": "E",
#     "𞤫": "e",
#     "𞤉𞥅": "EE",
#     "𞤉𞥅": "Ee",
#     "𞤫𞥅": "ee",
#     "𞤊": "F",
#     "𞤬": "f",
#     "𞤊𞥆": "FF",
#     "𞤊𞥆": "Ff",
#     "𞤬𞥆": "ff",
#     "𞤘": "G",
#     "𞤺": "g",
#     "𞤘𞥆": "GG",
#     "𞤘𞥆": "Gg",
#     "𞤺𞥆": "gg",
#     "𞤞": "GB",
#     "𞥀": "gb",
#     "𞤞𞥆": "GGB",
#     "𞤞𞥆": "Ggb",
#     "𞥀𞥆": "ggb",
#     "𞤖": "H",
#     "𞤸": "h",
#     "𞤖𞥆": "HH",
#     "𞤖𞥆": "Hh",
#     "𞤸𞥆": "hh",
#     "𞤋": "I",
#     "𞤭": "i",
#     "𞤋𞥅": "II",
#     "𞤋𞥅": "Ii",
#     "𞤭𞥅": "ii",
#     "𞤔": "J",
#     "𞤶": "j",
#     "𞤔𞥆": "JJ",
#     "𞤔𞥆": "Jj",
#     "𞤶𞥆": "jj",
#     "𞤑": "K",
#     "𞤳": "k",
#     "𞤑𞥆": "KK",
#     "𞤑𞥆": "Kk",
#     "𞤳𞥆": "kk",
#     "𞤝": "KH",
#     "𞤿": "kh",
#     "𞤝𞥆": "KKH",
#     "𞤝𞥆": "Kkh",
#     "𞤿𞥆": "kkh",
#     "𞤝": "X",
#     "𞤿": "x",
#     "𞤝𞥆": "XX",
#     "𞤝𞥆": "Xx",
#     "𞤿𞥆": "xx",
#     "𞤂": "L",
#     "𞤤": "l",
#     "𞤂𞥆": "LL",
#     "𞤂𞥆": "Ll",
#     "𞤤𞥆": "ll",
#     "𞤃": "M",
#     "𞤥": "m",
#     "𞤃𞥆": "MM",
#     "𞤃𞥆": "Mm",
#     "𞤥𞥆": "mm",
#     "𞤐": "N",
#     "𞤲": "n",
#     "𞤐𞥆": "NN",
#     "𞤐𞥆": "Nn",
#     "𞤲𞥆": "nn",
#     "𞤛": "Ŋ",
#     "𞤽": "ŋ",
#     "𞤛𞥆": "ŊŊ",
#     "𞤛𞥆": "Ŋŋ",
#     "𞤽𞥆": "ŋŋ",
#     "𞤛": "NH",
#     "𞤽": "nh",
#     "𞤛𞥆": "NNH",
#     "𞤛𞥆": "Nnh",
#     "𞤽𞥆": "nnh",
#     "𞤙": "Ñ",
#     "𞤻": "ñ",
#     "𞤙𞥆": "ÑÑ",
#     "𞤙𞥆": "Ññ",
#     "𞤻𞥆": "ññ",
#     "𞤙": "NY",
#     "𞤻": "ny",
#     "𞤙𞥆": "NNY",
#     "𞤙𞥆": "Nny",
#     "𞤻𞥆": "nny",
#     "𞤌": "O",
#     "𞤮": "o",
#     "𞤌𞥅": "OO",
#     "𞤌𞥅": "Oo",
#     "𞤮𞥅": "oo",
#     "𞤆": "P",
#     "𞤨": "p",
#     "𞤆𞥆": "PP",
#     "𞤆𞥆": "Pp",
#     "𞤨𞥆": "pp",
#     "𞤠": "KP",
#     "𞥂": "kp",
#     "𞤠𞥆": "KKP",
#     "𞤠𞥆": "Kkp",
#     "𞥂𞥆": "kkp",
#     "𞤗": "Q",
#     "𞤹": "q",
#     "𞤗𞥆": "QQ",
#     "𞤗𞥆": "Qq",
#     "𞤹𞥆": "qq",
#     "𞤗": "GH",
#     "𞤹": "gh",
#     "𞤗𞥆": "GGH",
#     "𞤗𞥆": "Ggh",
#     "𞤹𞥆": "ggh",
#     "𞤈": "R",
#     "𞤪": "r",
#     "𞤈𞥆": "RR",
#     "𞤈𞥆": "Rr",
#     "𞤪𞥆": "rr",
#     "𞤅": "S",
#     "𞤧": "s",
#     "𞤅𞥆": "SS",
#     "𞤅𞥆": "Ss",
#     "𞤧𞥆": "ss",
#     "𞤡": "SH",
#     "𞥃": "Sh",
#     "𞤡𞥆": "SSH",
#     "𞤡𞥆": "Ssh",
#     "𞥃𞥆": "ssh",
#     "𞤚": "T",
#     "𞤼": "t",
#     "𞤚𞥆": "TT",
#     "𞤚𞥆": "Tt",
#     "𞤼𞥆": "tt",
#     "𞤓": "U",
#     "𞤵": "u",
#     "𞤓𞥅": "UU",
#     "𞤓𞥅": "Uu",
#     "𞤵𞥅": "uu",
#     "𞤜": "V",
#     "𞤾": "v",
#     "𞤜𞥆": "VV",
#     "𞤜𞥆": "Vv",
#     "𞤾𞥆": "vv",
#     "𞤏": "W",
#     "𞤱": "w",
#     "𞤏𞥆": "WW",
#     "𞤏𞥆": "Ww",
#     "𞤱𞥆": "ww",
#     "𞤒": "Y",
#     "𞤴": "y",
#     "𞤒𞥆": "YY",
#     "𞤒𞥆": "Yy",
#     "𞤴𞥆": "yy",
#     "𞤎": "Ƴ",
#     "𞤰": "ƴ",
#     "𞤎𞥆": "ƳƳ",
#     "𞤎𞥆": "Ƴƴ",
#     "𞤰𞥆": "ƴƴ",
#     "𞤎": "YH",
#     "𞤰": "yh",
#     "𞤎𞥆": "YYH",
#     "𞤎𞥆": "Yyh",
#     "𞤰𞥆": "yyh",
#     "𞤟": "Z",
#     "𞥁": "z",
#     "𞤟𞥆": "ZZ",
#     "𞤟𞥆": "Zz",
#     "𞥁𞥆": "zz",
#     𞤐'"𞤁": "ND",
#     𞤐'"𞤁": "Nd",
#     "𞤲": "𞤣	nd",
#     𞤐'"𞤄": "MB",
#     "𞤐": "𞤄	Mb",
#     𞤲'"𞤦": "mb",
#     "𞤐": "𞤔	NJ",
#     𞤐'"𞤔": "Nj",
#     𞤐'"𞤘": "NG",
#     "𞤐": "𞤘	Ng",
#     "𞤲": "𞤺	ng",
#     𞤲"𞤣": "nnd",
#     𞤥"𞤦": "mmb",
#     𞤲"𞤶": "nnj",
#     𞤲"𞤺": "nng    ",
#     # TODO: digits and punctuation
# '𞤀𞤁𞤂𞤢𞤃':	'Laten',
# '𞤀𞥄𞤐𞤁':	'AAND',
# '𞤀𞥄𞤲𞤣':	'Aand',
# '𞤢𞥄𞤲𞤣':	'aand',
# '𞤀𞥄𞤐𞤄':	'AAMB',
# '𞤀𞥄𞤲𞤦':	'Aamb',
# '𞤢𞥄𞤲𞤦':	'aamb',
# '𞤀𞥄𞤐𞤔':	'AANJ',
# '𞤀𞥄𞤲𞤶':	'Aanj',
# '𞤢𞥄𞤲𞤶':	'aanj',
# '𞤀𞥄𞤐𞤘':	'AANG',
# '𞤀𞥄𞤲𞤺':	'Aang',
# '𞤢𞥄𞤲𞤺':	'aang',
# '𞤉𞥅𞤐𞤁':	'EEND',
# '𞤉𞥅𞤲𞤣':	'Eend',
# '𞤫𞥅𞤲𞤣':	'eend',
# '𞤉𞥅𞤐𞤄':	'EEMB',
# '𞤉𞥅𞤲𞤦':	'Eemb',
# '𞤫𞥅𞤲𞤦':	'eemb',
# '𞤉𞥅𞤐𞤔':	'EENJ',
# '𞤉𞥅𞤲𞤶':	'Eenj',
# '𞤫𞥅𞤲𞤶':	'eenj',
# '𞤉𞥅𞤐𞤘':	'EENG',
# '𞤉𞥅𞤲𞤺':	'Eeng',
# '𞤫𞥅𞤲𞤺':	'eeng',
# '𞤋𞥅𞤐𞤁':	'IIND',
# '𞤋𞥅𞤲𞤣':	'Iind',
# '𞤭𞥅𞤲𞤣':	'iind',
# '𞤋𞥅𞤐𞤄':	'IIMB',
# '𞤋𞥅𞤲𞤦':	'Iimb',
# '𞤭𞥅𞤲𞤦':	'iimb',
# '𞤋𞥅𞤐𞤔':	'IINJ',
# '𞤋𞥅𞤲𞤶':	'Iinj',
# '𞤭𞥅𞤲𞤶':	'iinj',
# '𞤋𞥅𞤐𞤘':	'IING',
# '𞤋𞥅𞤲𞤺':	'Iing',
# '𞤭𞥅𞤲𞤺':	'iing',
# '𞤌𞥅𞤐𞤁':	'OOND',
# '𞤌𞥅𞤲𞤣':	'Oond',
# '𞤮𞥅𞤲𞤣':	'oond',
# '𞤌𞥅𞤐𞤄':	'OOMB',
# '𞤌𞥅𞤲𞤦':	'Oomb',
# '𞤮𞥅𞤲𞤦':	'oomb',
# '𞤌𞥅𞤐𞤔':	'OONJ',
# '𞤌𞥅𞤲𞤶':	'Oonj',
# '𞤮𞥅𞤲𞤶':	'oonj',
# '𞤌𞥅𞤐𞤘':	'OONG',
# '𞤌𞥅𞤲𞤺':	'Oong',
# '𞤮𞥅𞤲𞤺':	'oong',
# '𞤓𞥅𞤐𞤁':	'UUND',
# '𞤓𞥅𞤲𞤣':	'Uund',
# '𞤵𞥅𞤲𞤣':	'uund',
# '𞤓𞥅𞤐𞤄':	'UUMB',
# 𞤓𞥅'𞤲𞤦':	'Uumb',
# '𞤵𞥅𞤲𞤦':	'uumb',
# '𞤓𞥅𞤐𞤔':	'UUNJ',
# '𞤓𞥅𞤲𞤶':	'Uunj',
# '𞤵𞥅𞤲𞤶':	'uunj',
# '𞤓𞥅𞤐𞤘':	'UUNG',
# '𞤓𞥅𞤲𞤺':	'Uung',
# '𞤵𞥅𞤲𞤺':	'uung',
# '𞤐𞤁':	'ND',
# '𞤐𞤣':	'Nd',
# '𞤲𞤣':	'nd',
# '𞤐𞤄':	'MB',
# '𞤐𞤦':	'Mb',
# '𞤲𞤦':	'mb',
# '𞤐𞤔':	'NJ',
# '𞤐𞤶':	'Nj',
# '𞤲𞤶':	'nj',
# '𞤐𞤘':	'NG',
# '𞤐𞤺':	'Ng',
# '𞤲𞤺':	'ng',
# '𞤢𞤢':	'a\'a',
# '𞤫𞤫':	'e\'e',
# '𞤭𞤭':	'i\'i',
# '𞤮𞤮':	'o\'o',
# '𞤵𞤵':	'u\'u',
# '𞤀𞤀':	'A\'a',
# '𞤉𞤉':	'E\'e',
# '𞤋𞤋':	'I\'i',
# '𞤌𞤌':	'O\'o',
# '𞤓𞤓':	'U\'u',
# '𞤀𞤀':	'A\'A',
# '𞤉𞤉':	'E\'E',
# '𞤋𞤋':	'I\'I',
# '𞤌𞤌':	'O\'O',
# '𞤓𞤓':	'U\'U',

# '𞥐      ': '0',
# '𞥑      ': '1',
# '𞥒      ': '2',
# '𞥓      ': '3',
# '𞥔      ': '4',
# '𞥕      ': '5',
# '𞥖      ': '6',
# '𞥗      ': '7',
# '𞥘      ': '8',
# '𞥙      ': '9',
# '!      ': '!',

# '𞥞      ': '!',
# '?      ': '?',
# '𞥟      ': '?',
# '⹁      ': ',',
# '⁏      ': ';',
# '.	.  ': ' '
# }

mende_map_v3 ={
	'pi': '\ue000',
	'pii': '\ue001',
	'pa': '\ue002',
	'paa': '\ue003',
	'paaa': '\ue004',
	'pu': '\ue005',
	'puu': '\ue006',
	'pe': '\ue007',
	'pee': '\ue008',
	'pɛ': '\ue009',
	'pɛɛ': '\ue00a',
	'pɔ': '\ue00b',
	'pɔɔ': '\ue00c',
	'po': '\ue00d',
	'poo': '\ue00e',

	'wi': '\ue00f',
	'wii': '\ue010',
	'wI': '\ue01f',
	'wa': '\ue011',
	'waa': '\ue012',
	'wA': '\ue020',
	'wAA': '\ue021',
	'wu': '\ue013',
	'wuu': '\ue014',
	'we': '\ue015',
	'wee': '\ue016',
	'wE': '\ue022',
	'wɛ': '\ue017',
	'wɛɛ': '\ue018',
	'wƐ': '\ue023',
	'wƐƐ': '\ue024',
	'wɔ': '\ue019',
	'wɔɔ': '\ue01a',
	'wo': '\ue01b',
	'woo': '\ue01c',

	'mbi': '\ue025',
	'mbii': '\ue026',
	'mba': '\ue027',
	'mbaa': '\ue028',
	'mbu': '\ue029',
	'mbuu': '\ue02a',
	'mbU': '\ue033',
	'mbUU': '\ue034',
	'Mbu': '\ue033',
	'Mbuu': '\ue034',
	'mbe': '\ue02b',
	'mbee': '\ue02c',
	'Mbe': '\ue035',
	'mbE': '\ue035',
	'mbɛ': '\ue02d',
	'mbɛɛ': '\ue02e',
	'mbƐ': '\ue036',
	'mbƐƐ': '\ue037',
	'mbɔ': '\ue02f',
	'mbɔɔ': '\ue030',
	'mbƆ': '\ue038',
	'mbƆƆ': '\ue039',
	'mbo': '\ue031',
	'mboo': '\ue032',
	'mbO': '\ue03a',

	'bi': '\ue03b',
	'bii': '\ue03c',
	'ba': '\ue03d',
	'baa': '\ue03e',
	'bu': '\ue03f',
	'buu': '\ue040',
	'be': '\ue041',
	'bee': '\ue042',
	'bɛ': '\ue043',
	'bɔ': '\ue044',
	'bɔɔ': '\ue045',
	'bo': '\ue046',
	'boo': '\ue047',
	'booo': '\ue048',

	'kpi': '\ue049',
	'kpa': '\ue04a',
	'kpaa': '\ue04b',
	'kpaaa': '\ue04c',
	'kpu': '\ue04d',
	'kpuu': '\ue04e',
	'kpe': '\ue04f',
	'kpɛ': '\ue050',
	'kpɛɛ': '\ue051',
	'kpɛɛɛ': '\ue052',
	'kpɔ': '\ue053',
	'kpɔɔ': '\ue054',
	'kpo': '\ue055',

	'gbi': '\ue056',
	'gba': '\ue057',
	'gbaa': '\ue058',
	'gbu': '\ue059',
	'gbe': '\ue05a',
	'gbɛ': '\ue05b',
	'gbɛɛ': '\ue05c',
	'gbɔ': '\ue05d',
	'gbɔɔ': '\ue05e',
	'gbo': '\ue05f',
	'gboo': '\ue060',
	
	'fi': '\ue061',
	'fa': '\ue062',
	'fu': '\ue063',
	'fe': '\ue064',
	'fee': '\ue065',
	'fɛ': '\ue066',
	'fɛɛ': '\ue067',
	'fɔ': '\ue068',
	'fo': '\ue069',

	'vi': '\ue06c',
	'va': '\ue06d',
	'vaa': '\ue06e',
	'vu': '\ue06f',
	'vuu': '\ue070',
	've': '\ue071',
	'vee': '\ue072',
	'vɛ': '\ue073',
	'vɛɛ': '\ue074',
	'vɔ': '\ue075',
	'vɔɔ': '\ue076',
	'vo': '\ue077',
	'voo': '\ue078',

	'ti': '\ue079',
	'tii': '\ue07a',
	'ta': '\ue07b',
	'taa': '\ue07c',
	'tu': '\ue07d',
	'tuu': '\ue07e',
	'te': '\ue07f',
	'tee': '\ue080',
	'tɛ': '\ue081',
	'tɛɛ': '\ue082',
	'tɔ': '\ue083',
	'to': '\ue084',
	'too': '\ue085',

	'li': '\ue086',
	'lii': '\ue087',
	'liii': '\ue088',
	'la': '\ue089',
	'laa': '\ue08a',
	'laaa': '\ue08b',
	'lA': '\ue08c',
	'lu': '\ue08d',
	'luu': '\ue08e',
	'le': '\ue08f',
	'lee': '\ue090',
	'lɛ': '\ue091',
	'lɛɛ': '\ue092',
	'lɛɛɛ': '\ue093',
	'lɔ': '\ue094',
	'lɔɔ': '\ue095',
	'lo': '\ue096',
	'loo': '\ue097',
	
	'ndi': '\ue09a',
	'ndii': '\ue09b',
	'nda': '\ue09c',
	'ndaa': '\ue09d',
	'ndu': '\ue09e',
	'nduu': '\ue09f',
	'nde': '\ue0a0',
	'ndee': '\ue0a1',
	'ndɛ': '\ue0a2',
	'ndɛɛ': '\ue0a3',
	'ndɛɛɛ': '\ue0a4',
	'ndɔ': '\ue0a5',
	'ndɔɔ': '\ue0a6',
	'ndo': '\ue0a7',
	'ndoo': '\ue0a8',

	'di': '\ue0aa',
	'dii': '\ue0a9',
	'da': '\ue0ab',
	'daa': '\ue0ac',
	'du': '\ue0ad',
	'duu': '\ue0ae',
	'de': '\ue0af',
	'dee': '\ue0b0',
	'dɔ': '\ue0b1',
	'dɔɔ': '\ue0b2',
	'do': '\ue0b3',

	'si': '\ue0b4',
	'sii': '\ue0b5',
	'sa': '\ue0b6',
	'saa': '\ue0b7',
	'su': '\ue0b8',
	'suu': '\ue0b9',
	'se': '\ue0ba',
	'see': '\ue0bb',
	'sɛ': '\ue0bc',
	'sɛɛ': '\ue0bd',
	'sɔ': '\ue0be',
	'sɔɔ': '\ue0bf',
	'so': '\ue0c0',
	'soo': '\ue0c1',

	'ji': '\ue0c2',
	'jii': '\ue0c3',
	'ja': '\ue0c4',
	'jaa': '\ue0c5',
	'ju': '\ue0c6',
	'juu': '\ue0c7',
	'je': '\ue0c8',
	'jee': '\ue0c9',
	'jɛ': '\ue0ca',
	'jɛɛ': '\ue0cb',
	'jɔ': '\ue0cc',
	'jɔɔ': '\ue0cd',
	'jo': '\ue0ce',

	'nja': '\ue0cf',
	'njaa': '\ue0d0',
	'nju': '\ue0d1',
	'njuu': '\ue0d2',
	'nje': '\ue0d3',
	'njee': '\ue0d4',
	'njeee': '\ue0d5',
	'njɔ': '\ue0d6',
	'njɔɔ': '\ue0d7',
	'njo': '\ue0d8',
	'njoo': '\ue0d9',

	'yi': '\ue0da',
	'ya': '\ue0db',
	'yu': '\ue0dc',
	'ye': '\ue0dd',
	'yee': '\ue0de',
	'yeee': '\ue0df',
	'yɛ': '\ue0e0',
	'yɛɛ': '\ue0e1',
	'yɔ': '\ue0e2',
	'yɔɔ': '\ue0e3',
	'yo': '\ue0e4',
	'yoo': '\ue0e5',

	'ngi': '\ue0e6',
	'ngii': '\ue0e7',
	'nga': '\ue0e8',
	'ngaa': '\ue0e9',
	'ngu': '\ue0ea',
	'nguu': '\ue0eb',
	'nge': '\ue0ec',
	'ngee': '\ue0ed',
	'ngeee': '\ue0ee',
	'ngɛ': '\ue0ef',
	'ngɔ': '\ue0f0',
	'ngɔɔ': '\ue0f1',
	'ngo': '\ue0f2',
	'ngoo': '\ue0f3',

	'gi': '\ue0f6',
	'gii': '\ue0f7',
	'ga': '\ue0f8',
	'gaa': '\ue0f9',
	'gaaa': '\ue0fa',
	'gu': '\ue0fb',
	'guu': '\ue0fc',
	'ge': '\ue0fd',
	'gee': '\ue0fe',
	'gɛ': '\ue0ff',
	'gɛɛ': '\ue100',
	'gɔ': '\ue101',
	'gɔɔ': '\ue102',
	'go': '\ue103',
	'goo': '\ue104',

	'ki': '\ue109',
	'kii': '\ue10a',
	'ka': '\ue10b',
	'kaa': '\ue10c',
	'ku': '\ue10d',
	'kuu': '\ue10e',
	'ke': '\ue10f',
	'kee': '\ue110',
	'kɛ': '\ue111',
	'kɔ': '\ue112',
	'kɔɔ': '\ue113',
	'ko': '\ue114',
	'koo': '\ue115',

	'hi': '\ue117',
	'ha': '\ue118',
	'hu': '\ue119',
	'huu': '\ue11a',
	'huuu': '\ue11b',
	'he': '\ue11c',
	'hɛ': '\ue11d',
	'hɛɛ': '\ue11e',
	'hɔ': '\ue11f',
	'hɔɔ': '\ue120',
	'hɔɔɔ': '\ue121',
	'ho': '\ue122',

	'i': '\ue127',
	'a': '\ue128',
	'aa': '\ue129',
	'u': '\ue12a',
	'uu': '\ue12b',
	'e': '\ue12c',
	'ee': '\ue12d',
	'ɛ': '\ue12e',
	'ɛɛ': '\ue12f',
	'ɔ': '\ue130',
	'ɔɔ': '\ue131',
	'o': '\ue132',

	'Hi': '\ue134',
	'Hii': '\ue135',
	'Ha': '\ue136',
	'Haa': '\ue137',
	'Hu': '\ue138',
	'Huu': '\ue139',
	'Hɛ': '\ue13a',
	'Hɛɛ': '\ue13b',
	'Hɔ': '\ue13c',
	'Hɔɔ': '\ue13e',
	
	'Mi': '\ue140',
	'Ma': '\ue141',
	'Mu': '\ue142',
	'Mɛ': '\ue143',
	'Mɔ': '\ue144',

	'Ni': '\ue149',
	'Na': '\ue14a',
	'Nu': '\ue14b',
	'Nɛ': '\ue14d',
	'Nɛɛ': '\ue14e',
	'Nɔ': '\ue14f',

	'Nyi': '\ue150',
	'Nya': '\ue151',
	'Nyu': '\ue152',
	'Nyuu': '\ue153',
	'Nyɛ': '\ue154',
	'Nyɛɛ': '\ue155',
	'Nyɔ': '\ue156',
	'Nyɔɔ': '\ue157',

	'Ŋa': '\ue158',
	'Ŋaa': '\ue159',
	'Ŋɛ': '\ue15a',
	'Ŋɛɛ': '\ue15b',

	'I': '\ue15d',
	'II': '\ue15e',
	'E': '\ue160',
	'Ɛ': '\ue161',
	'ƐƐ': '\ue162',

	'nhɔ': '\ue13d',
	'nnɛ': '\ue14c',
	
	'wɛi': '\ue01d',
	'wɛii': '\ue01e',
	'gɛi': '\ue107',
	'gɛii': '\ue108',
	'ɛi': '\ue133',
	'ŋgua': '\ue0f4',
	'ŋguaa': '\ue0f5',
	'nngua': '\ue0f4',
	'nnguaa': '\ue0f5',
	'gua': '\ue105',
	'guaa': '\ue106',
	'kua': '\ue116',
	'hua': '\ue13e',
	'huaa': '\ue13f',
 	'mnua': '\ue158',
	'mnuaa': '\ue158',
	'mnua': '\ue145',
	'mnuaa': '\ue146',
	'ŋua': '\ue15c',


	'fA': '\ue06a',
	'fAA': '\ue06b',
	'lƐ': '\ue098',
	'lƐƐ': '\ue099',
	'hei': '\ue123',
	'heii': '\ue124',
	'hou': '\ue125',
	'houu': '\ue126',
	'mũc': '\ue147',
	'mũ c': '\ue148'
    }

m3_older = {
	'pi': '\ue000',
	'pii': '\ue001',
	'pa': '\ue002',
	'paa': '\ue003',
	'paaa': '\ue004',
	'pu': '\ue005',
	'puu': '\ue006',
	'pe': '\ue007',
	'pee': '\ue008',
	'pɛ': '\ue009',
	'pɛɛ': '\ue00a',
	'pɔ': '\ue00b',
	'pɔɔ': '\ue00c',
	'po': '\ue00d',
	'poo': '\ue00e',

	'wi': '\ue00f',
	'wii': '\ue010',
	'wI': '\ue01f',
	'wa': '\ue011',
	'waa': '\ue012',
	'wA': '\ue020',
	'wAA': '\ue021',
	'wu': '\ue013',
	'wuu': '\ue014',
	'we': '\ue015',
	'wee': '\ue016',
	'wE': '\ue022',
	'wɛ': '\ue017',
	'wɛɛ': '\ue018',
	'wƐ': '\ue023',
	'wƐƐ': '\ue024',
	'wɔ': '\ue019',
	'wɔɔ': '\ue01a',
	'wo': '\ue01b',
	'woo': '\ue01c',

	'mbi': '\ue025',
	'mbii': '\ue026',
	'mba': '\ue027',
	'mbaa': '\ue028',
	'mbu': '\ue029',
	'mbuu': '\ue02a',
	'mbU': '\ue033',
	'mbUU': '\ue034',
	'Mbu': '\ue033',
	'Mbuu': '\ue034',
	'mbe': '\ue02b',
	'mbee': '\ue02c',
	'Mbe': '\ue035',
	'mbE': '\ue035',
	'mbɛ': '\ue02d',
	'mbɛɛ': '\ue02e',
	'mbƐ': '\ue036',
	'mbƐƐ': '\ue037',
	'mbɔ': '\ue02f',
	'mbɔɔ': '\ue030',
	'mbƆ': '\ue038',
	'mbƆƆ': '\ue039',
	'mbo': '\ue031',
	'mboo': '\ue032',
	'mbO': '\ue03a',

	'bi': '\ue03b',
	'bii': '\ue03c',
	'ba': '\ue03d',
	'baa': '\ue03e',
	'bu': '\ue03f',
	'buu': '\ue040',
	'be': '\ue041',
	'bee': '\ue042',
	'bɛ': '\ue043',
	'bɔ': '\ue044',
	'bɔɔ': '\ue045',
	'bo': '\ue046',
	'boo': '\ue047',
	'booo': '\ue048',

	'kpi': '\ue049',
	'kpa': '\ue04a',
	'kpaa': '\ue04b',
	'kpaaa': '\ue04c',
	'kpu': '\ue04d',
	'kpuu': '\ue04e',
	'kpe': '\ue04f',
	'kpɛ': '\ue050',
	'kpɛɛ': '\ue051',
	'kpɛɛɛ': '\ue052',
	'kpɔ': '\ue053',
	'kpɔɔ': '\ue054',
	'kpo': '\ue055',

	'gbi': '\ue056',
	'gba': '\ue057',
	'gbaa': '\ue058',
	'gbu': '\ue059',
	'gbe': '\ue05a',
	'gbɛ': '\ue05b',
	'gbɛɛ': '\ue05c',
	'gbɔ': '\ue05d',
	'gbɔɔ': '\ue05e',
	'gbo': '\ue05f',
	'gboo': '\ue060',
	
	'fi': '\ue061',
	'fa': '\ue062',
	'fu': '\ue063',
	'fe': '\ue064',
	'fee': '\ue065',
	'fɛ': '\ue066',
	'fɛɛ': '\ue067',
	'fɔ': '\ue068',
	'fo': '\ue069',

	'vi': '\ue06c',
	'va': '\ue06d',
	'vaa': '\ue06e',
	'vu': '\ue06f',
	'vuu': '\ue070',
	've': '\ue071',
	'vee': '\ue072',
	'vɛ': '\ue073',
	'vɛɛ': '\ue074',
	'vɔ': '\ue075',
	'vɔɔ': '\ue076',
	'vo': '\ue077',
	'voo': '\ue078',

	'ti': '\ue079',
	'tii': '\ue07a',
	'ta': '\ue07b',
	'taa': '\ue07c',
	'tu': '\ue07d',
	'tuu': '\ue07e',
	'te': '\ue07f',
	'tee': '\ue080',
	'tɛ': '\ue081',
	'tɛɛ': '\ue082',
	'tɔ': '\ue083',
	'to': '\ue084',
	'too': '\ue085',

	'li': '\ue086',
	'lii': '\ue087',
	'liii': '\ue088',
	'la': '\ue089',
	'laa': '\ue08a',
	'laaa': '\ue08b',
	'lA': '\ue08c',
	'lu': '\ue08d',
	'luu': '\ue08e',
	'le': '\ue08f',
	'lee': '\ue090',
	'lɛ': '\ue091',
	'lɛɛ': '\ue092',
	'lɛɛɛ': '\ue083',
	'lɔ': '\ue094',
	'lɔɔ': '\ue095',
	'lo': '\ue096',
	'loo': '\ue097',
	
	'ndi': '\ue09a',
	'ndii': '\ue09b',
	'nda': '\ue09c',
	'ndaa': '\ue09d',
	'ndu': '\ue09e',
	'nduu': '\ue09f',
	'nde': '\ue0a0',
	'ndee': '\ue0a1',
	'ndɛ': '\ue0a2',
	'ndɛɛ': '\ue0a3',
	'ndɛɛɛ': '\ue0a4',
	'ndɔ': '\ue0a5',
	'ndɔɔ': '\ue0a6',
	'ndo': '\ue0a7',
	'ndoo': '\ue0a8',

	'di': '\ue0a9',
	'dii': '\ue0aa',
	'da': '\ue0ab',
	'daa': '\ue0ac',
	'du': '\ue0ad',
	'duu': '\ue0ae',
	'de': '\ue0af',
	'dee': '\ue0b0',
	'dɔ': '\ue0b1',
	'dɔɔ': '\ue0b2',
	'do': '\ue0b3',

	'si': '\ue0b4',
	'sii': '\ue0b5',
	'sa': '\ue0b6',
	'saa': '\ue0b7',
	'su': '\ue0b8',
	'suu': '\ue0b9',
	'se': '\ue0ba',
	'see': '\ue0bb',
	'sɛ': '\ue0bc',
	'sɛɛ': '\ue0bd',
	'sɔ': '\ue0be',
	'sɔɔ': '\ue0bf',
	'so': '\ue0c0',
	'soo': '\ue0c1',

	'ji': '\ue0c2',
	'jii': '\ue0c3',
	'ja': '\ue0c4',
	'jaa': '\ue0c5',
	'ju': '\ue0c6',
	'juu': '\ue0c7',
	'je': '\ue0c8',
	'jee': '\ue0c9',
	'jɛ': '\ue0ca',
	'jɛɛ': '\ue0cb',
	'jɔ': '\ue0cc',
	'jɔɔ': '\ue0cd',
	'jo': '\ue0ce',

	'nja': '\ue0cf',
	'njaa': '\ue0d0',
	'nju': '\ue0d1',
	'njuu': '\ue0d2',
	'nje': '\ue0d3',
	'njee': '\ue0d4',
	'njeee': '\ue0d5',
	'njɔ': '\ue0d6',
	'njɔɔ': '\ue0d7',
	'njo': '\ue0d8f',
	'njoo': '\ue0d9',

	'yi': '\ue0da',
	'ya': '\ue0db',
	'yu': '\ue0dc',
	'ye': '\ue0dd',
	'yee': '\ue0de',
	'yeee': '\ue0df',
	'yɛ': '\ue0e0',
	'yɛɛ': '\ue0e1',
	'yɔ': '\ue0e2',
	'yɔɔ': '\ue0e3',
	'yo': '\ue0e4',
	'yoo': '\ue035',

	'ngi': '\ue0e6',
	'ngii': '\ue0e7',
	'nga': '\ue0e8',
	'ngaa': '\ue0e9',
	'ngu': '\ue0ea',
	'nguu': '\ue0eb',
	'nge': '\ue0ec',
	'ngee': '\ue0ed',
	'ngeee': '\ue0ee',
	'ngɛ': '\ue0ef',
	'ngɔ': '\ue0f0',
	'ngɔɔ': '\ue0f1',
	'ngo': '\ue0f2',
	'ngoo': '\ue0f3',

	'gi': '\ue0f6',
	'gii': '\ue0f7',
	'ga': '\ue0f8',
	'gaa': '\ue0f9',
	'gaaa': '\ue0fa',
	'gu': '\ue0fb',
	'guu': '\ue0fc',
	'ge': '\ue0fd',
	'gee': '\ue0fe',
	'gɛ': '\ue0ff',
	'gɛɛ': '\ue100',
	'gɔ': '\ue101',
	'gɔɔ': '\ue102',
	'go': '\ue103',
	'goo': '\ue104',

	'ki': '\ue109',
	'kii': '\ue10a',
	'ka': '\ue10b',
	'kaa': '\ue10c',
	'ku': '\ue10d',
	'kuu': '\ue10e',
	'ke': '\ue10f',
	'kee': '\ue110',
	'kɛ': '\ue111',
	'kɔ': '\ue112',
	'kɔɔ': '\ue113',
	'ko': '\ue114',
	'koo': '\ue115',

	'hi': '\ue117',
	'ha': '\ue118',
	'hu': '\ue119',
	'huu': '\ue11a',
	'huuu': '\ue11b',
	'he': '\ue11c',
	'hɛ': '\ue11d',
	'hɛɛ': '\ue11e',
	'hɔ': '\ue11f',
	'hɔɔ': '\ue120',
	'hɔɔɔ': '\ue121',
	'ho': '\ue122',

	'i': '\ue127',
	'a': '\ue128',
	'aa': '\ue129',
	'u': '\ue12a',
	'uu': '\ue12b',
	'e': '\ue12c',
	'ee': '\ue12d',
	'ɛ': '\ue12e',
	'ɛɛ': '\ue12f',
	'ɔ': '\ue130',
	'ɔɔ': '\ue131',
	'o': '\ue132',

	'h̃ĩ': '\ue134',
	'h̃ĩĩ': '\ue135',
	'h̃ã': '\ue136',
	'h̃ãã': '\ue137',
	'h̃ũ': '\ue138',
	'h̃ũũ': '\ue139',
	'h̃ɛ̃': '\ue13a',
	'h̃ɛ̃ɛ̃': '\ue13b',
	'h̃ɔ̃': '\ue13c',
	'h̃ɔ̃ɔ̃': '\ue13e',
	
	'mĩ': '\ue140',
	'mã': '\ue141',
	'mũ': '\ue142',
	'mɛ̃': '\ue143',
	'mɔ̃': '\ue144',

	'nĩ': '\ue149',
	'nã': '\ue14a',
	'nũ': '\ue14b',
	'nɛ̃': '\ue14d',
	'nɛ̃ɛ̃': '\ue14e',
	'nɔ̃': '\ue14f',

	'nyĩ': '\ue150',
	'nyã': '\ue151',
	'nyũ': '\ue152',
	'nyũũ': '\ue153',
	'nyɛ̃': '\ue154',
	'nyɛ̃ɛ̃': '\ue155',
	'nyɔ̃': '\ue156',
	'nyɔ̃ɔ̃': '\ue157',

	'ŋã': '\ue158',
	'ŋãã': '\ue159',
	'ŋɛ̃': '\ue15a',
	'ŋɛ̃ɛ̃': '\ue15b',

	'ĩ': '\ue15d',
	'ĩĩ': '\ue15e',
	'ẽ': '\ue160',
	'ɛ̃': '\ue161',
	'ɛ̃ɛ̃': '\ue162',

	'nhɔ': '\ue13d',
	'nnɛ': '\ue14c',
	
	'wɛi': '\ue01d',
	'wɛii': '\ue01e',
	'gɛi': '\ue107',
	'gɛii': '\ue108',
	'ɛi': '\ue133',
	'ŋgua': '\ue0f4',
	'ŋguaa': '\ue0f5',
	'nngua': '\ue0f4',
	'nnguaa': '\ue0f5',
	'gua': '\ue105',
	'guaa': '\ue106',
	'kua': '\ue116',
	'hua': '\ue13e',
	'huaa': '\ue13f',
 	'mnua': '\ue158',
	'mnuaa': '\ue158',
	'mnua': '\ue145',
	'mnuaa': '\ue146',
	'ŋua': '\ue15c',


	'fã': '\ue06a',
	'fãã': '\ue06b',
	'lɛɛ': '\ue098',
	'lɛɛɛ': '\ue099',
	'hei': '\ue123',
	'heii': '\ue124',
	'hou': '\ue125',
	'houu': '\ue126',
	'mũc': '\ue147',
	'mũ c': '\ue148'
    }

m3_old = {
	'pi': '\e000',
	'pii': '\e000',
	'pa': '\e000',
	'paa': '\e000',
	'paaa': '\e000',
	'pu': '\e000',
	'puu': '\e000',
	'pe': '\e000',
	'pee': '\e000',
	'pɛ': '\e000',
	'pɛɛ': '\e000',
	'pɔ': '\e000',
	'pɔɔ': '\e000',
	'po': '\e000',
	'poo': '\e000',
	'wi': '\e00f',
	'wii': '\e00f',
	'wI': '\e00f',
	'wa': '\e00f',
	'waa': '\e00f',
	'wA': '\e00f',
	'wAA': '\e00f',
	'wu': '\e00f',
	'wuu': '\e00f',
	'we': '\e00f',
	'wee': '\e00f',
	'wE': '\e00f',
	'wɛ': '\e00f',
	'wɛɛ': '\e00f',
	'wƐ': '\e00f',
	'wƐƐ': '\e00f',
	'wɔ': '\e00f',
	'wɔɔ': '\e00f',
	'wo': '\e00f',
	'woo': '\e00f',
	'mbi': '\e025',
	'mbii': '\e025',
	'mba': '\e025',
	'mbaa': '\e025',
	'mbu': '\e025',
	'mbuu': '\e025',
	'mbU': '\e025',
	'mbUU': '\e025',
	'mbe': '\e025',
	'mbee': '\e025',
	'mbE': '\e025',
	'mbɛ': '\e025',
	'mbɛɛ': '\e025',
	'mbƐ': '\e025',
	'mbƐƐ': '\e025',
	'mbɔ': '\e025',
	'mbɔɔ': '\e025',
	'mbƆ': '\e025',
	'mbƆƆ': '\e025',
	'mbo': '\e025',
	'mbO': '\e025',
	'bi': '\e03b',
	'bii': '\e03b',
	'ba': '\e03b',
	'baa': '\e03b',
	'bu': '\e03b',
	'buu': '\e03b',
	'be': '\e03b',
	'bee': '\e03b',
	'bɛ': '\e03b',
	'bɔ': '\e03b',
	'bɔɔ': '\e03b',
	'bo': '\e03b',
	'boo': '\e03b',
	'booo': '\e03b',
	'kpi': '\e049',
	'kpa': '\e049',
	'kpaa': '\e049',
	'kpaaa': '\e049',
	'kpu': '\e049',
	'kpuu': '\e049',
	'kpe': '\e049',
	'kpɛ': '\e049',
	'kpɛɛ': '\e049',
	'kpɛɛɛ': '\e049',
	'kpɔ': '\e049',
	'kpɔɔ': '\e049',
	'kpo': '\e049',
	'gbi': '\e056',
	'gba': '\e056',
	'gbaa': '\e056',
	'gbu': '\e056',
	'gbe': '\e056',
	'gbɛ': '\e056',
	'gbɛɛ': '\e056',
	'gbɔ': '\e056',
	'gbɔɔ': '\e056',
	'gbo': '\e056',
	'gboo': '\e056',
	'fi': '\e061',
	'fa': '\e061',
	'fu': '\e061',
	'fe': '\e061',
	'fee': '\e061',
	'fɛ': '\e061',
	'fɛɛ': '\e061',
	'fɔ': '\e061',
	'fo': '\e061',

	'vi': '\e06c',
	'va': '\e06c',
	'vaa': '\e06c',
	'vu': '\e06c',
	'vuu': '\e06c',
	've': '\e06c',
	'vee': '\e06c',
	'vɛ': '\e06c',
	'vɛɛ': '\e06c',
	'vɔ': '\e06c',
	'vo': '\e06c',
	'voo': '\e06c',
	'ti': '\e079',
	'tii': '\e079',
	'ta': '\e079',
	'taa': '\e079',
	'tu': '\e079',
	'tuu': '\e079',
	'te': '\e079',
	'tee': '\e079',
	'tɛ': '\e079',
	'tɛɛ': '\e079',
	'tɔ': '\e079',
	'to': '\e079',
	'too': '\e079',

	'li': '\e086',
	'lii': '\e086',
	'liii': '\e086',
	'la': '\e086',
	'laa': '\e086',
	'laaa': '\e086',
	'lA': '\e086',
	'lu': '\e086',
	'luu': '\e086',
	'le': '\e086',
	'lee': '\e086',
	'lɛ': '\e086',
	'lɛɛ': '\e086',
	'lɛɛɛ': '\e086',
	'lɔ': '\e086',
	'lɔɔ': '\e086',
	'lo': '\e086',
	'loo': '\e086',
	'ndi': '\e09a',
	'ndii': '\e09a',
	'nda': '\e09a',
	'ndaa': '\e09a',
	'ndu': '\e09a',
	'nduu': '\e09a',
	'nde': '\e09a',
	'ndee': '\e09a',
	'ndɛ': '\e09a',
	'ndɛɛ': '\e09a',
	'ndɛɛɛ': '\e09a',
	'ndɔ': '\e09a',
	'ndɔɔ': '\e09a',
	'ndo': '\e09a',
	'ndoo': '\e09a',

	'di': '\e0a9',
	'dii': '\e0a9',
	'da': '\e0a9',
	'daa': '\e0a9',
	'du': '\e0a9',
	'duu': '\e0a9',
	'de': '\e0a9',
	'dee': '\e0a9',
	'dɔ': '\e0a9',
	'dɔɔ': '\e0a9',
	'do': '\e0a9',

	'si': '\e0b4',
	'sii': '\e0b4',
	'sa': '\e0b4',
	'saa': '\e0b4',
	'su': '\e0b4',
	'suu': '\e0b4',
	'se': '\e0b4',
	'see': '\e0b4',
	'sɛ': '\e0b4',
	'sɛɛ': '\e0b4',
	'sɔ': '\e0b4',
	'sɔɔ': '\e0b4',
	'so': '\e0b4',
	'soo': '\e0b4',

	'ji': '\e0c2',
	'jii': '\e0c2',
	'ja': '\e0c2',
	'jaa': '\e0c2',
	'ju': '\e0c2',
	'juu': '\e0c2',
	'je': '\e0c2',
	'jee': '\e0c2',
	'jɛ': '\e0c2',
	'jɛɛ': '\e0c2',
	'jɔ': '\e0c2',
	'jɔɔ': '\e0c2',
	'jo': '\e0c2',

	'nja': '\e0cf',
	'njaa': '\e0cf',
	'nju': '\e0cf',
	'njuu': '\e0cf',
	'nje': '\e0cf',
	'njee': '\e0cf',
	'njeee': '\e0cf',
	'njɔ': '\e0cf',
	'njɔɔ': '\e0cf',
	'njo': '\e0cf',
	'njoo': '\e0cf',

	'yi': '\e0da',
	'ya': '\e0da',
	'yu': '\e0da',
	'ye': '\e0da',
	'yee': '\e0da',
	'yeee': '\e0da',
	'yɛ': '\e0da',
	'yɛɛ': '\e0da',
	'yɔ': '\e0da',
	'yɔɔ': '\e0da',
	'yo': '\e0da',
	'yoo': '\e0da',

	'ŋgi': '\e0e6',
	'ŋgii': '\e0e6',
	'ŋga': '\e0e6',
	'ŋgaa': '\e0e6',
	'ŋgu': '\e0e6',
	'ŋguu': '\e0e6',
	'ŋge': '\e0e6',
	'ŋgee': '\e0e6',
	'ŋgeee': '\e0e6',
	'ŋgɛ': '\e0e6',
	'ŋgɔ': '\e0e6',
	'ŋgɔɔ': '\e0e6',
	'ŋgo': '\e0e6',
	'ŋgoo': '\e0e6',

	'gi': '\e0f6',
	'gii': '\e0f6',
	'ga': '\e0f6',
	'gaa': '\e0f6',
	'gaaa': '\e0f6',
	'gu': '\e0f6',
	'guu': '\e0f6',
	'ge': '\e0f6',
	'gee': '\e0f6',
	'gɛ': '\e0f6',
	'gɛɛ': '\e0f6',
	'gɔ': '\e0f6',
	'gɔɔ': '\e0f6',
	'go': '\e0f6',
	'goo': '\e0f6',

	'ki': '\e109',
	'kii': '\e109',
	'ka': '\e109',
	'kaa': '\e109',
	'ku': '\e109',
	'kuu': '\e109',
	'ke': '\e109',
	'kee': '\e109',
	'kɛ': '\e109',
	'kɔ': '\e109',
	'kɔɔ': '\e109',
	'ko': '\e109',
	'koo': '\e109',

	'hi': '\e117',
	'ha': '\e117',
	'hu': '\e117',
	'huu': '\e117',
	'huuu': '\e117',
	'he': '\e117',
	'hɛ': '\e117',
	'hɛɛ': '\e117',
	'hɔ': '\e117',
	'hɔɔ': '\e117',
	'hɔɔɔ': '\e117',
	'ho': '\e117',

	'i': '\e127',
	'a': '\e127',
	'aa': '\e127',
	'u': '\e127',
	'uu': '\e127',
	'e': '\e127',
	'ee': '\e127',
	'ɛ': '\e127',
	'ɛɛ': '\e127',
	'ɔ': '\e127',
	'ɔɔ': '\e127',
	'o': '\e127',

	'h̃ĩ': '\e134',
	'h̃ĩĩ': '\e134',
	'h̃ã': '\e134',
	'h̃ãã': '\e134',
	'h̃ũ': '\e134',
	'h̃ũũ': '\e134',
	'h̃ɛ̃': '\e134',
	'h̃ɛ̃ɛ̃': '\e134',
	'h̃ɔ̃': '\e134',
	'h̃ɔ̃ɔ̃': '\e134',
	'mĩ': '\e140',
	'mã': '\e140',
	'mũ': '\e140',
	'mɛ̃': '\e140',
	'mɔ̃': '\e140',
	'nĩ': '\e149',
	'nã': '\e149',
	'nũ': '\e149',
	'nẽ': '\e149',
	'nɛ̃': '\e149',
	'nɛ̃ɛ̃': '\e149',
	'nɔ̃': '\e149',

	'nyĩ': '\e150',
	'nyã': '\e150',
	'nyũ': '\e150',
	'nyũũ': '\e150',
	'nyɛ̃': '\e150',
	'nyɛ̃ɛ̃': '\e150',
	'nyɔ̃': '\e150',
	'nyɔ̃ɔ̃': '\e150',

	'ŋã': '\e158',
	'ŋãã': '\e158',
	'ŋɛ̃': '\e158',
	'ŋɛ̃ɛ̃': '\e158',

	'ĩ': '\e15d',
	'ĩĩ': '\e15d',
	'ẽ': '\e15d',
	'ɛ̃': '\e15d',
	'ɛ̃ɛ̃': '\e15d',
}

mende_map = {
	'A':'\ue160',
	'Hc':'\ue13d',
	'Hcc':'\ue13e',
	'Hr':'\ue13b',
	'Hrr':'\ue13a',
	'Hu':'\ue138',
	'Huu':'\ue139',
	'I':   '\ue15f',
	'I':'\ue15f',
	'Lrr':'\ue099',
	'Lrrr':'\ue098',
	'Nr':'\ue15a',
	'Nrr':'\ue15b',
	'R':'\ue161',
	'RR':'\ue162',
	'a':  '\ue128',
	'a': '\ue128',
	'aa': '\ue129',
	'aa': '\ue129',
	'b':   '\ue03b',
	'bi':  '\ue03c',    
	'c':  '\ue130',
	'c': '\ue130',
	'cc': '\ue311',
	'cc':'\ue311',
	'd':   '\ue0a9',
	'di':  '\ue0aa',
	'e':  '\ue12d',
	'e': '\ue12d',
	'ee': '\ue12c',
	'ee':'\ue12c',
	'f':   '\ue061',
	'faa':'\ue06a',
	'faaa':'\ue06b',
	'g':   '\ue0f6',
	'g': '\ue0f6',
	'ga':'\ue0fa',
	'gaa':'\ue0f8',
	'gaaa':'\ue0f9',
	'gb':  '\ue056',
	'gc':'\ue101',
	'gcc':'\ue102',
	'ge':'\ue0fd',
	'gee':'\ue0fe',
	'gi':  '\ue0f7',
	'gi': '\ue0f7',
	'go':'\ue104',
	'goo':'\ue103',
	'gr':'\ue0ff',
	'gri':'\ue107',
	'grii':'\ue108',
	'grr':'\ue100',
	'gu':'\ue0fb',
	'gua':'\ue105',
	'guaa':'\ue106',
	'guu':'\ue0fc',
	'h':   '\ue117',
	'h': '\ue117',
	'ha':'\ue118',
	'haa':'\ue137',
	'haaa':'\ue136',
	'hc':'\ue11f',
	'hcc':'\ue120',
	'hccc':'\ue121',
	'he':'\ue11c',
	'hi':  '\ue134',
	'hi': '\ue134',
	'hii': '\ue135',
	'hii':'\ue135',
	'ho':'\ue122',
	'hr':'\ue11d',
	'hrr':'\ue11e',
	'hu':'\ue11b',
	'hua':'\ue13f',
	'huaa':'\ue13e',
	'huu':'\ue11a',
	'huuu':'\ue119',
	'i':  '\ue127',
	'i':'\ue127',
	'ii':  '\ue15d',
	'ii':'\ue15d',
	'iii': '\ue15e',
	'iii':'\ue15e',
	'j':   '\ue0c2',
	'j': '\ue0c2',
	'ja': '\ue0c4',
	'jaa':'\ue0c6',
	'jc': '\ue0cc',
	'jcc':'\ue0cd',
	'je': '\ue0c8',
	'jee':'\ue0c9',
	'ji':  '\ue0c3',
	'ji': '\ue0c3',
	'jo': '\ue0ce',
	'jr': '\ue0ca',
	'jrr':'\ue0cb',
	'ju': '\ue0c6',
	'juu':'\ue0c7',
	'k':   '\ue019',
	'k': '\ue019',
	'ka':'\ue10b',
	'kaa':'\ue10c',
	'kc':'\ue112',
	'kcc':'\ue113',
	'ke':'\ue10f',
	'kee':'\ue110',
	'ki':  '\ue10a',
	'ki': '\ue10a',
	'ko':'\ue114',
	'koo':'\ue115',
	'kp':  '\ue049',
	'kr':'\ue111',
	'ku':'\ue10d',
	'kua':'\ue116',
	'kuu':'\ue10e',
	'l':   '\ue088',
	'li':  '\ue087',
	'lii': '\ue086',
	'm':   '\ue140',
	'm':'\ue140',
	'ma':'\ue141',
	'mb':  '\ue025',
	'mbi': '\ue026',
	'mc':'\ue144',
	'mr':'\ue143',
	'mu':'\ue142',
	'mua':'\ue145',
	'muaa':'\ue146',
	'n':   '\ue149',
	'n':'\ue149',
	'na':'\ue14a',
	'naa':'\ue158',
	'naaa':'\ue159',
	'nc':'\ue14e',
	'nd':  '\ue09a',
	'ndi': '\ue09b',
	'ng':  '\ue0e6',
	'ng': '\ue0e6',
	'nga':'\ue0e8',
	'ngaa':'\ue0e9',
	'nge':'\ue0ec',
	'ngee':'\ue0ed',
	'ngeee':'\ue0ee',
	'ngi': '\ue0e7',
	'ngi':'\ue0e7',
	'ngr':'\ue0ef',
	'ngu':'\ue0eb',
	'nguu':'\ue0eb',
	'nja':'\ue0cf',
	'njaa':'\ue0d0',
	'njc':'\ue0d6',
	'njcc':'\ue0d7',
	'nje':'\ue0d5',
	'njee':'\ue0d4',
	'njeee':'\ue0d3',
	'njo':'\ue0d8',
	'njoo':'\ue0d9',
	'nju':'\ue0d1',
	'njuu':'\ue0d2',
	'nr':'\ue14c',
	'nrr':'\ue14d',
	'nu':'\ue14b',
	'nua':'\ue15c',
	'ny':  '\ue150',
	'ny':'\ue150',
	'nya':'\ue151',
	'nyc':'\ue156',
	'nycc':'\ue157',
	'nyr':'\ue155',
	'nyrr':'\ue154',
	'nyu':'\ue153',
	'nyuu':'\ue152',
	'o':  '\ue132',
	'o': '\ue132',
	'p':   '\ue001',
	'pi':  '\ue000',
	'r':  '\ue12e',
	'r': '\ue12e',
	'ri':'\ue133',
	'rr': '\ue12f',
	'rr':'\ue12f',
	's':   '\ue0b5',
	's': '\ue0b5',
	'sa': '\ue0b7',
	'saa':'\ue0b6',
	'sc': '\ue0bf',
	'scc':'\ue0be',
	'se': '\ue0bb',
	'see':'\ue0ba',
	'si':  '\ue0b4',
	'si': '\ue0b4',
	'so': '\ue0c0',
	'soo':'\ue0c1',
	'sr': '\ue0bc',
	'srr':'\ue0bd ',
	'su': '\ue0b9',
	'suu':'\ue0b8',
	't':   '\ue079',
	'ti':  '\ue07a',
	'u':  '\ue12a',
	'u': '\ue12a',
	'uu': '\ue12b',
	'uu':'\ue12b',
	'v':   '\ue06c',
	'w':   '\ue010',
	'wi':  '\ue00f',
	'wii': '\ue01f',
	'wri':'\ue01d',
	'wrii':'\ue01e',
	'y':   '\ue0da',
	'y':'\ue0da',
	'ya':'\ue0db',
	'yc':'\ue0e3',
	'ycc':'\ue0e2',
	'ye':'\ue0de',
	'yee':'\ue0dd',
	'yeee':'\ue0df',
	'yo':'\ue0e4',
	'yoo':'\ue0e5',
	'yr':'\ue0e0',
	'yrr':'\ue0e1',
	'yu':'\ue0dc',
    }
#e105,e106,e107,e108 belong to other combinations to follow later
#ngo 
#ngoo 
#ngua
#nguaa
#hel
# 29-Dec-2022
mende_map_v2 = {
    's': '\ue0b5',
    'si': '\ue0b4',
    'sa': '\ue0b7',
    'saa':'\ue0b6',
    'su': '\ue0b9',
    'suu':'\ue0b8',
    'se': '\ue0bb',
    'see':'\ue0ba',
    'sr': '\ue0bc',
    'srr':'\ue0bd ',
    'sc': '\ue0bf',
    'scc':'\ue0be',
    'so': '\ue0c0',
    'soo':'\ue0c1',
    'j': '\ue0c2',
    'ji': '\ue0c3',
    'ja': '\ue0c4',
    'jaa':'\ue0c6',
    'ju': '\ue0c6',
    'juu':'\ue0c7',
    'je': '\ue0c8',
    'jee':'\ue0c9',
    'jr': '\ue0ca',
    'jrr':'\ue0cb',
    'jc': '\ue0cc',
    'jcc':'\ue0cd',
    'jo': '\ue0ce',
    'nja':'\ue0cf',
    'njaa':'\ue0d0',
    'nju':'\ue0d1',
    'njuu':'\ue0d2',
    'nje':'\ue0d5',
    'njee':'\ue0d4',
    'njeee':'\ue0d3',
    'njc':'\ue0d6',
    'njcc':'\ue0d7',
    'njo':'\ue0d8',
    'njoo':'\ue0d9',
    'y':'\ue0da',
    'ya':'\ue0db',
    'yu':'\ue0dc',
    'ye':'\ue0de',
    'yee':'\ue0dd',
    'yeee':'\ue0df',
    'yr':'\ue0e0',
    'yrr':'\ue0e1',
    'yc':'\ue0e3',
    'ycc':'\ue0e2',
    'yo':'\ue0e4',
    'yoo':'\ue0e5',
    'ng': '\ue0e6',
    'ngi':'\ue0e7',
    'nga':'\ue0e8',
    'ngaa':'\ue0e9',
    'ngu':'\ue0eb',
    'nguu':'\ue0eb',
    'nge':'\ue0ec',
    'ngee':'\ue0ed',
    'ngeee':'\ue0ee',
    'ngr':'\ue0ef',
    'g': '\ue0f6',
    'gi': '\ue0f7',
    'ga':'\ue0fa',
    'gaa':'\ue0f8',
    'gaaa':'\ue0f9',
    'gu':'\ue0fb',
    'guu':'\ue0fc',
    'ge':'\ue0fd',
    'gee':'\ue0fe',
    'gr':'\ue0ff',
    'grr':'\ue100',
    'gc':'\ue101',
    'gcc':'\ue102',
    'go':'\ue104',
    'goo':'\ue103',
    'k': '\ue019',
    'ki': '\ue10a',
    'ka':'\ue10b',
    'kaa':'\ue10c',
    'ku':'\ue10d',
    'kuu':'\ue10e',
    'ke':'\ue10f',
    'kee':'\ue110',
    'kr':'\ue111',
    'kc':'\ue112',
    'kcc':'\ue113',
    'ko':'\ue114',
    'koo':'\ue115',
    'h': '\ue117',
    'hi': '\ue134',
    'hii':'\ue135',
    'ha':'\ue118',
    'hu':'\ue11b',
    'huu':'\ue11a',
    'huuu':'\ue119',
    'he':'\ue11c',
    'hr':'\ue11d',
    'hrr':'\ue11e',
    'hc':'\ue11f',
    'hcc':'\ue120',
    'hccc':'\ue121',
    'ho':'\ue122',
    'i':'\ue127',
    'a': '\ue128',
    'aa': '\ue129',
    'u': '\ue12a',
    'uu':'\ue12b',
    'e': '\ue12d',
    'ee':'\ue12c',
    'r': '\ue12e',
    'rr':'\ue12f',
    'c': '\ue130',
    'cc':'\ue311',
    'o':'\ue132',
    'haa':'\ue137',
    'haaa':'\ue136',
    'Hu':'\ue138',
    'Huu':'\ue139',
    'Hr':'\ue13b',
    'Hrr':'\ue13a',
    'Hc':'\ue13d',
    'Hcc':'\ue13e',
    'm':'\ue140',
    'ma':'\ue141',
    'mu':'\ue142',
    'mr':'\ue143',
    'mc':'\ue144',
    'n':'\ue149',
    'na':'\ue14a',
    'nu':'\ue14b',
    'nr':'\ue14c',
    'nrr':'\ue14d',
    'nc':'\ue14e',
    'ny':'\ue150',
    'nya':'\ue151',
    'nyu':'\ue153',
    'nyuu':'\ue152',
    'nyr':'\ue155',
    'nyrr':'\ue154',
    'nyc':'\ue156',
    'nycc':'\ue157',
    'naa':'\ue158',
    'naaa':'\ue159',
    'Nr':'\ue15a',
    'Nrr':'\ue15b',
    'ii':'\ue15d',
    'iii':'\ue15e',
    'I':'\ue15f',
    'A':'\ue160',
    'R':'\ue161',
    'RR':'\ue162',
    'wri':'\ue01d',
    'wrii':'\ue01e',
    'gri':'\ue107',
    'grii':'\ue108',
    'ri':'\ue133',
    'gua':'\ue105',
    'guaa':'\ue106',
    'kua':'\ue116',
    'hua':'\ue13f',
    'huaa':'\ue13e',
    'mua':'\ue145',
    'muaa':'\ue146',
    'nua':'\ue15c',
    'faa':'\ue06a',
    'faaa':'\ue06b',
    'Lrr':'\ue099',
    'Lrrr':'\ue098',
}

old_mende_map = {
	'I':   '\ue15f',
	'a':  '\ue128',
	'aa': '\ue129',
	'b':   '\ue03b',
	'b.': '\ue03b',
	'ba': '\ue03d',
	'baa': '\ue03c',
	'bc': '\ue044',
	'bcc': '\ue044',
	'be': '\ue041',
	'bee': '\ue042',
	'bi':  '\ue03c',    
	'bi.':  '\ue03c',
	'bo': '\ue048',
	'boo': '\ue046',
	'booo': '\ue047',
	'br': '\ue043',
	'bu': '\ue03f',
	'buu': '\ue040',
	'c':  '\ue130',
	'cc': '\ue131',
	'd':   '\ue0a9',
	'di':  '\ue0aa',
	'e':  '\ue12d',
	'ee': '\ue12c',
	'f':   '\ue061',
	'g':   '\ue0f6',
	'gb':  '\ue056',
	'gi':  '\ue0f7',
	'h':   '\ue117',
	'hi':  '\ue134',
	'hii': '\ue135',
	'i':  '\ue127',
	'ii':  '\ue15d',
	'iii': '\ue15e',
	'j':   '\ue0c2',
	'ji':  '\ue0c3',
	'k':   '\ue019',
	'ki':  '\ue10a',
	'kp':  '\ue049',
	'kp.': '\ue049',
	'kpa': '\ue046',
	'kpaa': '\ue04a',
	'kpaaa': '\ue04c',
	'kpc': '\ue053',
	'kpcc': '\ue054',
	'kpe': '\ue04f',
	'kpo': '\ue055',
	'kpr': '\ue052',
	'kprr': '\ue051',
	'kprrr': '\ue050',
	'kpu': '\ue04d',
	'kpuu': '\ue04e',
	'l':   '\ue088',
	'li':  '\ue087',
	'lii': '\ue086',
	'm':   '\ue140',
	'mb':  '\ue025',
	'mb.':   '\ue025',
	'mba': '\ue028',
	'mbaa': '\ue027',
	'mbc': '\ue02f',
	'mbcc': '\ue030',
	'mbccc': '\ue038',
	'mbcccc': '\ue038',
	'mbe': '\ue02c',
	'mbee': '\ue02b',
	'mbeee': '\ue035',
	'mbi': '\ue026',
	'mbi.':   '\ue026',
	'mbo': '\ue03a',
	'mbr': '\ue02c',
	'mbrr': '\ue02e',
	'mbrrr': '\ue036',
	'mbrrrr': '\ue037',
	'mbu': '\ue029',
	'mbuu': '\ue02a',
	'mbuu': '\ue033',
	'mbuuu': '\ue034',
	'n':   '\ue149',
	'nd':  '\ue09a',
	'ndi': '\ue09b',
	'ng':  '\ue0e6',
	'ngi': '\ue0e7',
	'ny':  '\ue150',
	'o':  '\ue132',
	'p':    '\ue001',
	'pA':   '\ue004',	
	'pa':   '\ue002',
	'paa':  '\ue003',
	'paaa':   '\ue004',	
	'pc': '\ue00c',
	'pcc': '\ue025', 
	'pe':   '\ue007',
	'pee':  '\ue021',
	'pi':   '\ue000',
	'po': '\ue00e',
	'poo': '\ue00d',
	'pr': '\ue023',
	'pr': '\ue023',
	'prr': '\ue024',
	'pu':   '\ue005',
	'puu':  '\ue006',
	'pɔ':	  '\ue00b',
	'pɔɔ':  '\ue00c',
	'pɛ':   '\ue009',
	'pɛɛ':  '\ue00a',
	'r':  '\ue12e',
	'rr': '\ue12f',
	's':   '\ue0b5',
	'si':  '\ue0b4',
	't':   '\ue079',
	'ti':  '\ue07a',
	'u':  '\ue12a',
	'uu': '\ue12b',
	'v':   '\ue06c',
	'w': '\ue010', 
	'wa': '\ue012',
	'waa': '\ue011',
	'waaa': '\ue021',
	'waaaa': '\ue020',
	'we': '\ue015',
	'wee': '\ue016',
	'weee': '\ue022',
	'wi': '\ue00f',
	'wii': '\ue01f',
	'wii': '\ue01f',
	'wu': '\ue014',
	'wuu': '\ue013',
	'y': '\ue0da',
    }

class keyboard_data ():
    def __init__(self, filename):
        file = open(filename, mode='r', encoding='utf-8')
        self.raw_data = file.readlines()

        #print('KB = %s' % self.raw_data)
        return

    def fields(self):
        # Find the LAYOUT = line
        start_line_num = -1
        last_brace_line = -1
        line_num = 0
        for line in self.raw_data:
            layout_pos = line.find('LAYOUT = {')

            if layout_pos >= 0 and start_line_num < 0:
                start_line_num = line_num
                # Got the line for start of the data
                print('LAYOUT_POS = %s %s' % (layout_pos, line))

            close_brace_pos = line.find('}')
            if close_brace_pos >= 0:
                # Got the line for start of the data
#                print('LAYOUT_POS = %s %s' % (close_brace_pos, line))
                last_brace_line = line_num

            line_num += 1

        print('start: %s' % (self.raw_data[start_line_num]))
        print('last:  %s' % (self.raw_data[last_brace_line]))

        # TODO: Start with a single '{'
        these_lines = ['{', ' '.join(self.raw_data[start_line_num+1:
                                                   last_brace_line + 1]).replace("\\", "")]
        print('these_lines = %s' % ' '.join(these_lines))

        try:
            self.data_dict = ast.literal_eval(these_lines)
            print(self.data_dict['title'])
        except BaseException as err:
            print('Error = %s' % err)
            
    def getTransforms(self):
        
        return

    
input_rules = {
        'p':   '\ue001',
        'pi':  '\ue000',
        'w':   '\ue010',
        'wi':  '\ue00f',
        'wii': '\ue01f',
        'mb':  '\ue025',
        'mbi': '\ue026',
        'b':   '\ue03b',
        'bi':  '\ue03c',    
        'kp':  '\ue049',
        'gb':  '\ue056',
        'f':   '\ue061',
        'v':   '\ue06c',
        't':   '\ue079',
        'ti':  '\ue07a',
        'l':   '\ue088',
        'li':  '\ue087',
        'lii': '\ue086',
        'nd':  '\ue09a',
        'ndi': '\ue09b',
        'd':   '\ue0a9',
        'di':  '\ue0aa',
        's':   '\ue0b5',
        'si':  '\ue0b4',
        'j':   '\ue0c2',
        'ji':  '\ue0c3',
        'y':   '\ue0da',
        'ng':  '\ue0e6',
        'ngi': '\ue0e7',
        'g':   '\ue0f6',
        'gi':  '\ue0f7',
        'k':   '\ue019',
        'ki':  '\ue10a',
        'h':   '\ue117',
        'hi':  '\ue134',
        'hii': '\ue135',
        'm':   '\ue140',
        'n':   '\ue149',
        'ny':  '\ue150',
        'iii': '\ue15e',
        'ii':  '\ue15d',
        'i':  '\ue127',
        'I':   '\ue15f',
        'aa': '\ue129',
        'a':  '\ue128',
        'ee': '\ue12c',
        'e':  '\ue12d',
        'uu': '\ue12b',
        'u':  '\ue12a',
        'rr': '\ue12f',
        'r':  '\ue12e',
        'cc': '\ue131',
        'c':  '\ue130',
        'o':  '\ue132'
    }

adlamNasalizationMark = u'\U0001E94B'
adlamInitialExclamationMark = u'\U0001E95E'
adlamInitialQuestionMark = u'\U0001E95F'
reverseQuestionMark = u'\ue2e2'
# adlam_latin_map = {
#     ' ': u' ',
#     'A': u'𞤀',
#     'a': u'𞤢',
#     'AA': u'𞤀𞥄',
#     'Aa': u'𞤀𞥄',
#     'aa': u'𞤢𞥄',
#     'B': u'𞤄',
#     'b': u'𞤦',
#     'BB': u'𞤄𞥆',
#     'Bb': u'𞤄𞥆',
#     'bb': u'𞤦𞥆',
#     'Ɓ': u'𞤇',
#     'ɓ': u'𞤩',
#     'ƁƁ': u'𞤇𞥆',
#     'Ɓɓ': u'𞤇𞥆',
#     'ɓƁ': u'𞤩𞥆',
#     'ɓɓ': u'𞤩𞥆',
#     'BH': u'𞤇',
#     'Bh': u'𞤇',
#     'BBH': u'𞤇𞥆',
#     'Bbh': u'𞤇𞥆',
#     'bh': u'𞤩',
#     'bbh': u'𞤩𞥆',
#     'C': u'𞤕',
#     'c': u'𞤷',
#     'CC': u'𞤕𞥆',
#     'Cc': u'𞤕𞥆',
#     'cc': u'𞤷𞥆',
#     'D': u'𞤁',
#     'd': u'𞤣',
#     'DD': u'𞤁𞥆',
#     'Dd': u'𞤁𞥆',
#     'dd': u'𞤣𞥆',
#     'Ɗ': u'𞤍',
#     'ɗ': u'𞤯',
#     'ƊƊ': u'𞤍𞥆',
#     'Ɗɗ': u'𞤍𞥆',
#     'ɗɗ': u'𞤯𞥆',
#     'DH': u'𞤍',
#     'Dh': u'𞤍',
#     'dH': u'𞤯',
#     'dh': u'𞤯',
#     'DDH': u'𞤍𞥆',
#     'Ddh': u'𞤍𞥆',
#     'ddh': u'𞤯𞥆',
#     'E': u'𞤉',
#     'e': u'𞤫',
#     'EE': u'𞤉𞥅',
#     'Ee': u'𞤉𞥅',
#     'ee': u'𞤫𞥅',
#     'F': u'𞤊',
#     'f': u'𞤬',
#     'FF': u'𞤊𞥆',
#     'Ff': u'𞤊𞥆',
#     'ff': u'𞤬𞥆',
#     'G': u'𞤘',
#     'g': u'𞤺',
#     'GG': u'𞤘𞥆',
#     'Gg': u'𞤘𞥆',
#     'gg': u'𞤺𞥆',
#     'GB': u'𞤞',
#     'gb': u'𞥀',
#     'GGB': u'𞤞𞥆',
#     'Ggb': u'𞤞𞥆',
#     'ggb': u'𞥀𞥆',
#     'H': u'𞤖',
#     'h': u'𞤸',
#     'HH': u'𞤖𞥆',
#     'Hh': u'𞤖𞥆',
#     'hh': u'𞤸𞥆',
#     'I': u'𞤋',
#     'i': u'𞤭',
#     'II': u'𞤋𞥅',
#     'Ii': u'𞤋𞥅',
#     'ii': u'𞤭𞥅',
#     'J': u'𞤔',
#     'j': u'𞤶',
#     'JJ': u'𞤔𞥆',
#     'Jj': u'𞤔𞥆',
#     'jj': u'𞤶𞥆',
#     'K': u'𞤑',
#     'k': u'𞤳',
#     'KK': u'𞤑𞥆',
#     'Kk': u'𞤑𞥆',
#     'kk': u'𞤳𞥆',
#     'KH': u'𞤝',
#     'kh': u'𞤿',
#     'KKH': u'𞤝𞥆',
#     'Kkh': u'𞤝𞥆',
#     'kkh': u'𞤿𞥆',
#     'X': u'𞤝',
#     'x': u'𞤿',
#     'XX': u'𞤝𞥆',
#     'Xx': u'𞤝𞥆',
#     'xx': u'𞤿𞥆',
#     'L': u'𞤂',
#     'l': u'𞤤',
#     'LL': u'𞤂𞥆',
#     'Ll': u'𞤂𞥆',
#     'll': u'𞤤𞥆',
#     'M': u'𞤃',
#     'm': u'𞤥',
#     'MM': u'𞤃𞥆',
#     'Mm': u'𞤃𞥆',
#     'mm': u'𞤥𞥆',
#     'N': u'𞤐',
#     'n': u'𞤲',
#     'NN': u'𞤐𞥆',
#     'Nn': u'𞤐𞥆',
#     'nn': u'𞤲𞥆',
#     'Ŋ': u'𞤛',
#     'ŋ': u'𞤽',
#     'ŊŊ': u'𞤛𞥆',
#     'Ŋŋ': u'𞤛𞥆',
#     'ŋŋ': u'𞤽𞥆',
#     'NH': u'𞤛',
#     'Nh': u'𞤛',
#     'nH': u'𞤽',
#     'nh': u'𞤽',
#     'NNH': u'𞤛𞥆',
#     'Nnh': u'𞤛𞥆',
#     'nnh': u'𞤽𞥆',
#     'Ñ': u'𞤙',
#     'ñ': u'𞤻',
#     'ÑÑ': u'𞤙𞥆',
#     'Ññ': u'𞤙𞥆',
#     'ññ': u'𞤻𞥆',
#     'NY': u'𞤙',
#     'ny': u'𞤻',
#     'NNY': u'𞤙𞥆',
#     'Nny': u'𞤙𞥆',
#     'nny': u'𞤻𞥆',
#     'O': u'𞤌',
#     'o': u'𞤮',
#     'OO': u'𞤌𞥅',
#     'Oo': u'𞤌𞥅',
#     'oo': u'𞤮𞥅',
#     'P': u'𞤆',
#     'p': u'𞤨',
#     'PP': u'𞤆𞥆',
#     'Pp': u'𞤆𞥆',
#     'pp': u'𞤨𞥆',
#     'KP': u'𞤠',
#     'kp': u'𞥂',
#     'KKP': u'𞤠𞥆',
#     'Kkp': u'𞤠𞥆',
#     'kkp': u'𞥂𞥆',
#     'Q': u'𞤗',
#     'q': u'𞤹',
#     'QQ': u'𞤗𞥆',
#     'Qq': u'𞤗𞥆',
#     'qq': u'𞤹𞥆',
#     'GH': u'𞤗',
#     'gh': u'𞤹',
#     'GGH': u'𞤗𞥆',
#     'Ggh': u'𞤗𞥆',
#     'ggh': u'𞤹𞥆',
#     'R': u'𞤈',
#     'r': u'𞤪',
#     'RR': u'𞤈𞥆',
#     'Rr': u'𞤈𞥆',
#     'rr': u'𞤪𞥆',
#     'S': u'𞤅',
#     's': u'𞤧',
#     'SS': u'𞤅𞥆',
#     'Ss': u'𞤅𞥆',
#     'ss': u'𞤧𞥆',
#     'SH': u'𞤡',
#     'Sh': u'𞤡',
#     'sh': u'𞥃',
#     'sH': u'𞥃',
#     'SSH': u'𞤡𞥆',
#     'Ssh': u'𞤡𞥆',
#     'ssh': u'𞥃𞥆',
#     'T': u'𞤚',
#     't': u'𞤼',
#     'TT': u'𞤚𞥆',
#     'Tt': u'𞤚𞥆',
#     'tt': u'𞤼𞥆',
#     'U': u'𞤓',
#     'u': u'𞤵',
#     'UU': u'𞤓𞥅',
#     'Uu': u'𞤓𞥅',
#     'uu': u'𞤵𞥅',
#     'V': u'𞤜',
#     'v': u'𞤾',
#     'VV': u'𞤜𞥆',
#     'Vv': u'𞤜𞥆',
#     'vv': u'𞤾𞥆',
#     'W': u'𞤏',
#     'w': u'𞤱',
#     'WW': u'𞤏𞥆',
#     'Ww': u'𞤏𞥆',
#     'ww': u'𞤱𞥆',
#     'Y': u'𞤒',
#     'y': u'𞤴',
#     'YY': u'𞤒𞥆',
#     'Yy': u'𞤒𞥆',
#     'yy': u'𞤴𞥆',
#     'Ƴ': u'𞤎',
#     'ƴ': u'𞤰',
#     'ƳƳ': u'𞤎𞥆',
#     'Ƴƴ': u'𞤎𞥆',
#     'ƴƴ': u'𞤰𞥆',
#     'YH': u'𞤎',
#     'yh': u'𞤰',
#     'YYH': u'𞤎𞥆',
#     'Yyh': u'𞤎𞥆',
#     'yyh': u'𞤰𞥆',
#     'Z': u'𞤟',
#     'z': u'𞥁',
#     'ZZ': u'𞤟𞥆',
#     'Zz': u'𞤟𞥆',
#     'zz': u'𞥁𞥆',
#     'ND': "𞤐'𞤁",
#     'Nd': "𞤐'𞤁",
#     'nd': "𞤲'𞤣",
#     'MB': "𞤐'𞤄",
#     'Mb': "𞤐'𞤄",
#     'mb': "𞤲'𞤦",
#     'NJ': "𞤐'𞤔",
#     'Nj': "𞤐'𞤔",
#     'nj': "𞤲'𞤶",
#     'NG': "𞤐'𞤘",
#     'Ng': "𞤐'𞤘",
#     'ng': "𞤲'𞤺",
#     'nnd': u'𞤲𞤣',
#     'mmb': u'𞤥𞤦',
#     'nnj': u'𞤲𞤶',
#     'nng': u'𞤲𞤺',
#     '0': u'𞥐',
#     '1': u'𞥑',
#     '2': u'𞥒',
#     '3': u'𞥓',
#     '4': u'𞥔',
#     '5': u'𞥕',
#     '6': u'𞥖',
#     '7': u'𞥗',
#     '8': u'𞥘',
#     '9': u'𞥙',
#     '': u'',
#     ',': u'⹁',
#     '\u061f': reverseQuestionMark,
#     # ';': u'⁏'
#     #'?':  u'?',
#     #u'\u201c': u'\u201c',
#     #u'\u201d': u'\u201d',
#             ':': ':',
#     '!': '!',
#     "\u0027": adlamNasalizationMark,
# }

# rev = in_parsed.sort(key=sortRevN, reverse=True)

#print(in_parsed)

#out = '|'.join(in_parsed)
#print(out)

def sortRevN(a):
    
    return len(a)*10000 + ord(a[0])

def processRules(rules):
    keys = list(rules.keys())
    keys.sort(key=sortRevN, reverse=True)

    weights = [sortRevN(a) for a in keys]
    print(weights)

    print('|'.join(keys).replace('',''))
    print(28*'-')
    
    # The elements in history for pruning
    historyPruneRegex = set()
    for key in keys:
        if len(key) > 1:
            historyPruneRegex.add(key[0:-1])
    allHistory = sorted(historyPruneRegex)
    allHistory.sort(key=sortRevN, reverse=True)
    print('|'.join(allHistory))
            

def main(argv):
    # TODO: get the file and open it
    if len(argv) > 1:
        kb_data = keyboard_data(argv[1])
        kb_data.fields()
    else:
        print('No filename given')

    #processRules(adlam_latin_map)
    #processRules(adlam_to_latin_map)
    
    # TODO: Process rules from the keyboard
    # processRules(input_rules)
    processRules(mende_map_v3)
    return

if __name__ == '__main__':
    main(sys.argv)
